name: NATURAL LANGUAGE PROCESSING PROJECTS
name_cn: 自然语言处理项目
slug: natural-language-processing-projects
toc:
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 关于技术审稿人
- - '#'
  - 第1章 自然语言处理与人工智能概述
- - '##'
  - 机器学习
- - '###'
  - 监督学习
- - '####'
  - 回归
- - '####'
  - 分类
- - '###'
  - 无监督学习
- - '####'
  - 聚类
- - '#####'
  - k-means 聚类
- - '#####'
  - 层次聚类
- - '####'
  - 降维
- - '###'
  - 强化学习
- - '###'
  - 线性回归
- - '###'
  - 逻辑回归
- - '####'
  - 分类
- - '####'
  - 回归
- - '###'
  - 随机森林
- - '###'
  - 支持向量机
- - '####'
  - 非线性数据：核技巧
- - '###'
  - 神经网络
- - '###'
  - 深度神经网络
- - '###'
  - 卷积神经网络
- - '###'
  - RNN
- - '##'
  - 自然语言处理概念
- - '###'
  - 非结构化数据
- - '####'
  - 自然语言处理
- - '###'
  - 文本预处理
- - '###'
  - 文本到特征
- - '####'
  - 独热编码 (OHE)
- - '####'
  - 计数向量化器
- - '####'
  - 词频-逆文档频率 (TF-IDF)
- - '####'
  - 词嵌入
- - '###'
  - 应用
- - '####'
  - 文本分类
- - '####'
  - 文本摘要
- - '####'
  - 文本生成
- - '#'
  - 第2章 AI 生命周期
- - '##'
  - 理解并定义业务问题
- - '##'
  - 将业务问题转化为机器学习问题并创建解决方案/架构设计
- - '##'
  - 数据收集与理解
- - '##'
  - 数据清洗与预处理
- - '##'
  - 探索性数据分析
- - '##'
  - 特征工程与选择
- - '##'
  - 模型构建、调优与选择
- - '##'
  - 模型测试与验证
- - '##'
  - 预测与洞察
- - '##'
  - 部署或生产化及模型维护
- - '#'
  - 第3章 业务背景：Product360：情感与情绪检测器
- - '##'
  - 问题陈述
- - '##'
  - 方法制定
- - '###'
  - 解决此问题的步骤
- - '##'
  - 构建情绪分类器模型
- - '###'
  - 情绪分类器的数据
- - '###'
  - 数据清洗与预处理
- - '###'
  - 标签编码
- - '###'
  - 训练-测试集划分
- - '###'
  - 特征工程
- - '###'
  - 模型构建阶段
- - '####'
  - 多项式朴素贝叶斯
- - '####'
  - 线性分类器/逻辑回归
- - '####'
  - 支持向量机
- - '####'
  - 随机森林
- - '##'
  - 模型评估与比较总结
- - '###'
  - 所选模型的混淆矩阵
- - '###'
  - 精确率、召回率、F1 分数、支持度
- - '##'
  - 实时数据提取
- - '###'
  - Twitter API
- - '###'
  - 对 Twitter 数据进行文本预处理
- - '####'
  - 转换为小写
- - '####'
  - 移除标点符号
- - '####'
  - 移除停用词
- - '####'
  - 拼写纠正
- - '###'
  - 预测情绪
- - '####'
  - 词级别 tf-idf
- - '####'
  - 获取预测的情绪
- - '###'
  - 预测情感
- - '###'
  - 可视化与洞察
- - '###'
  - 情绪分析
- - '###'
  - 情绪与情感分析
- - '###'
  - 自动化报告
- - '###'
  - 总结
- - '#'
  - 第4章 使用机器学习进行 TED 演讲分割与主题提取
- - '##'
  - 问题陈述
- - '##'
  - 方法制定
- - '##'
  - 数据收集
- - '##'
  - 理解数据
- - '##'
  - 数据清洗与预处理
- - '##'
  - 特征工程
- - '###'
  - 计数向量
- - '###'
  - TF-IDF 向量
- - '###'
  - 词嵌入
- - '##'
  - 模型构建阶段
- - '###'
  - K-means 聚类
- - '####'
  - 肘部法则
- - '####'
  - 轮廓系数
- - '###'
  - 以计数向量作为特征
- - '####'
  - 肘部法则
- - '####'
  - 轮廓系数
- - '###'
  - 以 TF-IDF 为特征
- - '####'
  - 肘部法则
- - '####'
  - 轮廓系数
- - '###'
  - 以词嵌入为特征
- - '####'
  - 肘部法则
- - '####'
  - 轮廓系数
- - '##'
  - 构建聚类模型
- - '###'
  - 聚类可视化
- - '##'
  - 主题建模
- - '###'
  - 聚类 1 的主题建模
- - '###'
  - 聚类 0 的主题建模
- - '##'
  - 结论
- - '#'
  - 第5章 利用高级搜索引擎和推荐系统增强电子商务
- - '##'
  - 问题陈述
- - '##'
  - 方法
- - '###'
  - 基于内容的过滤
- - '###'
  - 环境设置
- - '##'
  - 理解数据
- - '##'
  - 探索性数据分析
- - '##'
  - 数据预处理
- - '###'
  - 文本预处理
- - '####'
  - 移除标点符号
- - '####'
  - 将词条间的空白字符替换为单个空格
- - '####'
  - 移除首尾空白字符
- - '####'
  - 转换为小写
- - '####'
  - 移除停用词
- - '####'
  - 移除单个字符
- - '####'
  - 从描述中移除领域相关的停用词
- - '####'
  - 移除领域相关停用词后的高频词
- - '##'
  - 模型构建
- - '###'
  - 基于内容的推荐系统
- - '###'
  - 产品搜索引擎
- - '####'
  - 实现
- - '##'
  - 使用 PyTerrier 和 Sentence-BERT 的高级搜索引擎
- - '###'
  - 数据预处理
- - '###'
  - 构建搜索引擎
- - '##'
  - 总结
- - '#'
  - 第6章 创建简历解析、筛选与入围系统
- - '##'
  - 背景
- - '##'
  - 方法与步骤
- - '##'
  - 实现
- - '###'
  - 安装与导入所需库
- - '###'
  - 阅读简历与职位描述
- - '###'
  - 文本处理
- - '###'
  - 文本到特征
- - '###'
  - 特征降维
- - '###'
  - 模型构建
- - '###'
  - 排名
- - '###'
  - 可视化
- - '##'
  - 结论
- - '#'
  - 第7章 使用深度学习创建电子商务产品分类模型
- - '##'
  - 问题陈述
- - '##'
  - 方法与途径
- - '###'
  - 环境设置
- - '###'
  - 理解数据
- - '###'
  - 探索性数据分析
- - '###'
  - 数据预处理
- - '###'
  - 文本预处理
- - '###'
  - 特征工程
- - '###'
  - 训练-测试集划分
- - '###'
  - 模型构建
- - '####'
  - 人工神经网络
- - '####'
  - 长短期记忆网络：循环神经网络
- - '####'
  - 卷积神经网络
- - '###'
  - 评估模型
- - '####'
  - 超参数调优
- - '####'
  - 结果
- - '###'
  - 总结
- - '#'
  - 第8章 预测 Quora 中的重复问题
- - '##'
  - 问题陈述
- - '##'
  - 方法
- - '###'
  - 无监督学习
- - '###'
  - 有监督学习
- - '##'
  - 数据集
- - '##'
  - 实现：无监督学习
- - '###'
  - 数据准备
- - '###'
  - A. 使用 doc2vec 构建向量
- - '###'
  - B. 使用 BERT 模型的句子变换器
- - '###'
  - C. GPT
- - '###'
  - 查找相似问题
- - '##'
  - 实现：监督学习
- - '###'
  - 理解数据
- - '###'
  - 预处理数据
- - '###'
  - 文本到特征
- - '###'
  - 模型构建
- - '###'
  - 评估
- - '###'
  - 对新问题对的预测
- - '##'
  - 结论
- - '#'
  - 第9章 使用 CRF 和 BERT 进行命名实体识别
- - '##'
  - 问题陈述
- - '##'
  - 方法论与方案
- - '##'
  - 实现
- - '###'
  - 数据
- - '###'
  - 训练数据准备
- - '###'
  - 测试数据准备
- - '###'
  - 模型构建
- - '####'
  - 条件随机场（CRF）
- - '####'
  - 简单特征映射
- - '####'
  - 通过添加更多特征进行特征映射
- - '####'
  - BERT 变换器
- - '##'
  - 后续步骤
- - '##'
  - 总结
- - '#'
  - 第10章 使用迁移学习构建聊天机器人
- - '##'
  - 方法
- - '###'
  - 基于规则的聊天机器人
- - '###'
  - 生成式或智能聊天机器人
- - '##'
  - 聊天机器人 1：使用相似度评分的问答系统
- - '##'
  - 聊天机器人 2：基于预训练模型的上下文聊天机器人
- - '###'
  - Hugging Face Transformers
- - '##'
  - 聊天机器人 3：使用 RNN 的预训练聊天机器人
- - '##'
  - 未来展望
- - '###'
  - RASA
- - '###'
  - Microsoft Bot Framework
- - '##'
  - 结论
- - '#'
  - 第11章 新闻标题摘要
- - '##'
  - 方法
- - '###'
  - 抽取式摘要
- - '###'
  - 生成式摘要
- - '##'
  - 环境搭建
- - '##'
  - 理解数据
- - '##'
  - 文本预处理
- - '##'
  - 模型构建
- - '###'
  - BART：简单 Transformer 预训练模型
- - '###'
  - T5 预训练模型
- - '##'
  - 检查测试数据的标题
- - '##'
  - 摘要的评估指标
- - '##'
  - 未来展望
- - '##'
  - 结论
- - '#'
  - 第12章 文本生成：下一个词预测
- - '##'
  - 问题陈述
- - '##'
  - 方法：理解语言建模
- - '##'
  - 实现
- - '###'
  - 模型 1：词到词的文本生成
- - '###'
  - 模型 2：逐句处理
- - '###'
  - 模型 3：输入词序列与输出词
- - '###'
  - GPT-2（高级预训练模型）
- - '###'
  - 自动补全/建议
- - '####'
  - 快速自动补全
- - '##'
  - 结论
- - '#'
  - 第13章 结论与未来趋势
- - '##'
  - 接下来该往哪走？
- - '##'
  - AutoNLP
- - '###'
  - 什么是 AutoNLP？
- - '##'
  - 多语言自然语言处理
- - '##'
  - 对话式人工智能
- - '##'
  - 行业特定预训练模型
- - '##'
  - 图像描述
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
