name: Practical Explainable AI Using Python
name_cn: Python 可解释 AI 实用指南
slug: practical-explainable-ai-using-python
toc:
- - '#'
  - 模型可解释性与可理解性
- - '##'
  - 引言
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '##'
  - 关于技术审稿人
- - '#'
  - 1. 模型可解释性与可理解性
- - '##'
  - 建立框架
- - '##'
  - 人工智能
- - '###'
  - 可解释人工智能（XAI）的必要性
- - '###'
  - 可解释性 vs. 可理解性
- - '###'
  - 可解释性类型
- - '###'
  - 模型可解释性工具
- - '####'
  - SHAP
- - '####'
  - LIME
- - '####'
  - ELI5
- - '####'
  - Skater
- - '####'
  - Skope_rules
- - '###'
  - 机器学习可解释人工智能的方法
- - '###'
  - XAI 兼容模型
- - '###'
  - XAI 与负责任的人工智能
- - '###'
  - XAI 评估
- - '##'
  - 结论
- - '#'
  - 2. AI 伦理、偏见与可靠性
- - '##'
  - AI 伦理入门
- - '##'
  - AI 中的偏见
- - '###'
  - 数据偏见
- - '###'
  - 算法偏见
- - '###'
  - 偏见缓解流程
- - '###'
  - 解释偏见
- - '###'
  - 训练偏见
- - '##'
  - AI 的可靠性
- - '##'
  - 结论
- - '#'
  - 3. 线性模型的可解释性
- - '##'
  - 线性模型
- - '##'
  - 线性回归
- - '###'
  - VIF 及其可能引发的问题
- - '####'
  - 最终模型
- - '####'
  - 模型可解释性
- - '##'
  - 对机器学习模型的信任：SHAP
- - '###'
  - 计算线性模型的 SHAP 值
- - '###'
  - 机器学习模型中的局部解释与个体预测
- - '###'
  - 机器学习模型中的全局解释与整体预测
- - '##'
  - LIME 解释与机器学习模型
- - '##'
  - Skater 解释与机器学习模型
- - '##'
  - ELI5 解释与机器学习模型
- - '##'
  - 逻辑回归
- - '###'
  - 解释
- - '###'
  - LIME 推断
- - '##'
  - 结论
- - '#'
  - 4. 非线性模型的可解释性
- - '##'
  - 非线性模型
- - '##'
  - 决策树解释
- - '###'
  - 创建模型
- - '##'
  - 决策树 – SHAP
- - '##'
  - 使用 Scikit-Learn 的 PDP
- - '##'
  - 非线性模型解释 – LIME
- - '##'
  - 非线性解释 – Skope-Rules
- - '##'
  - 结论
- - '#'
  - 5. 集成模型的可解释性
- - '##'
  - 集成模型
- - '###'
  - 集成模型的类型
- - '##'
  - 为什么使用集成模型？
- - '##'
  - 使用 SHAP 进行集成模型分析
- - '###'
  - 波士顿房价预测
- - '###'
  - 使用可解释的增强模型
- - '###'
  - 集成分类模型：SHAP
- - '###'
  - 使用 SHAP 解释分类提升模型
- - '###'
  - 使用 SHAP 多分类 CatBoost 模型
- - '###'
  - 使用 SHAP 解释 Light GBM 模型
- - '##'
  - 结论
- - '#'
  - 6. 时间序列模型的可解释性
- - '##'
  - 时间序列模型
- - '###'
  - 判断模型优劣
- - '##'
  - 预测策略
- - '##'
  - 预测的置信区间
- - '##'
  - 信任何去何从？
- - '##'
  - 时间序列：LIME
- - '##'
  - 结论
- - '#'
  - 7. 自然语言处理的可解释性
- - '##'
  - 自然语言处理任务
- - '##'
  - 文本分类的可解释性
- - '##'
  - 文本分类数据集
- - '###'
  - 使用 ELI5 进行解释
- - '###'
  - 计算局部解释的特征权重
- - '####'
  - 局部解释示例 1
- - '####'
  - 局部解释示例 2
- - '####'
  - 局部解释示例 3
- - '####'
  - 去除停用词后的解释
- - '###'
  - 基于 N-gram 的文本分类
- - '###'
  - 多标签文本分类的可解释性
- - '####'
  - 局部解释示例 1
- - '####'
  - 局部解释示例 2
- - '####'
  - 局部解释示例 1
- - '##'
  - 结论
- - '#'
  - 8. 使用假设场景实现 AI 模型公平性
- - '##'
  - 什么是 WIT？
- - '###'
  - 安装 WIT
- - '###'
  - 评估指标
- - '##'
  - 结论
- - '#'
  - 9. 深度学习模型的可解释性
- - '##'
  - 解释深度学习模型
- - '##'
  - 将 SHAP 与深度学习结合使用
- - '###'
  - 使用 Deep SHAP
- - '###'
  - 使用 Alibi
- - '###'
  - 图像分类的另一个示例
- - '###'
  - 表格数据的深度解释器
- - '##'
  - 结论
- - '#'
  - 10. XAI 模型的反事实解释
- - '##'
  - 什么是 CFE？
- - '##'
  - CFE 的实现
- - '###'
  - 回归任务的反事实解释
- - '##'
  - 结论
- - '#'
  - 11. 机器学习的对比解释
- - '##'
  - 什么是机器学习中的对比解释？
- - '###'
  - 使用 Alibi 实现对比解释方法（CEM）
- - '###'
  - 原始图像与自编码器生成图像的对比
- - '###'
  - 表格数据的 CEM 解释
- - '##'
  - 结论
- - '#'
  - 12. 通过识别预测不变性实现模型无关解释
- - '##'
  - 什么是模型无关？
- - '##'
  - 什么是锚点？
- - '###'
  - 使用 Alibi 进行锚点解释
- - '####'
  - 文本分类的锚点解释
- - '####'
  - 图像分类的锚点图像
- - '##'
  - 结论
- - '#'
  - 13. 基于规则的专家系统的模型可解释性
- - '##'
  - 什么是专家系统？
- - '##'
  - 反向链与正向链
- - '##'
  - 使用 Scikit-Learn 进行规则提取
- - '###'
  - 对基于规则的系统的需求
- - '###'
  - 专家系统的挑战
- - '###'
  - 结论
- - '#'
  - 14. 计算机视觉的模型可解释性
- - '##'
  - 为什么图像数据需要可解释性？
- - '###'
  - 使用 Alibi 进行锚点图像解释
- - '###'
  - 积分梯度法
- - '##'
  - 结论
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G, H
- - '##'
  - I, J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N, O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T, U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
