name: Productionizing AI
name_cn: AI 生产化指南
slug: productionizing-ai
toc:
- - '#'
  - 序言
- - '#'
  - 前言
- - '#'
  - 1. 人工智能与 AI 生态系统简介
- - '##'
  - AI 生态系统
- - '###'
  - 炒作周期
- - '###'
  - 历史背景
- - '###'
  - 人工智能——一些定义
- - '###'
  - 当今的人工智能
- - '####'
  - 机器学习
- - '####'
  - 深度学习
- - '###'
  - 什么是人工智能
- - '###'
  - 云计算
- - '###'
  - 云服务提供商——它们提供什么？
- - '###'
  - 更广泛的人工智能生态系统
- - '###'
  - 全栈人工智能
- - '###'
  - 人工智能伦理与风险：问题与担忧
- - '###'
  - 人工智能生态系统：动手实践
- - '##'
  - 人工智能的应用
- - '###'
  - 机器学习
- - '###'
  - 深度学习
- - '####'
  - 计算机视觉
- - '####'
  - 投资组合、风险管理与预测
- - '###'
  - 自然语言处理
- - '####'
  - 聊天机器人
- - '####'
  - 认知机器人流程自动化 (CRPA)
- - '###'
  - 其他人工智能应用
- - '###'
  - 人工智能应用：动手实践
- - '####'
  - 调用 Azure 文本分析 API
- - '##'
  - 数据摄取与 AI 流水线
- - '###'
  - AI 工程
- - '###'
  - 什么是数据流水线？
- - '###'
  - 提取、转换、加载 (ETL)
- - '####'
  - 提取
- - '####'
  - 转换
- - '####'
  - 加载
- - '###'
  - 数据整理
- - '###'
  - 性能基准测试
- - '###'
  - 人工智能管道自动化 – AutoAI
- - '###'
  - 构建你自己的 AI 管道：动手实践
- - '##'
  - 神经网络与深度学习
- - '###'
  - 机器学习
- - '####'
  - 监督式机器学习
- - '####'
  - 无监督式机器学习
- - '####'
  - 强化学习
- - '###'
  - 什么是神经网络？
- - '###'
  - 简单感知器
- - '###'
  - 深度学习
- - '####'
  - 卷积神经网络
- - '####'
  - 循环神经网络
- - '####'
  - 自编码器和变分自编码器
- - '####'
  - 生成对抗网络
- - '###'
  - 神经网络 – 术语
- - '###'
  - 深度学习工具
- - '###'
  - 神经网络与深度学习入门：动手实践
- - '##'
  - 将 AI 投入生产
- - '###'
  - 计算与存储
- - '###'
  - CSP（云服务提供商）——为何不投资亚马逊、微软或谷歌就无法在 AI 领域取得成功
- - '####'
  - 计算服务
- - '####'
  - 存储服务
- - '####'
  - 容器化
- - '#####'
  - Docker 和 Kubernetes
- - '###'
  - 将 AI 投入生产：动手实践
- - '####'
  - 从 pycaret 仓库导入数据集
- - '####'
  - 注意：运行下方代码时，请确保按回车键继续/接受
- - '####'
  - 初始化环境
- - '####'
  - 训练线性回归模型
- - '####'
  - 保存转换管道和模型
- - '####'
  - 注意：保存到 /content 文件夹，格式为 pkl 文件
- - '####'
  - 注意：根据参考 https://github.com/pycaret/pycaret/issues/985 添加了 model_only=True
- - '##'
  - 总结
- - '#'
  - 2. AI 最佳实践与 DataOps
- - '###'
  - DataOps 和 MLOps 简介
- - '###'
  - DataOps
- - '###'
  - 数据“工厂”
- - '###'
  - 人工智能的问题：从 DataOps 到 MLOps
- - '###'
  - 企业级人工智能
- - '###'
  - GCP/BigQuery：动手实践
- - '###'
  - 使用 Kafka 进行事件流处理：动手实践
- - '##'
  - 敏捷
- - '###'
  - 敏捷团队与协作
- - '###'
  - 开发/产品冲刺
- - '###'
  - 敏捷的优势
- - '###'
  - 适应性
- - '###'
  - react.js：动手实践
- - '###'
  - VueJS：动手实践
- - '##'
  - 代码仓库
- - '###'
  - Git 与 GitHub
- - '###'
  - 版本控制
- - '###'
  - 分支与合并
- - '###'
  - Git 工作流
- - '###'
  - GitHub 与 Git：动手实践
- - '###'
  - 将应用部署到 GitHub Pages：动手实践
- - '##'
  - 持续集成与持续交付 (CI/CD)
- - '###'
  - DataOps 中的 CI/CD
- - '###'
  - Jenkins 简介
- - '###'
  - Maven
- - '###'
  - 容器化
- - '####'
  - Docker 和 Kubernetes
- - '###'
  - 玩转 Docker：动手实践
- - '####'
  - 玩转 DOCKER
- - '###'
  - 测试、性能评估与监控
- - '####'
  - Selenium
- - '####'
  - TestNG
- - '####'
  - 问题管理
- - '#####'
  - Jira
- - '#####'
  - ServiceNow
- - '###'
  - 监控与告警
- - '####'
  - Nagios
- - '###'
  - Jenkins CI/CD 与 Selenium 测试脚本：动手实践
- - '###'
  - 总结
- - '#'
  - 3. 面向人工智能的数据摄取
- - '##'
  - 数据摄取简介
- - '###'
  - 数据摄取——当今的挑战
- - '###'
  - AI 阶梯
- - '###'
  - 云架构/云“堆栈”
- - '###'
  - 计划性（OLAP）与流式（OLTP）数据
- - '####'
  - API
- - '###'
  - 数据类型（结构化与非结构化）
- - '###'
  - 文件类型
- - '###'
  - 自动化数据摄入：动手实践
- - '###'
  - 使用 Parquet：动手实践
- - '##'
  - 面向 AI 的数据存储
- - '###'
  - 数据存储：数据湖与数据仓库
- - '####'
  - 湖仓一体
- - '###'
  - 界定项目数据需求
- - '###'
  - OLTP/OLAP – 确定最佳方法
- - '###'
  - ETL 与 ELT
- - '###'
  - SQL 与 NoSQL 数据库
- - '###'
  - 弹性与可扩展性
- - '###'
  - 用于 AI 的数据存储：动手实践
- - '##'
  - 用于数据摄入的云服务
- - '###'
  - 云（SQL）数据仓库
- - '###'
  - 数据湖存储
- - '####'
  - Hadoop
- - '###'
  - 流处理与流分析
- - '###'
  - 简易数据流：动手实践
- - '####'
  - 使用 Microsoft Excel 与 Python 流式传输股票价格
- - '###'
  - 用于数据摄入的云服务：动手实践
- - '####'
  - 使用 Python 与 AWS KINESIS 进行流式传输
- - '##'
  - 数据管道编排 – 最佳实践
- - '###'
  - 存储考量
- - '###'
  - 数据摄取调度
- - '###'
  - 无服务器计算
- - '###'
  - 日终处理
- - '###'
  - 机器学习和深度学习的数据导入
- - '###'
  - 构建交付管道
- - '####'
  - 示例：XenonStack
- - '####'
  - 示例：Red Hat/IBM
- - '####'
  - 示例：AWS 无服务器架构
- - '####'
  - 示例：Databricks 与 Apache Spark
- - '###'
  - 示例：Snowflake 工作负载管理
- - '###'
  - 数据管道编排：动手实践
- - '##'
  - 总结
- - '#'
  - 4. 云端机器学习
- - '##'
  - 机器学习基础
- - '##'
  - 监督机器学习
- - '###'
  - 分类与回归
- - '###'
  - 时间序列预测
- - '###'
  - fbprophet 入门：动手实践
- - '##'
  - 无监督机器学习
- - '###'
  - 聚类
- - '###'
  - 降维
- - '###'
  - 无监督机器学习（聚类）：动手实践
- - '##'
  - 半监督机器学习
- - '##'
  - 机器学习实现
- - '###'
  - 探索性数据分析（EDA）
- - '###'
  - 数据整理
- - '####'
  - 特征工程
- - '####'
  - 数据洗牌与划分/分割
- - '####'
  - 采样
- - '####'
  - 端到端数据整理：动手实践
- - '###'
  - 算法建模
- - '##'
  - 性能基准测试
- - '###'
  - 持续改进
- - '###'
  - 机器学习分类器：动手实践
- - '##'
  - 模型选择、部署与推理
- - '###'
  - 推理：动手实践
- - '##'
  - 强化学习
- - '##'
  - 总结
- - '#'
  - 5. 神经网络与深度学习
- - '##'
  - 深度学习简介
- - '###'
  - 什么是深度学习
- - '###'
  - 深度学习——为何是现在？
- - '###'
  - AI 与深度学习炒作周期
- - '###'
  - 高层架构
- - '###'
  - TensorFlow Playground：动手实践
- - '##'
  - 随机过程
- - '###'
  - 生成式模型与判别式模型
- - '###'
  - 随机游走
- - '###'
  - 马尔可夫链与马尔可夫过程
- - '###'
  - 其他随机过程：鞅
- - '###'
  - 用 Python 实现随机游走：动手实践
- - '##'
  - 神经网络简介
- - '###'
  - 人工神经网络（ANN）
- - '###'
  - 简单感知机
- - '###'
  - 多层感知机（MLP）
- - '###'
  - 卷积神经网络（CNN）
- - '###'
  - 循环神经网络（RNN）
- - '####'
  - 长短期记忆（LSTM）网络
- - '###'
  - 其他类型的神经网络
- - '###'
  - 受限玻尔兹曼机（RBM）
- - '###'
  - 深度信念网络（DBN）
- - '###'
  - 深度玻尔兹曼机（DBM）
- - '###'
  - 自编码器
- - '###'
  - 生成对抗网络
- - '###'
  - 一个简单的深度学习解决方案——MNIST：动手实践
- - '###'
  - Keras 中的自编码器：动手实践
- - '##'
  - 深度学习工具
- - '###'
  - 深度学习工具
- - '###'
  - TensorFlow
- - '###'
  - Keras
- - '###'
  - PyTorch
- - '###'
  - 其他重要的深度学习工具
- - '####'
  - Apache Spark
- - '##'
  - 深度学习与实现框架
- - '###'
  - 张量
- - '###'
  - TensorFlow 关键概念
- - '###'
  - 深度学习建模生命周期
- - '####'
  - 定义模型
- - '####'
  - 编译模型
- - '####'
  - 拟合模型
- - '####'
  - 评估模型
- - '####'
  - 进行预测
- - '###'
  - 顺序模型 API 和函数式模型 API
- - '####'
  - 顺序模型 API
- - '#####'
  - 定义模型
- - '####'
  - 函数式模型 API
- - '#####'
  - 定义层
- - '#####'
  - 定义模型
- - '###'
  - 实现 CNN
- - '###'
  - 实现 RNN
- - '####'
  - GRU 的输出将是一个形状为 (batch_size, timesteps, 256) 的 3D 张量
- - '####'
  - SimpleRNN 的输出将是一个形状为 (batch_size, 128) 的 2D 张量
- - '####'
  - 用于时间序列的 LSTM 实现
- - '###'
  - 神经网络 – 术语
- - '###'
  - 计算多层神经网络的输出
- - '###'
  - 使用 Keras 和 TensorFlow 的卷积神经网络：动手实践
- - '###'
  - 循环神经网络 – 时间序列预测：动手实践
- - '##'
  - 调优深度学习模型
- - '###'
  - 激活函数
- - '####'
  - （逻辑）Sigmoid 函数
- - '####'
  - 双曲正切函数 (tanh)
- - '####'
  - 修正线性单元 (ReLU)
- - '####'
  - Softmax
- - '###'
  - 梯度下降与反向传播
- - '####'
  - 反向传播
- - '###'
  - 其他优化算法
- - '####'
  - 带动量的随机梯度下降
- - '####'
  - AdaGrad、Adadelta 和 RMSProp
- - '####'
  - Adam
- - '###'
  - 损失函数
- - '###'
  - 提高深度学习性能
- - '###'
  - 深度学习最佳实践 – 超参数
- - '####'
  - 网络调整
- - '#####'
  - 更深的网络/更多层/更多神经元
- - '#####'
  - 激活函数
- - '###'
  - 神经网络集成
- - '###'
  - 批量归一化
- - '###'
  - 池化
- - '###'
  - 图像增强
- - '##'
  - 过程调优
- - '###'
  - 轮数与批量大小
- - '###'
  - 学习率
- - '###'
  - 正则化
- - '###'
  - 丢弃法
- - '###'
  - 早停
- - '###'
  - 迁移学习
- - '##'
  - 总结
- - '###'
  - Softmax：动手实践
- - '###'
  - 早停法：动手实践
- - '#'
  - 6. AutoML、AutoAI 与 NoLo UI 的兴起
- - '##'
  - 机器学习：流程回顾
- - '##'
  - 全局搜索算法
- - '###'
  - 贝叶斯优化与推理
- - '###'
  - 贝叶斯推理：动手实践
- - '##'
  - 用于自动化的基于 Python 的库
- - '###'
  - PyCaret
- - '###'
  - auto-sklearn
- - '###'
  - Auto-WEKA
- - '####'
  - TPOT
- - '####'
  - 使用 TPOT 进行 Python 自动化：动手实践
- - '##'
  - AutoAI 工具与平台
- - '###'
  - IBM Cloud Pak for Data
- - '###'
  - Azure 机器学习
- - '###'
  - Google Cloud Vertex AI
- - '####'
  - Google Cloud Composer
- - '###'
  - AWS SageMaker Autopilot
- - '###'
  - TensorFlow Extended (TFX)
- - '###'
  - 总结
- - '###'
  - 使用 IBM Cloud Pak for Data 进行 AutoAI：动手实践
- - '###'
  - 使用 Google Teachable Machines 进行医疗诊断：动手实践
- - '##'
  - TFX 与 Vertex AI Pipelines：动手实践
- - '###'
  - 使用 TFX、KERAS 和 VERTEX AI 实现自动深度学习
- - '##'
  - Azure Video Analyzer：动手实践
- - '###'
  - 使用 AZURE VIDEO ANALYZER 对视频进行分类和编目
- - '#'
  - 7. AI 全栈：应用开发
- - '##'
  - AI 应用开发简介
- - '###'
  - 开发 AI 解决方案
- - '###'
  - AI 应用——启动与运行
- - '###'
  - API 和端点
- - '###'
  - 分布式处理和集群
- - '####'
  - 集群
- - '####'
  - 图形处理单元（GPU）
- - '####'
  - 张量处理单元（TPU）
- - '####'
  - 分片
- - '####'
  - 虚拟环境
- - '####'
  - 从终端运行 Python：动手实践
- - '####'
  - API Web 服务和端点：动手实践
- - '###'
  - AI 加速器 - GPU：动手实践
- - '####'
  - COLAB GPU 性能测试
- - '###'
  - AI 开发的软件与工具
- - '###'
  - AI 需要数据与云
- - '###'
  - 云平台
- - '####'
  - AWS
- - '####'
  - Azure
- - '####'
  - GCP
- - '####'
  - IBM Cloud
- - '####'
  - Heroku
- - '###'
  - 基于 Python 的用户界面
- - '####'
  - Flask
- - '####'
  - Dash
- - '####'
  - Django
- - '###'
  - 其他 AI 软件供应商
- - '####'
  - ONNX（开放神经网络交换格式）
- - '####'
  - C3
- - '####'
  - DataRobot
- - '##'
  - Dash 入门：动手实践
- - '##'
  - Flask：动手实践
- - '##'
  - Django 入门：动手实践
- - '##'
  - 机器学习应用
- - '###'
  - 开发机器学习应用
- - '###'
  - 客户体验
- - '###'
  - 欺诈检测与网络安全
- - '###'
  - 运营管理、决策与业务支持
- - '###'
  - 风险管理、投资组合与资产优化
- - '###'
  - 开发推荐引擎：动手实践
- - '####'
  - 使用 CURL 测试部署到本地端点
- - '###'
  - 投资组合优化加速器：动手实践
- - '####'
  - 使用 Python 中的 CVXPY 实现利润最大化与风险最小化
- - '##'
  - 深度学习应用
- - '###'
  - 开发深度学习应用
- - '####'
  - 关键深度学习应用
- - '#####'
  - 计算机视觉
- - '#####'
  - 预测
- - '#####'
  - 物联网
- - '###'
  - 全栈深度学习：动手实践
- - '###'
  - 总结
- - '#'
  - 8. AI 案例研究
- - '##'
  - 行业案例研究
- - '###'
  - 业务/组织对 AI 的需求
- - '###'
  - AI 赋能因素
- - '###'
  - 按垂直行业划分的 AI 解决方案
- - '###'
  - AI 用例 – 解决方案框架
- - '###'
  - 解决方案架构
- - '####'
  - 示例：Azure
- - '##'
  - 电信解决方案
- - '###'
  - 具体挑战
- - '###'
  - 解决方案类别
- - '###'
  - 实时仪表盘
- - '###'
  - 情感分析
- - '###'
  - 预测性分析
- - '###'
  - 从 Python 连接到 Twitter API
- - '###'
  - Twitter API 与基础情感分析：动手实践
- - '####'
  - 熟悉 Twitter API
- - '#####'
  - a) 分析 Twitter 信息流：
- - '#####'
  - b) 执行基础情感分析
- - '##'
  - 零售解决方案
- - '###'
  - 零售行业面临的挑战
- - '###'
  - 客户流失与留存建模
- - '####'
  - 流失建模的最佳实践方法
- - '####'
  - 模型设计与成果
- - '###'
  - 使用 GCP BigQuery 进行在线零售预测分析：动手实践
- - '###'
  - 预测客户流失：动手实践
- - '###'
  - 社交网络分析：动手实践
- - '##'
  - 银行与金融服务/金融科技解决方案
- - '###'
  - 行业挑战
- - '###'
  - 欺诈检测
- - '####'
  - 案例研究：AWS 欺诈检测
- - '###'
  - 使用 AWS SageMaker 进行 AWS 欺诈检测：动手实践
- - '##'
  - 供应链解决方案
- - '###'
  - 供应链面临的挑战
- - '###'
  - 预测分析解决方案
- - '###'
  - 供应链优化与规范分析
- - '###'
  - 使用 IBM CloudPak/Watson Studio 进行供应链优化：动手实践
- - '##'
  - 石油和天然气/能源与公用事业解决方案
- - '###'
  - 能源、石油和天然气行业面临的挑战
- - '###'
  - 能源领域的人工智能解决方案——机遇还是威胁？
- - '##'
  - 医疗保健与制药解决方案
- - '###'
  - 医疗保健——人工智能鸿沟
- - '###'
  - 医疗保健与制药解决方案
- - '##'
  - 人力资源解决方案
- - '###'
  - 2022 年的人力资源
- - '###'
  - 人力资源解决方案示例
- - '###'
  - 人力资源员工流失：动手实践
- - '##'
  - 其他案例研究
- - '###'
  - 公共部门与政府
- - '###'
  - 制造业
- - '###'
  - 网络安全
- - '###'
  - 保险/远程信息处理
- - '###'
  - 法律
- - '###'
  - DALL-E 在创意艺术领域的应用：动手实践
- - '##'
  - 总结
- - '#'
  - 9. 部署 AI 解决方案（生产化与容器化）
- - '##'
  - 生产化 AI 应用
- - '###'
  - 生产化的典型障碍
- - '###'
  - 云/CSP 轮盘赌
- - '###'
  - 简化 AI 挑战——从小处着手，保持专注
- - '###'
  - Python 数据库管理：动手实践
- - '###'
  - 在 GCP 上构建应用：动手实践
- - '###'
  - PowerBI – Python 握手：动手实践
- - '##'
  - AI 项目生命周期
- - '###'
  - 从设计思维到敏捷开发
- - '###'
  - 通过假设驱动开发
- - '###'
  - 协作、测试、衡量、重复
- - '###'
  - 持续流程改进
- - '###'
  - 数据漂移
- - '###'
  - 自动重新训练
- - '###'
  - 在 Heroku 上托管 – 端到端：动手实践
- - '##'
  - 赋能工程与基础设施
- - '###'
  - 人工智能生态系统 – 人工智能云栈
- - '###'
  - 数据湖部署 – 最佳实践
- - '###'
  - 数据管道运营与编排
- - '##'
  - 大数据引擎与并行化
- - '###'
  - Dask
- - '###'
  - 利用 S3 文件存储：动手实践
- - '###'
  - 在 Databricks 上快速上手 Apache Spark：动手实践
- - '###'
  - Dask 并行化：动手实践
- - '##'
  - 全栈与容器化……最后的边界
- - '###'
  - 全栈 AI – React 与 Flask 案例研究
- - '###'
  - 使用 Docker 容器在云上部署
- - '###'
  - 实现持续交付流水线
- - '###'
  - 总结
- - '###'
  - 使用 Streamlit 和 Heroku 部署深度学习应用：动手实践
- - '###'
  - 使用 Docker 容器在 Azure 上部署：动手实践
- - '####'
  - 将用于预测保险费的机器学习模型容器化
- - '#'
  - 10. 自然语言处理
- - '##'
  - NLP 简介
- - '###'
  - NLP 基础
- - '####'
  - NLP 的历史背景与发展
- - '###'
  - NLP 目标与特定行业用例
- - '####'
  - 关键行业应用
- - '###'
  - NLP 生命周期
- - '####'
  - 从解析到语言分析
- - '####'
  - 从词嵌入到深度学习
- - '###'
  - 创建词云：动手实践
- - '##'
  - 预处理与语言学
- - '###'
  - 预处理/初始清理
- - '####'
  - 正则表达式
- - '####'
  - 文本剥离（例如，HTML 标签）
- - '###'
  - 语言学与数据转换
- - '####'
  - 词法分析
- - '#####'
  - 移除停用词
- - '#####'
  - 分词
- - '####'
  - 句法分析
- - '#####'
  - 转换为小写
- - '#####'
  - 词性标注
- - '#####'
  - 命名实体识别
- - '#####'
  - 处理缩略形式
- - '#####'
  - 词干提取
- - '####'
  - 语义分析
- - '#####'
  - 词形还原
- - '#####'
  - 词义消歧
- - '#####'
  - N-gram
- - '###'
  - 使用 NLTK 进行文本解析：动手实践
- - '##'
  - 文本向量化、词嵌入与 NLP 建模
- - '###'
  - 基于规则/频率的嵌入
- - '####'
  - 独热编码与计数向量化
- - '####'
  - 词袋模型（BoW）
- - '####'
  - 潜在语义分析（LSA）
- - '####'
  - TF-IDF
- - '####'
  - 关于余弦相似度
- - '###'
  - 词嵌入 / 基于预测的嵌入
- - '####'
  - Word2Vec（谷歌）
- - '####'
  - 其他模型
- - '###'
  - NLP 建模
- - '####'
  - 文本摘要
- - '####'
  - 主题建模
- - '####'
  - 序列模型
- - '####'
  - 变换器与注意力模型
- - '###'
  - 词嵌入：动手实践
- - '###'
  - Seq2Seq：动手实践
- - '###'
  - PyTorch NLP：动手实践
- - '##'
  - NLP 工具与应用
- - '###'
  - Python Libraries
- - '###'
  - NLP 应用
- - '####'
  - 文本分析
- - '#####'
  - 文本转语音与语音转文本
- - '####'
  - 社交媒体情感分析/意见挖掘
- - '####'
  - 聊天机器人、对话助手和 IVA
- - '###'
  - NLP 2.0
- - '####'
  - 自然语言生成
- - '####'
  - 辩论
- - '####'
  - 自动 NLP
- - '###'
  - 总结
- - '###'
  - WATSON Assistant 聊天机器人/IVA：动手实践
- - '###'
  - 面向聊天机器人的 Transformer 模型：动手实践
- - '####'
  - 使用 GPT-3 进行自然语言生成
