name: Hands-on Question Answering Systems with BERT
name_cn: BERT 问答系统实用指南
slug: hands-on-question-answering-systems-with-bert
toc:
- - '##'
  - 引言
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '#'
  - 1. 自然语言处理简介
- - '##'
  - 自然语言处理
- - '###'
  - 句子分割
- - '####'
  - 分词
- - '####'
  - 词性标注
- - '####'
  - 词干提取与词形还原
- - '####'
  - 停用词识别
- - '####'
  - 短语提取
- - '####'
  - 命名实体识别
- - '####'
  - 共指消解
- - '####'
  - 词袋模型
- - '##'
  - 结论
- - '#'
  - 2. 自然语言处理的神经网络
- - '##'
  - 什么是神经网络？
- - '##'
  - 神经网络的构建模块
- - '###'
  - 神经元
- - '###'
  - 输入层
- - '###'
  - 隐藏层
- - '###'
  - 输出层
- - '###'
  - 激活函数
- - '##'
  - 神经网络训练
- - '##'
  - 神经网络的类型
- - '###'
  - 前馈神经网络
- - '###'
  - 卷积神经网络
- - '###'
  - 循环神经网络
- - '###'
  - 长短期记忆网络
- - '###'
  - 编码器与解码器
- - '##'
  - 编码器-解码器架构
- - '###'
  - 模型的编码器部分
- - '###'
  - 模型的解码器部分
- - '###'
  - 双向编码器和解码器
- - '###'
  - Transformer 模型
- - '###'
  - 模型架构
- - '###'
  - 注意力模型
- - '####'
  - 为什么需要注意力机制？
- - '####'
  - 注意力机制如何工作
- - '####'
  - 注意力模型的类型
- - '#####'
  - 全局注意力模型
- - '#####'
  - 局部注意力模型
- - '#####'
  - 硬注意与软注意力模型
- - '#####'
  - 自注意力模型
- - '##'
  - 结论
- - '#'
  - 3. 词嵌入简介
- - '##'
  - 独热表示
- - '###'
  - 计数向量
- - '###'
  - TF-IDF 向量化
- - '##'
  - 什么是词嵌入？
- - '##'
  - 词嵌入的不同方法
- - '###'
  - Word2vec
- - '####'
  - 连续词袋
- - '####'
  - 跳字模型
- - '###'
  - GloVe
- - '##'
  - 句子嵌入
- - '###'
  - ELMo
- - '###'
  - 通用句子编码器
- - '###'
  - 来自 Transformers 的双向编码器表示
- - '####'
  - BERT 基础模型
- - '####'
  - BERT 大型模型
- - '##'
  - 结论
- - '#'
  - 4. BERT 算法详解
- - '##'
  - BERT 是如何工作的？
- - '###'
  - 文本处理
- - '###'
  - 掩码语言建模
- - '###'
  - 下一句预测
- - '##'
  - 使用 BERT 进行文本分类
- - '##'
  - 问题分类与 BERT 模型实现
- - '##'
  - BERT 模型的基准测试
- - '###'
  - GLUE 基准测试
- - '###'
  - SQuAD 数据集
- - '###'
  - IMDB 评论数据集
- - '###'
  - RACE 基准
- - '##'
  - 基于 BERT 的模型类型
- - '###'
  - ALBERT
- - '###'
  - RoBERTa
- - '###'
  - DistilBERT
- - '####'
  - 蒸馏损失
- - '####'
  - 余弦嵌入损失
- - '####'
  - 掩码语言建模损失
- - '####'
  - 架构修改
- - '###'
  - StructBERT
- - '####'
  - StructBERT 中的结构预训练
- - '####'
  - 预训练目标
- - '###'
  - 用于自然问题的 BERT[joint]
- - '##'
  - 结论
- - '#'
  - 5. BERT 模型应用：问答系统
- - '##'
  - 问答系统的类型
- - '##'
  - 使用 BERT 设计问答系统
- - '##'
  - 加载用于问答的预训练模型
- - '##'
  - 加载词汇表
- - '##'
  - 对输入文本执行分词
- - '##'
  - 查找 [SEP] 标记首次出现的位置
- - '##'
  - 在我们的示例上测试模型
- - '###'
  - 针对 Windows Server
- - '####'
  - 创建 REST API
- - '###'
  - 针对 Linux Server
- - '####'
  - 创建 REST API
- - '##'
  - 开放域问答系统
- - '##'
  - 模型架构
- - '##'
  - DeepPavlov 问答系统
- - '##'
  - 结论
- - '#'
  - 6. BERT 模型应用：其他任务
- - '##'
  - 情感分析
- - '##'
  - 命名实体识别
- - '##'
  - 文本分类
- - '###'
  - 文本摘要
- - '##'
  - 结论
- - '#'
  - 7. BERT 模型的未来
- - '##'
  - 未来能力
- - '###'
  - 抽象式摘要
- - '###'
  - 自然语言生成
- - '###'
  - 机器翻译
- - '##'
  - 结论
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U, V
- - '##'
  - W, X, Y, Z
