name: How to Compete in the Age of Artificial Intelligence
name_cn: 人工智能时代的竞争指南
slug: how-to-compete-in-the-age-of-artificial-intelligence
toc:
- - '#'
  - 引言
- - '#'
  - 排版后的内容
- - '#'
  - 最终思考
- - '#'
  - 致谢
- - '##'
  - 关于作者
- - '#'
  - 第1章 人工智能的经济学
- - '##'
  - 自然资源
- - '##'
  - 合作型企业
- - '##'
  - 人人享有能源
- - '##'
  - 金融机构不再是中介
- - '##'
  - 宜居城市
- - '##'
  - 解放学习
- - '##'
  - 真正关爱健康
- - '##'
  - 一切都是预测问题！
- - '##'
  - 自动驾驶与人工智能的演进
- - '##'
  - 人类判断力是无价的！
- - '#'
  - 第2章 什么定义了人工智能？
- - '##'
  - 人工智能作为普适智能
- - '###'
  - AI 即 AAAI——辅助智能、增强智能与自主智能
- - '####'
  - 辅助智能
- - '####'
  - 增强智能
- - '####'
  - 自主智能
- - '###'
  - 人工智能作为无形界面（无用户界面）
- - '###'
  - 人工智能的新进展是否名副其实？
- - '##'
  - 为什么采用人工智能如此困难？
- - '###'
  - AI 战略的前提：数据驱动战略
- - '###'
  - 避免偏见
- - '####'
  - 数据驱动的偏见
- - '####'
  - 通过交互产生的偏见
- - '####'
  - 涌现性偏见
- - '####'
  - 相似性偏见
- - '####'
  - 目标冲突偏见
- - '####'
  - 机器偏见即人类偏见
- - '##'
  - 你准备好迎接 AI 了吗？
- - '###'
  - 如何定义 AI 战略
- - '####'
  - 识别潜在的 AI 用例
- - '####'
  - 评估采用场景
- - '####'
  - 评估内部能力
- - '####'
  - 启动 AI 转型计划
- - '#####'
  - 建立赞助与治理机制
- - '#####'
  - 行动计划：实验、失败与学习
- - '#####'
  - 投资并发展 AI 能力
- - '###'
  - 如何定义 AI 用例
- - '##'
  - 虚拟个人助理
- - '##'
  - 电子游戏
- - '##'
  - 智能汽车
- - '##'
  - 消费者分析与预测
- - '##'
  - 金融
- - '##'
  - 聊天机器人
- - '##'
  - 社交网络
- - '##'
  - 房地产
- - '##'
  - 第9章 无人机
- - '##'
  - 第10章 文本分析与自然语言处理
- - '###'
  - 结论
- - '####'
  - 帕累托原则
- - '####'
  - 九十-九十法则
- - '####'
  - 侯世达定律
- - '#'
  - 第3章 在人工智能时代重新构想竞争优势
- - '##'
  - 感知与响应机器
- - '##'
  - 有限记忆机器
- - '##'
  - 心智理论
- - '##'
  - 自我意识机器
- - '##'
  - 董事会里的人工智能
- - '##'
  - 利用 AI 创造战略优势
- - '###'
  - 面向未来的目标
- - '###'
  - 人在回路中的方法
- - '###'
  - 精心设计的无界面
- - '###'
  - 成本、质量与时间有多重要？
- - '####'
  - 快得难以管理
- - '####'
  - 快得难以反应
- - '####'
  - 快得难以学习
- - '###'
  - AI 学习场景是否足够不可预测？
- - '###'
  - 管理不成熟的 AI
- - '##'
  - 新兴产业与人工智能经济
- - '##'
  - 制胜技能：面向不断演进的人工智能经济的情绪智力技能
- - '###'
  - 用例：人工智能与亚马逊飞轮
- - '####'
  - 对话式界面的影响
- - '####'
  - 让人工智能大众化
- - '###'
  - AI 工作方式
- - '###'
  - 一种新的商业模式
- - '##'
  - 让人工智能发挥作用
- - '###'
  - 市场营销与销售
- - '###'
  - 研究与开发
- - '###'
  - 运营
- - '###'
  - 采购与供应链管理
- - '###'
  - 共享服务职能
- - '#'
  - 结论
- - '##'
  - 建立与商业价值的清晰关联
- - '##'
  - 利用客户体验中的颠覆性潜力
- - '##'
  - 应对组织、治理和技术影响
- - '#'
  - 第4章 董事会致 CEO：“你的 AI 战略是什么？”
- - '##'
  - CEO：“董事会为何要问我这个问题？”
- - '###'
  - 应用“没有免费午餐”法则
- - '###'
  - 拥抱开放与透明
- - '###'
  - 评估互联世界中的机遇
- - '###'
  - 聚焦增强智能
- - '###'
  - 关注伦理与网络安全
- - '##'
  - CEO：“我该如何回应？”
- - '###'
  - AI 不是机器与人类的对立
- - '##'
  - 人工智能并非总关乎最优算法
- - '###'
  - 训练数据
- - '###'
  - 机器学习
- - '###'
  - 反馈循环
- - '##'
  - CEO：“我该如何让我的领导团队参与进来？”
- - '###'
  - 关注成果，而非技术
- - '###'
  - 解释人工智能
- - '###'
  - 评估人工智能平台
- - '###'
  - 单一领域与通用平台
- - '###'
  - 黑盒与白盒
- - '###'
  - 单点解决方案与集成平台
- - '##'
  - CEO 的新管理原则：AI 管理
- - '##'
  - 企业人工智能战略
- - '##'
  - CEO 使命：普及 AI
- - '##'
  - 结论
- - '#'
  - 第5章 黑箱之内：理解人工智能的决策过程
- - '##'
  - 弱人工智能（ANI）
- - '##'
  - 通用人工智能（AGI）
- - '##'
  - 超人工智能（ASI）
- - '##'
  - 学习者的分类
- - '###'
  - 监督学习
- - '###'
  - 无监督学习
- - '###'
  - 强化学习
- - '##'
  - AI 问题的分类
- - '##'
  - 面向管理者的机器学习入门
- - '###'
  - 朴素贝叶斯分类器
- - '###'
  - K-Means 聚类
- - '###'
  - KNN（K-最近邻）
- - '###'
  - 支持向量机
- - '###'
  - A Priori（先验算法）
- - '###'
  - 线性回归
- - '###'
  - 逻辑回归
- - '###'
  - 决策树
- - '###'
  - 随机森林
- - '###'
  - 降维算法
- - '###'
  - 梯度提升算法
- - '##'
  - 面向管理者的深度学习入门
- - '###'
  - 深度学习算法与架构
- - '####'
  - 前馈神经网络
- - '####'
  - 学习率衰减
- - '####'
  - 反向传播
- - '####'
  - Dropout
- - '####'
  - 批量归一化
- - '####'
  - 梯度消失
- - '####'
  - 自编码器
- - '####'
  - 玻尔兹曼机
- - '####'
  - 滤波器与最大池化
- - '####'
  - GAN（生成对抗网络）
- - '####'
  - 长短期记忆网络（LSTM）
- - '#####'
  - 遗忘门
- - '#####'
  - 输入门
- - '#####'
  - 输出门
- - '##'
  - 面向管理者的 NLP 入门
- - '###'
  - 自然语言理解
- - '###'
  - 自然语言生成
- - '###'
  - 文本预处理
- - '####'
  - 噪声去除
- - '####'
  - 词汇规范化
- - '####'
  - 对象标准化
- - '####'
  - 文本到特征（文本数据的特征工程）
- - '####'
  - 实体提取（实体作为特征）
- - '####'
  - 跳元模型
- - '####'
  - 连续词袋模型
- - '##'
  - 神经网络：黑箱之谜
- - '###'
  - 窥探黑箱内部
- - '####'
  - 揭开人工智能的黑箱
- - '####'
  - 训练机器学习与我们对错误的容忍度
- - '##'
  - 结论
- - '###'
  - 人类无法解释自己的行为
- - '###'
  - 算法是可预测的理性
- - '#'
  - 第6章 智能流程自动化 = RPA + AI
- - '##'
  - 机器人流程自动化（RPA）
- - '##'
  - 人工智能
- - '###'
  - 捕获和处理任何类型数据的能力
- - '###'
  - 将数据转化为洞察
- - '##'
  - 自动化与智能：协同工作
- - '###'
  - 对更快周转的需求
- - '###'
  - “直接迁移”的终结
- - '###'
  - 期望值已提高
- - '##'
  - 智能流程自动化之旅（IPA = RPA + AI）
- - '###'
  - 制定基于价值的战略
- - '###'
  - 确定机遇的优先级
- - '###'
  - 确定试点场景
- - '###'
  - 制定路线图
- - '###'
  - 整合流程与技术
- - '###'
  - 建立操作流程和治理模型
- - '###'
  - 建立变革管理计划
- - '##'
  - 你的 IPA 之旅：首个 100 天
- - '##'
  - 成功实现 IPA 之旅的 15 个关键要素
- - '##'
  - 结论
- - '#'
  - 第7章 网络安全与人工智能
- - '##'
  - 将机器学习应用于安全
- - '###'
  - 用于网络安全的监督式机器学习
- - '###'
  - 用于网络安全的无监督式机器学习
- - '##'
  - 首席信息安全官的人工智能与网络安全行动手册
- - '###'
  - 入侵发生前
- - '###'
  - 入侵发生时
- - '###'
  - 安全事件发生后
- - '##'
  - 给 CEO 的问题
- - '##'
  - 结论
- - '#'
  - 第8章 智联网 = 物联网 + 云计算 + 人工智能
- - '##'
  - 让住宅和建筑变得智能
- - '##'
  - 保持你的汽车良好运行
- - '##'
  - 确保持续供电
- - '##'
  - 确保你活着
- - '##'
  - 确保你的安全
- - '##'
  - 物联网、混合云与人工智能协同工作
- - '###'
  - 避免代价高昂的计划外停机
- - '###'
  - 提高运营效率
- - '###'
  - 实现新的和改进的产品与服务
- - '###'
  - 加强风险管理
- - '##'
  - 人工智能在工业 4.0 中的作用
- - '##'
  - 数字孪生
- - '###'
  - 数字孪生如何带来变革性的业务成果？
- - '###'
  - 如何为您的业务制定盈利的数字孪生战略？
- - '##'
  - 你的万物智联战略是什么？
- - '###'
  - 制定万物智联战略的最佳实践
- - '####'
  - 制定并阐明你自己的价值主张
- - '####'
  - 评估客户需求
- - '####'
  - 进行价值链分析和盈利能力分析
- - '####'
  - 合作共赢
- - '####'
  - 评估技术并进行适配差距分析
- - '####'
  - 构建你的智能物联路线图
- - '##'
  - 结论
- - '#'
  - 第9章 IT 运维与人工智能
- - '##'
  - 为什么你的企业需要 AIOps？
- - '###'
  - AIOps 平台的构成要素
- - '####'
  - 自动化
- - '####'
  - 预测
- - '##'
  - 你的 AIOps 策略是什么？
- - '###'
  - 建立工具和流程以实现系统拓扑的自组织
- - '###'
  - 建立实时数据探索与报告
- - '###'
  - 利用自然语言处理（NLP）消除人工分类
- - '###'
  - 在企业范围内实施机器学习
- - '###'
  - 打通数据孤岛与学科壁垒，解锁隐藏洞察
- - '##'
  - 结论
- - '#'
  - 第10章 去中心化自治组织 = 区块链 + AI + 物联网
- - '##'
  - 面向管理者的区块链入门指南
- - '###'
  - 区块链与物联网（IoT）
- - '###'
  - 区块链与人工智能
- - '####'
  - 人工智能需要加密
- - '####'
  - 区块链可助力人工智能实现可解释性
- - '####'
  - 人工智能可提升区块链效率
- - '####'
  - 人工智能可增强区块链可扩展性
- - '##'
  - 人工智能与区块链的集成价值主张
- - '###'
  - 改进的商业数据模型
- - '###'
  - 发现全新洞察
- - '###'
  - 智能预测
- - '###'
  - 数据知识产权
- - '###'
  - 自治组织
- - '####'
  - 更智能的金融
- - '####'
  - 智能零售
- - '####'
  - 省心省力的客户忠诚度计划
- - '####'
  - 创意护照
- - '####'
  - 透明治理
- - '####'
  - 全球化验证系统
- - '####'
  - 创新审计与合规系统
- - '####'
  - 数据与人工智能货币化
- - '##'
  - 去中心化人工智能的崛起
- - '###'
  - AI 与去中心化自治组织
- - '##'
  - 结论
- - '#'
  - 第11章 伦理与人工智能
- - '##'
  - 人工智能中的伦理问题
- - '###'
  - 失业
- - '###'
  - 不平等
- - '###'
  - 人性
- - '###'
  - 人工愚蠢
- - '###'
  - 安全
- - '##'
  - 奇点
- - '##'
  - 机器权利
- - '##'
  - 董事会与 CEO 在伦理人工智能中的角色
- - '###'
  - 董事会的角色
- - '###'
  - CEO 的角色：人工智能伦理的卓越治理
- - '###'
  - 技术专家的角色
- - '##'
  - 结论
- - '#'
  - 第12章 整合：迈向人机协作生态系统
- - '##'
  - 人机共生
- - '##'
  - 利克莱德的增强论
- - '##'
  - 琳达实验：快思考与慢思考
- - '##'
  - 人机融合策略（HMIS）
- - '###'
  - 应用场景
- - '####'
  - 机器代理作为人类助手
- - '####'
  - 完全自主的机器代理
- - '####'
  - 机器代理与人类交互
- - '####'
  - 全机器代理交互
- - '####'
  - 人类与机器代理交互
- - '##'
  - 治理框架
- - '###'
  - 机器的可信度与好感度
- - '###'
  - 人机关系
- - '####'
  - 所有人类皆不同
- - '##'
  - 结论
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V, W, X, Y, Z
