name: Hands-on Azure Cognitive Services
name_cn: Azure 认知服务实用指南
slug: hands-on-azure-cognitive-services
toc:
- - '##'
  - 引言
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '#'
  - 1. 认知服务的力量
- - '##'
  - Azure 认知服务概述
- - '###'
  - 为什么选择 Azure 认知服务
- - '###'
  - 探索认知服务 API：视觉、语音、语言、Web 搜索和决策
- - '####'
  - 视觉 API
- - '#####'
  - 计算机视觉
- - '#####'
  - 自定义视觉
- - '#####'
  - 人脸
- - '#####'
  - 表单识别器
- - '#####'
  - 视频索引器
- - '####'
  - 语音 API
- - '#####'
  - 语音服务
- - '#####'
  - 说话人识别（预览版）
- - '####'
  - 语言 API
- - '#####'
  - 沉浸式阅读器
- - '#####'
  - 语言理解 (LUIS)
- - '#####'
  - QnA Maker
- - '#####'
  - 文本分析
- - '#####'
  - 翻译器
- - '####'
  - 网页搜索 API
- - '#####'
  - Bing 搜索 API
- - '#####'
  - Bing 网页搜索
- - '#####'
  - Bing 自定义搜索
- - '#####'
  - Bing 图像搜索
- - '#####'
  - Bing 实体搜索
- - '#####'
  - Bing 新闻搜索
- - '######'
  - Bing 视频搜索
- - '######'
  - Bing 视觉搜索
- - '######'
  - Bing 自动建议
- - '######'
  - Bing 拼写检查
- - '######'
  - Bing 本地企业搜索
- - '####'
  - 决策 API
- - '#####'
  - 异常检测器（预览版）
- - '#####'
  - 内容审查器
- - '#####'
  - 个性化器
- - '###'
  - 机器学习概述
- - '####'
  - 理解应用场景
- - '###'
  - COVID-19 智能应用场景
- - '###'
  - 总结
- - '#'
  - 2. 认知服务的 Azure 门户
- - '##'
  - Azure 门户与 Azure 认知服务入门
- - '###'
  - Azure 认知服务入门
- - '###'
  - Azure 市场：AI + 机器学习概述
- - '###'
  - 了解软件开发工具包 (SDK)：开始使用你喜爱的编程语言
- - '###'
  - 设置 Visual Studio 模板
- - '##'
  - 总结
- - '#'
  - 3. 视觉 – 识别和分析图像与视频
- - '##'
  - 理解计算机视觉中的视觉 API
- - '###'
  - Microsoft Azure 认知服务
- - '###'
  - 分析图像
- - '####'
  - 开始探索计算机视觉
- - '####'
  - 使用 API
- - '####'
  - 识别人脸
- - '####'
  - 使用 API 控制台进行测试
- - '####'
  - 使用演示页面进行测试
- - '####'
  - 使用代码实现
- - '##'
  - 理解用于视频分析的视觉 API 工作行为
- - '###'
  - Microsoft Azure 视频索引器
- - '##'
  - 总结
- - '#'
  - 4. 语言 – 理解非结构化文本和模型
- - '##'
  - 创建与理解语言模型
- - '###'
  - 进行中的丰富——JFK 文件演示
- - '##'
  - Transformer 模型——用于自然语言处理的 Transformer
- - '###'
  - 使用微调 BERT 进行命名实体识别
- - '##'
  - 语言 API 总结
- - '#'
  - 5. 语音 – 与你的应用程序对话
- - '##'
  - 理解语音和语音服务
- - '###'
  - 全面的隐私与安全^(¹²)
- - '###'
  - 入门指南
- - '###'
  - 将语音实时翻译到你的应用程序中
- - '###'
  - 语音转文本 – 将口语音频转换为文本以实现交互
- - '###'
  - 使用 LUIS 和 Speech Studio 进行认知语音搜索
- - '####'
  - 图 5-31
- - '####'
  - 图 5-32
- - '####'
  - 图 5-33
- - '####'
  - 图 5-34
- - '####'
  - 图 5-35
- - '####'
  - 图 5-36
- - '####'
  - 图 5-37
- - '####'
  - 图 5-38
- - '####'
  - 图 5-39
- - '####'
  - 图 5-40
- - '####'
  - 图 5-41
- - '##'
  - Speech API 总结
- - '#'
  - 6. 决策 – 在应用程序中做出更明智的决策
- - '##'
  - 决策服务与 API
- - '###'
  - 内容审查器服务
- - '####'
  - 动手实践 – 构建内容审核系统
- - '####'
  - 使用内容审查服务进行文本审核
- - '#####'
  - 内容审核 – 调用 API
- - '#####'
  - 图 6-23
- - '###'
  - 个性化服务
- - '####'
  - 动手尝试 – 构建电影个性化服务
- - '###'
  - 异常检测器服务
- - '####'
  - 工作原理
- - '####'
  - 动手实践 – 异常检测器演示
- - '###'
  - 指标顾问（预览版）
- - '##'
  - 总结与结论
- - '#'
  - 7. 搜索 – 为你的应用程序添加搜索功能
- - '##'
  - 搜索生态系统
- - '##'
  - Azure 认知搜索
- - '###'
  - 使用 Azure 认知搜索进行搜索
- - '###'
  - 测试 Azure 认知搜索
- - '###'
  - 在 Notebook 中集成 Azure 认知搜索
- - '##'
  - 使用必应网页搜索
- - '###'
  - 图 7-2
- - '###'
  - 使用 Python 的必应图片搜索结果
- - '##'
  - 总结与结论
- - '#'
  - 8. 使用容器部署和托管服务
- - '##'
  - 认知服务容器
- - '###'
  - 托管认知服务容器
- - '####'
  - 运行语言服务容器
- - '####'
  - 运行异常检测器服务容器
- - '##'
  - 使用 Azure 容器实例
- - '##'
  - 使用 Azure Kubernetes 服务部署认知服务容器
- - '##'
  - 总结与结论
- - '#'
  - 9. Azure Bot 服务
- - '##'
  - Azure Bot 服务生态系统
- - '##'
  - 构建 Azure Service COVID-19 机器人^(³³)
- - '##'
  - 从 Web 扩充机器人知识库
- - '##'
  - 结论与总结
- - '#'
  - 10. Azure 机器学习
- - '##'
  - Azure 机器学习堆栈
- - '##'
  - 使用 Azure 机器学习实现 Hello World
- - '##'
  - Azure 机器学习工作室
- - '##'
  - 创建用于分类的机器学习模型
- - '##'
  - 使用 Azure 机器学习设计器构建分类模型
- - '##'
  - 结论与总结
