name: AI Solutions for the United Nations Sustainable Development Goals
name_cn: 联合国可持续发展目标的AI解决方案
slug: ai-solutions-for-the-united-nations-sustainable-development-
toc:
- - '#'
  - 关于贡献者
- - '#'
  - 第 2 章
- - '#'
  - 第 3 章
- - '#'
  - 第 4 章
- - '#'
  - 第 5 章
- - '#'
  - 第 6 章
- - '#'
  - 关于作者
- - '#'
  - 1. 机器学习应用开发与联合国可持续发展目标导论
- - '##'
  - 1.1 联合国可持续发展目标与机器学习
- - '##'
  - 1.2 人工智能与机器学习概念
- - '###'
  - 1.2.1 人工智能
- - '###'
  - 1.2.2 机器学习
- - '##'
  - 机器学习范式
- - '###'
  - 浅层学习
- - '###'
  - 深度学习
- - '###'
  - 强化学习
- - '###'
  - 集成学习
- - '###'
  - 1.2.3 数据类型
- - '###'
  - 1.2.4 数据预处理步骤
- - '##'
  - 数据集成
- - '###'
  - 数据与降维
- - '####'
  - JavaScript 数据预处理程序
- - '##'
  - 在 JavaScript 中实现基于机器学习的预测与分类算法
- - '###'
  - 1.3.1 简单线性回归 (SLR)
- - '###'
  - 1.3.2 多项式回归 (PLR)
- - '###'
  - 1.3.3 多元线性回归 (MLR)
- - '###'
  - 1.3.4 K-近邻算法
- - '###'
  - 1.4 本章小结
- - '#'
  - 2. 利用机器学习算法进行风电场发电量预测与分类
- - '##'
  - 2.1 引言
- - '##'
  - 2.2 可持续发展目标 7 的人工智能应用案例
- - '##'
  - 2.3 数据处理与应用设计
- - '###'
  - 2.3.1 数据收集过程与数据集描述
- - '###'
  - 2.3.2 数据预处理步骤
- - '###'
  - 2.3.3 风力涡轮机建模
- - '###'
  - 2.3.4 程序结构
- - '####'
  - KNN
- - '####'
  - 多项式回归
- - '####'
  - 多元线性回归
- - '##'
  - 2.4 应用测试与分析
- - '###'
  - 2.4.1 应用测试
- - '###'
  - 2.4.2 多项式回归结果
- - '###'
  - 2.4.3 KNN 回归
- - '###'
  - 2.4.4 多元线性回归
- - '###'
  - 2.4.5 KNN 分类
- - '###'
  - 2.4.6 回归模型对比分析：多项式回归 vs. KNN 回归 vs. 多元线性回归
- - '##'
  - 2.5 分类在风电预测中的优势
- - '###'
  - 2.5.1 准确的能源发电预测
- - '###'
  - 2.5.2 优化的能源分配
- - '###'
  - 2.5.3 降低成本
- - '###'
  - 2.5.4 电网稳定性
- - '###'
  - 2.5.5 增强的能源规划
- - '##'
  - 2.6 总结
- - '#'
  - 3. 一种利用机器学习算法实现可持续发展目标 2、9 和 12 的作物推荐系统
- - '##'
  - 3.1 引言
- - '###'
  - 3.2 人工智能在可持续发展目标 2、9 和 12 中的应用案例
- - '##'
  - 3.3 数据处理与应用设计
- - '###'
  - 3.3.1 数据收集过程与数据集描述
- - '###'
  - 3.3.2 数据预处理步骤
- - '###'
  - 3.3.3 程序结构
- - '###'
  - 3.3.4 Web 应用程序布局
- - '##'
  - 3.4 应用程序测试与分析
- - '###'
  - 3.4.1 应用程序测试
- - '###'
  - 3.4.2 K-NN 分类结果
- - '###'
  - 3.4.3 决策树分类结果
- - '###'
  - 3.4.4 随机森林
- - '###'
  - 3.4.5 多层感知器
- - '###'
  - 3.4.6 讨论
- - '##'
  - 3.5 总结
- - '#'
  - 4. 利用机器学习算法实现制造业排放与可持续发展目标 9 和 13 的协同
- - '##'
  - 4.1 引言
- - '###'
  - 4.2 可持续发展目标 9 和 13 的应用案例
- - '##'
  - 4.3 数据处理与应用设计
- - '###'
  - 4.3.1 数据收集流程与数据集描述
- - '###'
  - 4.3.2 数据预处理步骤
- - '####'
  - 数据预处理阶段
- - '####'
  - 特征选择与属性移除
- - '##'
  - 4.4 分析程序结构
- - '###'
  - 4.4.1 简单线性回归 (SLR)
- - '###'
  - 4.4.2 多元线性回归 (MLR)
- - '###'
  - 4.4.3 k-最近邻 (k-NN)
- - '##'
  - 4.5 应用测试与分析
- - '###'
  - 4.5.1 简单线性回归 (SLR)
- - '###'
  - 4.5.2 多元线性回归 (MLR)
- - '###'
  - 4.5.3 k-最近邻算法 (k-NN)
- - '###'
  - 4.5.4 讨论
- - '###'
  - 4.6 建议
- - '###'
  - 4.7 改进
- - '###'
  - 4.8 总结
- - '###'
  - 4.9 附录
- - '####'
  - 4.9.1 数据集
- - '#'
  - 5. 基于机器学习的水质可饮用性分析
- - '##'
  - 5.1 引言
- - '##'
  - 5.2 人工智能在可持续发展目标 3、6 和 12 中的应用案例
- - '##'
  - 5.3 数据处理与应用设计
- - '###'
  - 5.3.1 数据收集过程与数据集描述
- - '###'
  - 5.3.2 数据预处理步骤
- - '###'
  - 5.3.3 Web 应用程序的总体布局
- - '###'
  - 5.3.4 水可饮用性系统
- - '###'
  - 5.3.5 机器学习算法
- - '####'
  - k-NN
- - '####'
  - 决策树与随机森林
- - '####'
  - 朴素贝叶斯
- - '##'
  - 5.4 应用程序测试与分析
- - '###'
  - 5.4.1 应用测试
- - '###'
  - 5.4.2 k-NN
- - '###'
  - 5.4.3 决策树
- - '###'
  - 5.4.4 随机森林
- - '###'
  - 5.4.5 朴素贝叶斯
- - '###'
  - 5.5 总结
- - '#'
  - 6. 空气质量监测：机器学习在实现可持续发展目标 3 和 13 中的应用案例研究
- - '##'
  - 6.1 引言
- - '##'
  - 6.2 人工智能在可持续发展目标 3 和 13 中的应用案例
- - '###'
  - 6.2.1 可持续发展目标 3：良好健康与福祉
- - '###'
  - 6.2.2 可持续发展目标 13：气候行动
- - '##'
  - 6.3 数据处理与应用设计
- - '###'
  - 6.3.1 数据收集过程与数据集描述
- - '###'
  - 6.3.2 程序结构
- - '###'
  - 6.3.3 网站布局
- - '###'
  - 6.3.4 线性回归的实现
- - '###'
  - 6.3.5 多项式回归的实现
- - '###'
  - 6.3.6 LSTM/MLP 的实现
- - '###'
  - 6.3.7 显示回归图
- - '###'
  - 6.3.8 AQI 分类
- - '##'
  - 6.4 应用测试与分析
- - '###'
  - 6.4.1 Web 应用测试
- - '###'
  - 6.4.2 回归算法的性能
- - '###'
  - 6.4.3 SLR 算法的性能
- - '###'
  - 6.4.4 PR 算法的性能
- - '###'
  - 6.4.5 MLP 算法的性能
- - '###'
  - 6.4.6 LSTM 算法的性能
- - '###'
  - 6.4.7 分类算法的性能
- - '##'
  - 6.5 总结
- - '#'
  - 7. 针对可持续发展目标 7、9 和 11 的全球互联网连接发展聚类分析
- - '##'
  - 7.1 引言
- - '##'
  - 7.2 人工智能在可持续发展目标 7、9 和 11 中的应用案例
- - '##'
  - 7.3 数据处理与应用设计
- - '###'
  - 7.3.1 数据集的收集与描述
- - '###'
  - 7.3.2 数据预处理
- - '###'
  - 7.3.3 散点图
- - '###'
  - 7.3.4 应用系统模型
- - '####'
  - 组件与功能
- - '####'
  - 全球互联网连接发展聚类
- - '###'
  - 7.3.5 应用程序布局
- - '###'
  - 7.3.6 程序结构
- - '####'
  - 方法与类的描述
- - '####'
  - K-means 聚类算法
- - '##'
  - 7.4 应用程序测试与分析
- - '###'
  - 7.4.1 应用程序测试
- - '###'
  - 7.4.2 讨论
- - '####'
  - 与历史趋势的比较
- - '####'
  - 地理差异
- - '##'
  - 7.5 全球互联网连通性分析的优势
- - '##'
  - 7.6 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X, Y
- - '##'
  - Z
