name: Artificial Neural Networks with Java
name_cn: Java 人工神经网络
slug: artificial-neural-networks-with-java
toc:
- - '#'
  - 引言
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 关于技术审阅者
- - '#'
  - 第一部分：神经网络入门
- - '##'
  - 第1章 了解神经网络
- - '###'
  - 生物神经元与人工神经元
- - '###'
  - 激活函数
- - '###'
  - 本章小结
- - '##'
  - 第2章 神经网络处理的内部机制
- - '###'
  - 待逼近的函数
- - '###'
  - 网络架构
- - '###'
  - 前向传播计算
- - '####'
  - 输入记录 1
- - '####'
  - 输入记录 2
- - '####'
  - 输入记录 3
- - '####'
  - 输入记录 4
- - '###'
  - 反向传播
- - '###'
  - 函数导数与函数散度
- - '####'
  - 最常用的函数导数
- - '###'
  - 总结
- - '##'
  - 第3章 手动神经网络处理
- - '###'
  - 示例：单点处函数的手动近似
- - '###'
  - 构建神经网络
- - '###'
  - 前向传播计算
- - '####'
  - 隐藏层
- - '####'
  - 输出层
- - '###'
  - 反向传播计算
- - '####'
  - 计算输出层神经元的权重调整量
- - '#####'
  - 计算 `W²[11]` 的调整量
- - '#####'
  - 计算 `W²[12]` 的调整量
- - '#####'
  - 计算 `W²[13]` 的调整量
- - '####'
  - 计算隐藏层神经元的权重调整量
- - '#####'
  - 计算 `W¹[11]` 的调整量
- - '#####'
  - 计算 `W¹[12]` 的调整量
- - '#####'
  - 计算 `W¹[21]` 的调整量
- - '#####'
  - 计算 `W¹[22]` 的调整量
- - '#####'
  - 计算 `W¹[31]` 的调整量
- - '#####'
  - 计算 `W¹[32]` 的调整量
- - '###'
  - 更新网络偏置
- - '###'
  - 回到前向传播
- - '####'
  - 隐藏层
- - '####'
  - 输出层
- - '###'
  - 网络计算的矩阵形式
- - '###'
  - 深入探讨
- - '###'
  - 小批量与随机梯度
- - '###'
  - 总结
- - '#'
  - 第二部分：神经网络 Java 开发环境
- - '##'
  - 第4章 配置你的开发环境
- - '###'
  - 在 Windows 机器上安装 Java 环境与 NetBeans
- - '####'
  - 安装 Encog Java 框架
- - '####'
  - 安装 XChart 包
- - '###'
  - 总结
- - '##'
  - 第5章 使用 Java Encog 框架进行神经网络开发
- - '###'
  - 示例：使用 Java 环境进行函数逼近
- - '###'
  - 网络架构
- - '###'
  - 归一化输入数据集
- - '###'
  - 构建归一化两个数据集的 Java 程序
- - '###'
  - 构建神经网络处理程序
- - '####'
  - 程序代码
- - '####'
  - 调试与执行程序
- - '####'
  - 训练方法的处理结果
- - '###'
  - 测试网络
- - '####'
  - 测试结果
- - '###'
  - 深入探讨
- - '###'
  - 总结
- - '##'
  - 第6章 训练范围外的神经网络预测
- - '###'
  - 示例：在训练范围外逼近周期函数
- - '####'
  - 示例的网络架构
- - '####'
  - 示例的程序代码
- - '####'
  - 测试网络
- - '###'
  - 示例：在训练范围外正确逼近周期函数的正确方法
- - '####'
  - 准备训练数据
- - '####'
  - 示例的网络架构
- - '####'
  - 示例的程序代码
- - '####'
  - 排版后的内容
- - '####'
  - 示例的训练结果
- - '####'
  - 示例 3 的测试结果日志
- - '###'
  - 总结
- - '##'
  - 第7章 处理复杂周期函数
- - '###'
  - 示例：复杂周期函数的逼近
- - '####'
  - 数据准备
- - '####'
  - 在数据中反映函数拓扑结构
- - '####'
  - 网络架构
- - '####'
  - 程序代码
- - '####'
  - 训练网络
- - '####'
  - 测试网络
- - '###'
  - 深入探讨
- - '###'
  - 总结
- - '##'
  - 第8章 近似非连续函数
- - '###'
  - 示例：逼近非连续函数
- - '####'
  - 网络架构
- - '####'
  - 程序代码
- - '####'
  - 训练过程的代码片段
- - '####'
  - 不理想的训练结果
- - '###'
  - 使用微批次方法近似非连续函数
- - '####'
  - 微批次处理的程序代码
- - '####'
  - '`getChart()` 方法的程序代码'
- - '####'
  - 训练方法的代码片段 1
- - '####'
  - 训练方法的代码片段 2
- - '####'
  - 微批量方法的训练结果
- - '####'
  - 测试处理逻辑
- - '####'
  - 微批次方法的结果测试
- - '###'
  - 深入探讨
- - '###'
  - 总结
- - '##'
  - 第9章 具有复杂拓扑结构的连续函数的逼近
- - '###'
  - 示例：使用传统神经网络过程逼近具有复杂拓扑结构的连续函数
- - '####'
  - 示例的网络架构
- - '####'
  - 示例的程序代码
- - '####'
  - 示例的训练处理结果
- - '###'
  - 使用微批处理方法逼近具有复杂拓扑的连续函数
- - '####'
  - 使用微批次方法的示例程序代码
- - '###'
  - 示例：螺旋类函数的逼近
- - '####'
  - 示例的网络架构
- - '####'
  - 示例的程序代码
- - '###'
  - 使用微批次方法对相同函数进行近似
- - '###'
  - 总结
- - '##'
  - 第10章 使用神经网络进行对象分类
- - '###'
  - 示例：记录分类
- - '####'
  - 训练数据集
- - '####'
  - 网络架构
- - '####'
  - 测试数据集
- - '####'
  - 数据归一化的程序代码
- - '####'
  - 分类的程序代码
- - '####'
  - 训练结果
- - '####'
  - 测试结果
- - '###'
  - 本章小结
- - '##'
  - 第11章 选择正确模型的重要性
- - '###'
  - 示例：预测下个月的股市价格
- - '###'
  - 将函数拓扑结构纳入数据集
- - '###'
  - 构建微批次文件
- - '###'
  - 网络架构
- - '###'
  - 程序代码
- - '###'
  - 训练过程
- - '###'
  - 训练结果
- - '###'
  - 测试数据集
- - '###'
  - 测试逻辑
- - '###'
  - 测试结果
- - '###'
  - 分析测试结果
- - '###'
  - 总结
- - '##'
  - 第12章 三维空间中的逼近函数
- - '###'
  - 示例：三维空间中的逼近函数
- - '####'
  - 数据准备
- - '####'
  - 网络架构
- - '####'
  - 程序代码
- - '####'
  - 处理结果
- - '###'
  - 总结
- - '#'
  - 第三部分：计算机视觉简介
- - '##'
  - 第13章 图像识别
- - '###'
  - 手写数字分类
- - '####'
  - 准备输入数据
- - '####'
  - 输入数据转换
- - '####'
  - 构建转换程序
- - '####'
  - 程序说明
- - '###'
  - 本章小结
- - '##'
  - 第14章 手写数字分类
- - '###'
  - 网络架构
- - '###'
  - 程序代码
- - '###'
  - 编程逻辑
- - '###'
  - 执行
- - '###'
  - 卷积神经网络
- - '###'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F, G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K, L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q, R
- - '##'
  - S
- - '##'
  - T, U, V, W, X, Y, Z
