name: Introduction to Python and Large Language Models
name_cn: Python 与大型语言模型入门指南
slug: introduction-to-python-and-large-language-models
toc:
- - '#'
  - 1. 大型语言模型的演进与意义
- - '##'
  - 1.1 大型语言模型的演进步骤
- - '###'
  - 1.1.1 马尔可夫、香农与语言模型
- - '###'
  - 1.1.2 乔姆斯基与语言模型
- - '###'
  - 1.1.3 基于规则的语言模型
- - '###'
  - 1.1.4 首个聊天机器人：`ELIZA`
- - '###'
  - 1.1.5 统计语言处理
- - '####'
  - 1.1.5.1 N-gram
- - '####'
  - 1.1.5.2 词袋模型（BOW）
- - '####'
  - 1.1.5.3 TF-IDF（词频-逆文档频率）
- - '####'
  - 1.1.5.4 向量空间模型与状态空间模型
- - '####'
  - 1.1.5.5 神经语言模型——大语言模型的崛起
- - '#####'
  - 1.1.5.5.1 循环神经网络
- - '#####'
  - 1.1.5.5.2 长短期记忆网络
- - '#####'
  - 1.1.5.5.3 门控循环单元
- - '#####'
  - 1.1.5.5.4 序列到序列语言模型
- - '###'
  - 1.1.6 基于注意力的语言模型
- - '####'
  - 1.1.6.1 注意力机制
- - '####'
  - 1.1.6.2 Transformer 架构
- - '####'
  - 1.1.6.3 大语言模型（LLM）
- - '####'
  - 1.1.6.4 多模态学习时代
- - '#####'
  - 1.1.6.4.1 多模态学习挑战
- - '#####'
  - 1.1.6.4.2 融合
- - '#####'
  - 1.1.6.4.3 对齐
- - '#####'
  - 1.1.6.4.4 翻译
- - '#####'
  - 1.1.6.4.5 协同学习
- - '#####'
  - 1.1.6.4.6 多模态学习如何运作
- - '#####'
  - 1.1.6.4.7 多模态深度学习的应用
- - '######'
  - 1.1.6.4.7.1 图像描述
- - '######'
  - 1.1.6.4.7.2 图像检索
- - '######'
  - 1.1.6.4.7.3 文本到图像生成
- - '######'
  - 1.1.6.4.7.4 情感识别
- - '##'
  - 1.2 理解自然语言处理基础
- - '###'
  - 1.2.1 自然语言处理究竟是什么？
- - '###'
  - 1.2.2 NLP 如何运作？
- - '###'
  - 1.2.3 NLP 的构成要素
- - '####'
  - 1.2.3.1 句法
- - '####'
  - 1.2.3.2 语义
- - '####'
  - 1.2.3.3 语用
- - '####'
  - 1.2.3.4 话语
- - '####'
  - 1.2.3.5 NLP 任务
- - '####'
  - 1.2.3.6 文本预处理与特征工程
- - '#####'
  - 1.2.3.6.1 分词
- - '#####'
  - 1.2.3.6.2 句法分析
- - '#####'
  - 1.2.3.6.3 词形还原
- - '#####'
  - 1.2.3.6.4 词语分割
- - '#####'
  - 1.2.3.6.5 词义消歧
- - '#####'
  - 1.2.3.6.6 句子边界检测
- - '#####'
  - 1.2.3.6.7 词素分割
- - '#####'
  - 1.2.3.6.8 词干提取
- - '#####'
  - 1.2.3.6.9 命名实体识别（NER）
- - '######'
  - 1.2.3.6.9.1 实体如何被识别
- - '###'
  - 1.2.4 NLP 与特征工程
- - '###'
  - 1.2.5 Python 与自然语言工具包（NLTK）
- - '####'
  - 1.2.5.1 标记化
- - '####'
  - 1.2.5.2 停用词移除
- - '####'
  - 1.2.5.3 词干提取
- - '####'
  - 1.2.5.4 词形还原
- - '####'
  - 1.2.5.5 用于 NLP 特征工程的 N-gram
- - '####'
  - 1.2.5.6 词性标注
- - '####'
  - 1.2.5.7 命名实体识别
- - '####'
  - 1.2.5.8 TF-IDF
- - '###'
  - 1.2.6 词嵌入与语义理解
- - '####'
  - 1.2.6.1 词嵌入
- - '#####'
  - 1.2.6.1.1 优势
- - '#####'
  - 1.2.6.1.2 局限性
- - '#####'
  - 1.2.6.1.3 示例
- - '####'
  - 1.2.6.2 语义理解
- - '####'
  - 1.2.6.3 语义分析在 NLP 中的重要性
- - '####'
  - 1.2.6.4 语义系统中的语义分析
- - '###'
  - 1.2.7 使用 Python 进行情感分析与文本分类
- - '####'
  - 1.2.7.1 情感分析
- - '####'
  - 1.2.7.2 文本分类
- - '####'
  - 1.2.7.3 文本分类的优势
- - '####'
  - 1.2.7.4 文本分类的变体
- - '####'
  - 1.2.7.5 文本分类的机制
- - '####'
  - 1.2.7.6 文本分类面临的挑战
- - '####'
  - 1.2.7.7 文本分类的应用
- - '###'
  - 1.2.8 探索自然语言处理（NLP）中的方法
- - '####'
  - 1.2.8.1 监督式 NLP
- - '####'
  - 1.2.8.2 无监督式 NLP
- - '####'
  - 1.2.8.3 自然语言理解
- - '###'
  - 1.2.9 自然语言生成
- - '###'
  - 1.2.10 统计自然语言处理、机器学习与深度学习
- - '###'
  - 1.2.11 NLP 面临的挑战
- - '###'
  - 1.2.12 区分 NLP 基础与 LLM 能力
- - '###'
  - 1.2.13 传统 NLP 技术与 LLM 的对比
- - '###'
  - 1.2.14 总结
- - '#'
  - 2. 什么是大型语言模型？
- - '##'
  - 2.1 语言模型的发展阶段
- - '##'
  - 2.2 大型语言模型是如何工作的？
- - '##'
  - 2.3 大型语言模型的总体架构
- - '###'
  - 2.3.1 大型语言模型的深度架构
- - '####'
  - 2.3.1.1 分词
- - '####'
  - 2.3.1.2 注意力
- - '#####'
  - 2.3.1.2.1 LLM 中的注意力机制
- - '#####'
  - 2.3.1.2.2 位置编码
- - '#####'
  - 2.3.1.2.3 激活函数
- - '######'
  - 2.3.1.2.3.1 ReLU
- - '######'
  - 2.3.1.2.3.2 GELU
- - '######'
  - 2.3.1.2.3.3 GLU 变体
- - '#####'
  - 2.3.1.2.4 层归一化
- - '######'
  - 2.3.1.2.4.1 LayerNorm
- - '######'
  - 2.3.1.2.4.2 RMSNorm
- - '######'
  - 2.3.1.2.4.3 Pre-norm 和 Post-norm
- - '######'
  - 2.3.1.2.4.4 DeepNorm
- - '#####'
  - 2.3.1.2.5 大型语言模型的分布式训练
- - '#####'
  - 2.3.1.2.6 数据预处理
- - '####'
  - 2.3.1.3 架构
- - '#####'
  - 2.3.1.3.1 编码器-解码器
- - '#####'
  - 2.3.1.3.2 因果解码器
- - '#####'
  - 2.3.1.3.3 前缀解码器
- - '#####'
  - 2.3.1.3.4 预训练目标
- - '####'
  - 2.3.1.4 模型适配
- - '#####'
  - 2.3.1.4.1 预训练
- - '#####'
  - 2.3.1.4.2 微调
- - '#####'
  - 2.3.1.4.3 对齐验证与利用
- - '#####'
  - 2.3.1.4.4 提示/利用
- - '##'
  - 2.4 LLM 的训练
- - '##'
  - 2.5 LLM 在各领域的优势与挑战
- - '###'
  - 2.5.1 通用用途
- - '###'
  - 2.5.2 医疗应用
- - '###'
  - 2.5.3 医疗沟通与管理
- - '###'
  - 2.5.4 增强的自然语言处理
- - '###'
  - 2.5.5 教育
- - '###'
  - 2.5.6 内容创作与增强
- - '###'
  - 2.5.7 语言翻译与本地化
- - '###'
  - 2.5.8 研究与数据分析
- - '###'
  - 2.5.9 金融
- - '###'
  - 2.5.10 创意艺术
- - '###'
  - 2.5.11 道德与负责任使用
- - '###'
  - 2.5.12 法律与合规辅助
- - '###'
  - 2.5.13 金融分析与预测
- - '###'
  - 2.5.14 灾难响应与管理
- - '###'
  - 2.5.15 个性化营销与客户洞察
- - '###'
  - 2.5.16 游戏与互动娱乐
- - '###'
  - 2.5.17 无障碍增强
- - '###'
  - 2.5.18 环境监测与可持续性
- - '###'
  - 2.5.19 大语言模型与工程应用
- - '###'
  - 2.5.20 聊天机器人
- - '###'
  - 2.5.21 大语言模型智能体
- - '##'
  - 2.6 大语言模型的局限性
- - '###'
  - 2.6.1 偏见
- - '###'
  - 2.6.2 幻觉
- - '####'
  - 2.6.2.1 易受各类网络攻击
- - '##'
  - 2.7 超越大型语言模型的热潮——它们为何如此受欢迎？
- - '###'
  - 2.7.1 共同优势——LLM 如此受欢迎的真正原因
- - '###'
  - 2.7.2 面向企业的大型语言模型
- - '####'
  - 2.7.2.1 数字内容创作
- - '###'
  - 2.7.3 提升搜索引擎优化（SEO）
- - '###'
  - 2.7.4 内容审核
- - '###'
  - 2.7.5 情感/情绪分析
- - '###'
  - 2.7.6 客户服务
- - '###'
  - 2.7.7 语言翻译
- - '###'
  - 2.7.8 虚拟团队协作
- - '###'
  - 2.7.9 招聘与人力资源支持
- - '###'
  - 2.7.10 销售提升
- - '###'
  - 2.7.11 欺诈识别
- - '##'
  - 2.8 摘要
- - '#'
  - 3. Python 与 LLMs
- - '##'
  - 3.1 Python 概览
- - '###'
  - 3.1.1 Python 语法与语义
- - '###'
  - 3.1.2 语法设计原则
- - '###'
  - 3.1.3 Python 之禅
- - '###'
  - 3.1.4 Python 标识符
- - '###'
  - 3.1.5 Python 缩进
- - '###'
  - 3.1.6 Python 多行语句
- - '###'
  - 3.1.7 Python 中的引号
- - '###'
  - 3.1.8 Python 注释
- - '###'
  - 3.1.9 在 Python 代码中使用空行
- - '###'
  - 3.1.10 在一行中组合多个语句
- - '###'
  - 3.1.11 如何安装 Python 及编写你的第一个 Python 程序
- - '####'
  - 3.1.11.1 在 Windows 上安装 Python
- - '####'
  - 3.1.11.2 在 macOS 上安装 Python
- - '####'
  - 3.1.11.3 在 Linux 上安装 Python – Ubuntu/Debian 和 Fedora
- - '####'
  - 3.1.11.4 你的第一个 Python 程序
- - '##'
  - 3.2 变量与数据类型、数字、字符串和类型转换
- - '###'
  - 3.2.1 命名变量
- - '###'
  - 3.2.2 数据类型
- - '###'
  - 3.2.3 Python 中的数字
- - '####'
  - 3.2.3.1 整数
- - '####'
  - 3.2.3.2 浮点数
- - '####'
  - 3.2.3.3 复数
- - '###'
  - 3.2.4 字符串
- - '####'
  - 3.2.4.1 字符串定界符与特性
- - '####'
  - 3.2.4.2 处理字符串中的特殊字符
- - '#####'
  - 3.2.4.2.1 原始字符串
- - '####'
  - 3.2.4.3 Python 中的三引号字符串
- - '###'
  - 3.2.5 布尔值与运算符
- - '####'
  - 3.2.5.1 布尔值
- - '####'
  - 3.2.5.2 将整数和浮点数转换为布尔值
- - '####'
  - 3.2.5.3 布尔运算符
- - '####'
  - 3.2.5.4 Python 运算符
- - '#####'
  - 3.2.5.4.1 算术运算符
- - '#####'
  - 3.2.5.4.2 比较运算符
- - '#####'
  - 3.2.5.4.3 逻辑运算符
- - '#####'
  - 3.2.5.4.4 位运算符
- - '#####'
  - 3.2.5.4.5 赋值运算符
- - '#####'
  - 3.2.5.4.6 身份运算符
- - '#####'
  - 3.2.5.4.7 成员运算符
- - '#####'
  - 3.2.5.4.8 三元运算符
- - '##'
  - 3.3 条件语句与循环
- - '###'
  - 3.3.1 条件语句
- - '####'
  - 3.3.1.1 语句分组
- - '####'
  - 3.3.1.2 嵌套代码块
- - '####'
  - 3.3.1.3 Else 和 Elif 子句
- - '####'
  - 3.3.1.4 单行 if 语句
- - '###'
  - 3.3.2 Python 循环（For 和 While）
- - '####'
  - 3.3.2.1 Python 中的 while 循环
- - '####'
  - 3.3.2.2 while 循环中的 else 语句
- - '####'
  - 3.3.2.3 使用 Python while 循环创建无限循环
- - '####'
  - 3.3.2.4 Python 中的 for 循环
- - '####'
  - 3.3.2.5 for 循环中的 else 语句
- - '####'
  - 3.3.2.6 Python 中的嵌套循环
- - '####'
  - 3.3.2.7 循环控制语句
- - '##'
  - 3.4 Python 数据结构：列表、集合、元组、字典
- - '###'
  - 3.4.1 什么是数据结构？
- - '###'
  - 3.4.2 Python 的内置数据结构
- - '####'
  - 3.4.2.1 Python 中的自定义数据结构
- - '###'
  - 3.4.3 内置数据结构
- - '####'
  - 3.4.3.1 列表
- - '#####'
  - 3.4.3.1.1 创建列表
- - '#####'
  - 3.4.3.1.2 添加元素
- - '#####'
  - 3.4.3.1.3 删除元素
- - '#####'
  - 3.4.3.1.4 访问元素
- - '#####'
  - 3.4.3.1.5 其他列表操作
- - '####'
  - 3.4.3.2 Python 中的字典
- - '#####'
  - 3.4.3.2.1 创建字典
- - '#####'
  - 3.4.3.2.2 修改和添加键值对
- - '#####'
  - 3.4.3.2.3 删除键值对
- - '#####'
  - 3.4.3.2.4 访问元素
- - '#####'
  - 3.4.3.2.5 其他函数
- - '####'
  - 3.4.3.3 Python 中的元组
- - '#####'
  - 3.4.3.3.1 创建元组
- - '#####'
  - 3.4.3.3.2 访问元素
- - '#####'
  - 3.4.3.3.3 追加元素
- - '#####'
  - 3.4.3.3.4 其他函数
- - '####'
  - 3.4.3.4 Python 中的集合
- - '#####'
  - 3.4.3.4.1 创建集合
- - '#####'
  - 3.4.3.4.2 添加元素
- - '#####'
  - 3.4.3.4.3 集合运算
- - '##'
  - 3.5 常规函数与 Lambda 函数
- - '###'
  - 3.5.1 Python 中的函数是什么？
- - '###'
  - 3.5.2 `return` 语句
- - '###'
  - 3.5.3 函数中的 `return` 与 `print`
- - '###'
  - 3.5.4 方法与函数
- - '###'
  - 3.5.5 如何在 Python 中调用函数
- - '###'
  - 3.5.6 Python 中的函数参数
- - '####'
  - 3.5.6.1 位置参数
- - '####'
  - 3.5.6.2 关键字参数
- - '####'
  - 3.5.6.3 默认参数
- - '####'
  - 3.5.6.4 可变长度参数（`*args` 和 `**kwargs`）
- - '###'
  - 3.5.7 Python 中的匿名函数
- - '##'
  - 3.6 总结
- - '#'
  - 4. Python 与其他编程方法
- - '##'
  - 4.1 Python 中的面向对象编程
- - '###'
  - 4.1.1 为什么要在 Python 中使用面向对象编程？
- - '####'
  - 4.1.1.1 Python 中一切都是对象
- - '####'
  - 4.1.1.2 属性和方法
- - '###'
  - 4.1.2 你的第一个 Python 对象
- - '####'
  - 4.1.2.1 定义 'Book' 类
- - '####'
  - 4.1.2.2 创建并使用一个 “Book” 对象
- - '###'
  - 4.1.3 Python 中的面向对象编程（OOP）建立在四个基本概念之上
- - '####'
  - 4.1.3.1 抽象
- - '####'
  - 4.1.3.2 继承
- - '####'
  - 4.1.3.3 多态
- - '####'
  - 4.1.3.4 封装
- - '##'
  - 4.2 模块与文件处理
- - '###'
  - 4.2.1 Python 模块
- - '###'
  - 4.2.2 理解 Python 模块
- - '###'
  - 4.2.3 创建 Python 模块
- - '###'
  - 4.2.4 在 Python 中导入模块
- - '####'
  - 4.2.4.1 使用 `from` 语句进行 Python 导入
- - '####'
  - 4.2.4.2 从 Python 模块导入特定属性
- - '####'
  - 4.2.4.3 导入所有名称
- - '###'
  - 4.2.5 定位 Python 模块
- - '###'
  - 4.2.6 重命名 Python 模块
- - '###'
  - 4.2.7 Python 内置模块
- - '###'
  - 4.2.8 Python 文件处理
- - '####'
  - 4.2.8.1 在读取模式下工作
- - '####'
  - 4.2.8.2 使用 `write()` 函数创建文件
- - '####'
  - 4.2.8.3 使用追加模式
- - '##'
  - 4.3 Python 3.11 的强大功能
- - '###'
  - 4.3.1 TypedDicts
- - '####'
  - 4.3.1.1 `TypedDict` 还是仅仅一个 `Dict`？
- - '###'
  - 4.3.2 `Required[]` 和 `NotRequired[]`
- - '###'
  - 4.3.3 Self 类型
- - '####'
  - 4.3.3.1 使用 Self 类型
- - '###'
  - 4.3.4 改进的异常处理
- - '####'
  - 4.3.4.1 更好的错误消息
- - '####'
  - 4.3.4.2 异常注释
- - '####'
  - 4.3.4.3 添加异常注释的另一种方法：将其定义为自定义异常类的属性
- - '####'
  - 4.3.4.4 异常组
- - '####'
  - 4.3.4.5 TOML 支持
- - '####'
  - 4.3.4.6 改进的类型变量
- - '####'
  - 4.3.4.7 任意字面量字符串类型
- - '####'
  - 4.3.4.8 可变参数泛型
- - '####'
  - 4.3.4.9 负零格式化
- - '###'
  - 4.3.5 理解 Python 3.11 在 AI 和 NLP 中的作用 – 为什么选择 Python？
- - '####'
  - 4.3.5.1 为什么选择 Python 用于 AI？
- - '####'
  - 4.3.5.2 为什么选择 Python 用于 NLP？
- - '##'
  - 4.4 总结
- - '#'
  - 5. 大语言模型架构组件基础概述
- - '##'
  - 5.1 `嵌入`层
- - '###'
  - 5.1.1 阶段 1：节点
- - '###'
  - 5.1.2 阶段 2：返回至词
- - '###'
  - 5.1.3 阶段 3：实现 Softmax 层
- - '###'
  - 5.1.4 前馈层
- - '####'
  - 5.1.4.1 什么是前馈神经网络？
- - '####'
  - 5.1.4.2 前馈阶段
- - '####'
  - 5.1.4.3 反向传播阶段
- - '####'
  - 5.1.4.4 大语言模型与前馈层
- - '##'
  - 5.2 循环层
- - '###'
  - 5.2.1 深入了解循环层在大语言模型中的运作方式
- - '####'
  - 5.2.1.1 序列数据处理
- - '#####'
  - 5.2.1.1.1 隐藏状态
- - '####'
  - 5.2.1.2 时间反向传播
- - '####'
  - 5.2.1.3 挑战与解决方案
- - '###'
  - 5.2.2 注意力机制
- - '####'
  - 5.2.2.1 自注意力（内部注意力）
- - '#####'
  - 5.2.2.1.1 多头注意力
- - '#####'
  - 5.2.2.1.2 交叉注意力（编码器-解码器注意力）
- - '#####'
  - 5.2.2.1.3 掩码注意力
- - '#####'
  - 5.2.2.1.4 稀疏注意力
- - '#####'
  - 5.2.2.1.5 全局/局部注意力
- - '##'
  - 5.3 理解 Token、Token 分布以及预测下一个 Token
- - '###'
  - 5.3.1 理解大型语言模型中的分词
- - '###'
  - 5.3.2 分词技术对大型语言模型的优势
- - '###'
  - 5.3.3 局限性与挑战
- - '###'
  - 5.3.4 当前分词技术面临的挑战
- - '####'
  - 5.3.4.1 分词中的大小写敏感性
- - '####'
  - 5.3.4.2 数值数据处理
- - '####'
  - 5.3.4.3 尾部空格的不一致性
- - '####'
  - 5.3.4.4 模型特定的分词实践
- - '####'
  - 5.3.4.5 把握上下文细微差别
- - '####'
  - 5.3.4.6 处理歧义
- - '####'
  - 5.3.4.7 解释习语
- - '####'
  - 5.3.4.8 处理特殊符号和字符
- - '###'
  - 5.3.5 大型语言模型中的分词策略
- - '###'
  - 5.3.6 什么是令牌分布？
- - '###'
  - 5.3.7 预测下一个令牌
- - '##'
  - 5.4 零样本与少样本学习
- - '###'
  - 5.4.1 少样本学习
- - '####'
  - 5.4.1.1 少样本学习的意义
- - '####'
  - 5.4.1.2 少样本学习的实际应用
- - '###'
  - 5.4.2 零样本学习
- - '####'
  - 5.4.2.1 零样本学习的意义与用例
- - '####'
  - 5.4.2.2 解读有限数据学习：少样本学习、单样本学习和零样本学习详解
- - '####'
  - 5.4.2.3 示例
- - '###'
  - 5.4.3 少样本学习
- - '###'
  - 5.4.4 单样本学习
- - '###'
  - 5.4.5 零样本学习
- - '##'
  - 5.5 大语言模型幻觉
- - '###'
  - 5.5.1 大语言模型中幻觉的分类
- - '####'
  - 5.5.1.1 事实性幻觉
- - '####'
  - 5.5.1.2 忠实性幻觉
- - '###'
  - 5.5.2 人工智能幻觉的影响
- - '###'
  - 5.5.3 降低 AI 幻觉风险：预防策略
- - '####'
  - 5.5.3.1 确保高质量训练数据
- - '####'
  - 5.5.3.2 明确模型的目的与约束
- - '####'
  - 5.5.3.3 实施数据模板
- - '####'
  - 5.5.3.4 限制可能的结果
- - '####'
  - 5.5.3.5 持续测试与优化
- - '####'
  - 5.5.3.6 引入人工监督
- - '###'
  - 5.5.4 幻觉何时可能有益？
- - '##'
  - 5.6 未来影响
- - '##'
  - 5.7 大型语言模型架构示例
- - '###'
  - 5.7.1 GPT-4
- - '####'
  - 5.7.1.1 模型特性
- - '#####'
  - 5.7.1.1.1 GPT-4 的局限性
- - '####'
  - 5.7.1.2 关键要点
- - '###'
  - 5.7.2 BERT
- - '####'
  - 5.7.2.1 BERT 简介
- - '####'
  - 5.7.2.2 BERT 的双向特性
- - '####'
  - 5.7.2.3 BERT 的训练阶段：预训练与微调
- - '#####'
  - 5.7.2.3.1 阶段一：使用未标记数据进行预训练
- - '#####'
  - 5.7.2.3.2 阶段二：针对特定任务的微调
- - '####'
  - 5.7.2.4 BERT 的工作原理
- - '####'
  - 5.7.2.5 BERT 的架构创新
- - '####'
  - 5.7.2.6 从训练到应用
- - '###'
  - 5.7.3 BERT 在语言处理中的应用
- - '###'
  - 5.7.4 T5
- - '###'
  - 5.7.5 Cohere
- - '###'
  - 5.7.6 PaLM 2
- - '####'
  - 5.7.6.1 PaLM 2 的工作原理
- - '#####'
  - 5.7.6.1.1 初始数据获取与准备
- - '#####'
  - 5.7.6.1.2 利用 Transformer 架构
- - '#####'
  - 5.7.6.1.3 广泛的预训练
- - '#####'
  - 5.7.6.1.4 特定任务的微调
- - '#####'
  - 5.7.6.1.5 新颖的 Pathways 架构
- - '#####'
  - 5.7.6.1.6 独立路径运作
- - '#####'
  - 5.7.6.1.7 自适应计算资源分配
- - '####'
  - 5.7.6.2 路径交互与协作
- - '#####'
  - 5.7.6.2.1 选择性路径参与
- - '#####'
  - 5.7.6.2.2 生成输出
- - '###'
  - 5.7.7 Jurassic-2
- - '###'
  - 5.7.8 Claude v1
- - '####'
  - 5.7.8.1 数据与训练方法
- - '####'
  - 5.7.8.2 模型设计
- - '####'
  - 5.7.8.3 Claude v1 的局限性
- - '###'
  - 5.7.9 Falcon 40B
- - '####'
  - 5.7.9.1 模型设计
- - '####'
  - 5.7.9.2 训练数据
- - '####'
  - 5.7.9.3 训练过程
- - '####'
  - 5.7.9.4 多查询注意力机制
- - '####'
  - 5.7.9.5 用于增强性能的指令版本
- - '####'
  - 5.7.9.6 用户可访问性
- - '###'
  - 5.7.10 LLaMA
- - '###'
  - 5.7.11 LaMDA
- - '###'
  - 5.7.12 Guanaco-65B
- - '###'
  - 5.7.13 Orca
- - '###'
  - 5.7.14 StableLM
- - '###'
  - 5.7.15 Palmyra
- - '###'
  - 5.7.16 GPT4All
- - '##'
  - 5.8 总结
- - '#'
  - 6. LLM 在 Python 中的应用
- - '##'
  - 6.1 文本生成与创意写作
- - '###'
  - 6.1.1 文本生成背后的机制
- - '###'
  - 6.1.2 文本生成的重要性
- - '###'
  - 6.1.3 文本生成的关键用例
- - '###'
  - 6.1.4 什么是创意写作
- - '###'
  - 6.1.5 利用大语言模型进行创意写作
- - '####'
  - 6.1.5.1 概念构思与头脑风暴
- - '####'
  - 6.1.5.2 撰写与润色
- - '####'
  - 6.1.5.3 对话创作与角色塑造
- - '####'
  - 6.1.5.4 世界构建与场景设定
- - '####'
  - 6.1.5.5 诗歌与实验文学
- - '###'
  - 6.1.6 基于 OpenAI 的用户指定主题和长度的博客文章生成器
- - '##'
  - 6.2 语言翻译与多语言大语言模型
- - '###'
  - 6.2.1 使用 LLM 进行翻译的优势
- - '###'
  - 6.2.2 大语言模型如何实现语言翻译？
- - '###'
  - 6.2.3 大语言模型翻译面临的挑战
- - '###'
  - 6.2.4 大语言模型对翻译与本地化行业的潜在影响
- - '####'
  - 6.2.4.1 效率提升
- - '####'
  - 6.2.4.2 质量升级
- - '####'
  - 6.2.4.3 创新机遇
- - '###'
  - 6.2.5 基于谷歌 T5 模型的翻译应用
- - '##'
  - 6.3 文本摘要与文档理解
- - '###'
  - 6.3.1 使用用户提供的 URL 进行文章摘要的应用
- - '##'
  - 6.4 问答系统：知识触手可及
- - '###'
  - 6.4.1 通过大型语言模型（LLM）增强问答能力
- - '###'
  - 6.4.2 利用大型语言模型进行高级文档分析
- - '###'
  - 6.4.3 从数据到响应的旅程：全面概述
- - '####'
  - 6.4.3.1 文档解析与准备
- - '####'
  - 6.4.3.2 文本嵌入与索引
- - '####'
  - 6.4.3.3 查询处理与上下文检索
- - '####'
  - 6.4.3.4 答案生成
- - '###'
  - 6.4.4 生成式问答的实际应用与用例
- - '####'
  - 6.4.4.1 通过自动回复增强客户支持
- - '####'
  - 6.4.4.2 在报告和非结构化文档中的高效搜索
- - '####'
  - 6.4.4.3 大型组织的知识管理
- - '###'
  - 6.4.5 带来源的文档问答聊天机器人
- - '####'
  - 6.4.5.1 抓取用户提供的文章
- - '#####'
  - 6.4.5.1.1 启动链的设置
- - '###'
  - 6.4.6 应用的完整代码
- - '##'
  - 6.5 聊天机器人与虚拟助手
- - '###'
  - 6.5.1 聊天机器人的核心理念是什么？
- - '###'
  - 6.5.2 经 LLM 训练的聊天机器人的实际应用
- - '###'
  - 6.5.3 使用 LLM 构建聊天机器人指南
- - '####'
  - 6.5.3.1 模型选择
- - '####'
  - 6.5.3.2 数据预处理与清洗
- - '####'
  - 6.5.3.3 模型微调
- - '####'
  - 6.5.3.4 集成与部署
- - '####'
  - 6.5.3.5 最佳实践与注意事项
- - '###'
  - 6.5.4 客户支持问答聊天机器人
- - '####'
  - 6.5.4.1 步骤 1：文档分割与嵌入计算
- - '####'
  - 6.5.4.2 步骤 2：利用推荐技巧为 GPT-3 构建提示词
- - '####'
  - 6.5.4.3 第三步：使用温度为 0 的 GPT-3 模型进行文本生成
- - '##'
  - 6.6 基础提示工程——所有应用中的共通之处
- - '###'
  - 6.6.1 理解提示工程
- - '###'
  - 6.6.2 基础提示技巧
- - '####'
  - 6.6.2.1 提示模板示例
- - '##'
  - 6.7 摘要
- - '#'
  - 7. 利用 Python 3.11 和 Python 库进行大语言模型开发
- - '##'
  - 7.1 LangChain
- - '###'
  - 7.1.1 LangChain 特性
- - '###'
  - 7.1.2 LangChain 有哪些集成？
- - '###'
  - 7.1.3 如何在 LangChain 中构建应用？
- - '###'
  - 7.1.4 LangChain 的应用场景
- - '###'
  - 7.1.5 LangChain 应用示例 – 文章摘要生成器
- - '##'
  - 7.2 Hugging Face
- - '###'
  - 7.2.1 Hugging Face 的发展历程
- - '###'
  - 7.2.2 Hugging Face 的核心组件
- - '####'
  - 7.2.2.1 Transformers 库
- - '####'
  - 7.2.2.2 Hugging Face Hub
- - '####'
  - 7.2.2.3 模型中心
- - '####'
  - 7.2.2.4 分词器
- - '####'
  - 7.2.2.5 数据集库
- - '###'
  - 7.2.3 示例应用
- - '##'
  - 7.3 OpenAI API
- - '###'
  - 7.3.1 OpenAI API 的特性
- - '####'
  - 7.3.1.1 预训练模型
- - '####'
  - 7.3.1.2 通过微调进行定制
- - '####'
  - 7.3.1.3 用户友好的 API 接口
- - '####'
  - 7.3.1.4 可扩展的基础设施
- - '###'
  - 7.3.2 OpenAI API 的行业应用
- - '###'
  - 7.3.3 连接到 OpenAI API 的简单示例
- - '##'
  - 7.4 Cohere
- - '###'
  - 7.4.1 Cohere 模型
- - '####'
  - 7.4.1.1 Command
- - '####'
  - 7.4.1.2 Embed
- - '####'
  - 7.4.1.3 Rerank
- - '#####'
  - 7.4.1.3.1 情感分析示例应用
- - '##'
  - 7.5 Pinecone
- - '###'
  - 7.5.1 向量数据库的运作方式
- - '###'
  - 7.5.2 向量数据库究竟是什么？
- - '###'
  - 7.5.3 Pinecone 的特性
- - '###'
  - 7.5.4 实际应用
- - '##'
  - 7.6 Lamini.ai
- - '###'
  - 7.6.1 Lamini 的运行机制
- - '###'
  - 7.6.2 Lamini 的特性、功能与优势
- - '###'
  - 7.6.3 Lamini 的应用场景与用例
- - '##'
  - 7.7 Python 库的数据收集、清洗与准备
- - '###'
  - 7.7.1 大型语言模型的数据收集与准备
- - '####'
  - 7.7.1.1 数据获取
- - '####'
  - 7.7.1.2 什么是数据预处理？
- - '####'
  - 7.7.1.3 准备用于训练的数据集
- - '####'
  - 7.7.1.4 管理无用数据
- - '####'
  - 7.7.1.5 处理文档长度
- - '####'
  - 7.7.1.6 机器生成的文本
- - '####'
  - 7.7.1.7 移除重复内容
- - '####'
  - 7.7.1.8 数据净化
- - '####'
  - 7.7.1.9 处理有害内容和偏见
- - '####'
  - 7.7.1.10 保护个人身份信息 (PII)
- - '####'
  - 7.7.1.11 处理缺失数据
- - '####'
  - 7.7.1.12 通过数据增强提升数据集质量
- - '####'
  - 7.7.1.13 数据归一化
- - '####'
  - 7.7.1.14 数据解析
- - '####'
  - 7.7.1.15 分词
- - '####'
  - 7.7.1.16 词干提取与词形还原
- - '###'
  - 7.7.2 大型语言模型的特征工程
- - '####'
  - 7.7.2.1 词嵌入
- - '####'
  - 7.7.2.2 上下文嵌入
- - '####'
  - 7.7.2.3 子词嵌入
- - '###'
  - 7.7.3 数据处理最佳实践
- - '####'
  - 7.7.3.1 实施强大的数据清洗协议
- - '####'
  - 7.7.3.2 主动进行偏差管理
- - '####'
  - 7.7.3.3 实施持续的质量控制和反馈机制
- - '####'
  - 7.7.3.4 促进跨学科合作
- - '####'
  - 7.7.3.5 优先考虑教育成长和技能发展
- - '###'
  - 7.7.4 深入探索关键库
- - '####'
  - 7.7.4.1 自然语言处理与高级分析
- - '####'
  - 7.7.4.2 数据准备与完整性
- - '##'
  - 7.8 总结
- - '#'
  - 脚注
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U, V
- - '##'
  - W, X, Y
- - '##'
  - Z
