name: PyTorch Recipes
name_cn: PyTorch 秘籍
slug: pytorch-recipes
toc:
- - '#'
  - 引言
- - '#'
  - 致谢
- - '##'
  - 关于作者与技术审校者
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校者
- - '#'
  - PyTorch、张量及张量运算简介
- - '##'
  - 什么是 PyTorch？
- - '##'
  - PyTorch 安装
- - '##'
  - 方法 1-1：使用张量
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 结论
- - '#'
  - 2. 使用 PyTorch 的概率分布
- - '##'
  - 方法 2-1. 张量采样
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 2-2. 变量张量
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 2-3. 基础统计
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 2-4. 梯度计算
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 2-5. 张量运算
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 2-6. 张量运算
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 2-7. 分布
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 结论
- - '#'
  - 3. 使用 PyTorch 的 CNN 与 RNN
- - '##'
  - 方法 3-1. 设置损失函数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-2. 估计损失函数的导数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-3. 微调模型
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-4. 选择优化函数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-5. 进一步优化函数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-6. 实现卷积神经网络 (CNN)
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-7. 重新加载模型
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-8. 实现循环神经网络 (RNN)
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-9. 为回归问题实现 RNN
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-10. 使用 PyTorch 内置函数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-11：使用自编码器
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-12：使用自编码器微调结果
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-13：在 3D 图中可视化编码数据
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-14：限制模型过拟合
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-15. 可视化模型过拟合
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-16. 在 Dropout 比率中初始化权重
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-17. 添加数学运算
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 3-18. 在 RNN 中嵌入层
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 结论
- - '#'
  - 4. 使用 PyTorch 的神经网络入门
- - '##'
  - 方法 4-1. 使用激活函数
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '####'
  - 线性函数
- - '####'
  - 双线性函数
- - '####'
  - Sigmoid 函数
- - '####'
  - 双曲正切函数
- - '####'
  - 对数 Sigmoid 传递函数
- - '####'
  - ReLU 函数
- - '####'
  - 带泄露的 ReLU
- - '##'
  - 方法 4-2. 可视化激活函数的形状
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 4-3. 基础神经网络模型
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 4-4. 张量微分
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 结论
- - '#'
  - 5. 使用 PyTorch 进行监督学习
- - '##'
  - 线性回归简介
- - '##'
  - 方法 5-1. 监督模型的数据准备
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 5-2. 前向传播与反向传播
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 5-3. 优化与梯度计算
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 5-4. 查看预测结果
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 5-5. 监督模型：逻辑回归
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 结论
- - '#'
  - 6. 使用 PyTorch 微调深度学习模型
- - '##'
  - 方法 6-1. 构建序列神经网络
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 6-2：决定批量大小
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 6-3：决定学习率
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 6-4：执行并行训练
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 结论
- - '#'
  - 7. 使用 PyTorch 进行自然语言处理
- - '##'
  - 方法 7-1. 词嵌入
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 7-2. PyTorch 中的 CBOW 模型
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '##'
  - 方法 7-3. LSTM 模型
- - '###'
  - 问题
- - '###'
  - 解决方案
- - '###'
  - 工作原理
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D, E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U, V
- - '##'
  - W, X, Y, Z
