name: Practical Python AI Projects
name_cn: Python AI 项目实战指南
slug: practical-python-ai-projects
toc:
- - '#'
  - 致谢
- - '#'
  - 目录
- - '#'
  - 1. 引言
- - '##'
  - 1.1 本书内容简介
- - '##'
  - 1.2 本书特点
- - '###'
  - 1.2.1 运行模型
- - '###'
  - 1.2.2 关于符号的说明
- - '##'
  - 1.3 初试牛刀：两栖动物共存问题
- - '#'
  - 2. 线性连续模型
- - '##'
  - 2.1 混合问题
- - '###'
  - 2.1.1 构建模型
- - '###'
  - 2.1.2 变体
- - '###'
  - 2.1.3 所考虑问题的结构
- - '##'
  - 2.2 混合问题
- - '###'
  - 2.2.1 构建模型
- - '###'
  - 2.2.2 变体
- - '##'
  - 2.3 项目管理
- - '###'
  - 2.3.1 构建模型
- - '###'
  - 2.3.2 变体
- - '####'
  - 2.3.2.1 极小化极大问题
- - '####'
  - 2.3.2.2 绝对值问题
- - '##'
  - 2.4 多阶段模型
- - '###'
  - 2.4.1 问题实例
- - '###'
  - 2.4.2 构建模型
- - '####'
  - 2.4.2.1 决策变量
- - '####'
  - 2.4.2.2 约束条件
- - '####'
  - 2.4.2.3 目标函数
- - '####'
  - 2.4.2.4 可执行模型
- - '###'
  - 2.4.3 变体
- - '##'
  - 2.5 模式分类
- - '###'
  - 2.5.1 构建模型
- - '###'
  - 2.5.2 可执行模型
- - '####'
  - 2.5.2.1 变体
- - '#'
  - 3. 隐式线性连续模型
- - '##'
  - 3.1 分段线性
- - '###'
  - 3.1.1 构建模型
- - '####'
  - 3.1.1.1 约束条件
- - '####'
  - 3.1.1.2 目标函数
- - '####'
  - 3.1.1.3 可执行模型
- - '###'
  - 3.1.2 变体
- - '####'
  - 3.1.2.1 通过线性近似进行非线性函数最小化
- - '####'
  - 3.1.2.2 非凸分段线性函数
- - '##'
  - 3.2 曲线拟合
- - '###'
  - 3.2.1 构建模型
- - '####'
  - 3.2.1.1 目标函数
- - '####'
  - 3.2.1.2 约束条件
- - '####'
  - 3.2.1.3 可执行模型
- - '###'
  - 3.2.2 变体
- - '##'
  - 3.3 模式分类再探讨
- - '###'
  - 3.3.1 可执行模型
- - '#'
  - 4. 线性网络模型
- - '##'
  - 4.1 最大流
- - '###'
  - 4.1.1 构建模型
- - '###'
  - 4.1.2 决策变量
- - '####'
  - 4.1.2.1 目标函数
- - '####'
  - 4.1.2.2 约束条件
- - '####'
  - 4.1.2.3 可执行模型
- - '###'
  - 4.1.3 变体
- - '##'
  - 4.2 最小成本流
- - '###'
  - 4.2.1 构建模型
- - '####'
  - 4.2.1.1 决策变量
- - '####'
  - 4.2.1.2 目标
- - '####'
  - 4.2.1.3 约束条件
- - '####'
  - 4.2.1.4 可执行模型
- - '###'
  - 4.2.2 变体
- - '##'
  - 4.3 转运问题
- - '###'
  - 4.3.1 构建模型
- - '####'
  - 4.3.1.1 目标函数
- - '####'
  - 4.3.1.2 约束条件
- - '####'
  - 4.3.1.3 可执行模型
- - '###'
  - 4.3.2 变体
- - '##'
  - 4.4 最短路径
- - '###'
  - 4.4.1 构建模型
- - '###'
  - 4.4.2 替代算法
- - '###'
  - 4.4.3 变体
- - '#'
  - 5. 经典离散模型
- - '##'
  - 5.1 最小集合覆盖
- - '###'
  - 5.1.1 构建模型
- - '####'
  - 5.1.1.1 决策变量
- - '####'
  - 5.1.1.2 目标函数
- - '####'
  - 5.1.1.3 约束条件
- - '####'
  - 5.1.1.4 可执行模型
- - '###'
  - 5.1.2 变体
- - '##'
  - 5.2 集合打包
- - '###'
  - 5.2.1 构建模型
- - '####'
  - 5.2.1.1 决策变量
- - '####'
  - 5.2.1.2 目标函数
- - '####'
  - 5.2.1.3 约束条件
- - '####'
  - 5.2.1.4 可执行模型
- - '###'
  - 5.2.2 变体
- - '##'
  - 5.3 装箱问题
- - '###'
  - 5.3.1 构建模型
- - '####'
  - 5.3.1.1 决策变量
- - '####'
  - 5.3.1.2 约束条件
- - '####'
  - 5.3.1.3 目标函数
- - '####'
  - 5.3.1.4 可执行模型
- - '####'
  - 5.3.1.5 变体
- - '##'
  - 5.4 TSP
- - '###'
  - 5.4.1 构建模型
- - '####'
  - 5.4.1.1 决策变量
- - '####'
  - 5.4.1.2 目标函数
- - '####'
  - 5.4.1.3 约束条件
- - '####'
  - 5.4.1.4 可执行模型
- - '###'
  - 5.4.2 变体
- - '#'
  - 6. 经典混合模型
- - '##'
  - 6.1 设施选址问题
- - '###'
  - 6.1.1 构建模型
- - '####'
  - 6.1.1.1 决策变量
- - '####'
  - 6.1.1.2 目标函数
- - '####'
  - 6.1.1.3 约束条件
- - '####'
  - 6.1.1.4 可执行模型
- - '###'
  - 6.1.2 变体
- - '##'
  - 6.2 多商品流
- - '###'
  - 6.2.1 构建模型
- - '####'
  - 6.2.1.1 决策变量
- - '####'
  - 6.2.1.2 目标函数
- - '####'
  - 6.2.1.3 约束条件
- - '####'
  - 6.2.1.4 可执行模型
- - '###'
  - 6.2.2 变体
- - '####'
  - 6.2.2.1 全源最短路径（重访）
- - '###'
  - 6.2.3 实例
- - '##'
  - 6.3 人员配置水平
- - '###'
  - 6.3.1 构建模型
- - '####'
  - 6.3.1.1 决策变量
- - '####'
  - 6.3.1.2 目标函数
- - '####'
  - 6.3.1.3 约束条件
- - '####'
  - 6.3.1.4 可执行模型
- - '###'
  - 6.3.2 变体
- - '##'
  - 6.4 作业车间调度
- - '###'
  - 6.4.1 构建模型
- - '####'
  - 6.4.1.1 可执行模型
- - '#'
  - 7. 高级技术
- - '##'
  - 7.1 下料问题
- - '###'
  - 7.1.1 构建模型
- - '####'
  - 7.1.1.1 决策变量
- - '####'
  - 7.1.1.2 目标函数
- - '####'
  - 7.1.1.3 约束条件
- - '####'
  - 7.1.1.4 可执行模型
- - '###'
  - 7.1.2 预分配切割模式
- - '##'
  - 7.2 非凸技巧
- - '###'
  - 7.2.1 从 n 个变量中选取 k 个非零变量
- - '###'
  - 7.2.2 从 n 个变量中选取 k 个相邻的非零变量
- - '###'
  - 7.2.3 从 n 个约束中选取 k 个
- - '###'
  - 7.2.4 极大极大与极小极小
- - '##'
  - 7.3 员工排班
- - '###'
  - 7.3.1 构建模型
- - '####'
  - 7.3.1.1 决策变量
- - '####'
  - 7.3.1.2 约束条件
- - '####'
  - 7.3.1.3 目标函数
- - '####'
  - 7.3.1.4 可执行模型
- - '###'
  - 7.3.2 变体
- - '##'
  - 7.4 体育赛程安排
- - '###'
  - 7.4.1 构建模型
- - '####'
  - 7.4.1.1 决策变量
- - '####'
  - 7.4.1.2 约束
- - '####'
  - 7.4.1.3 目标函数
- - '####'
  - 7.4.1.4 可执行模型
- - '###'
  - 7.4.2 变体
- - '##'
  - 7.5 谜题
- - '###'
  - 7.5.1 伪国际象棋问题
- - '###'
  - 7.5.2 数独
- - '###'
  - 7.5.3 寄出更多钱！
- - '###'
  - 7.5.4 淑女与老虎
- - '##'
  - 7.6 OR-Tools MPSolver Python 快速参考
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - C
- - '##'
  - D, E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T, U, V, W, X, Y, Z
