name: Generating a New Reality
name_cn: 生成新现实
slug: generating-a-new-reality
toc:
- - '#'
  - 引言
- - '#'
  - 致谢
- - '#'
  - 1. 深度学习基础
- - '##'
  - 先决条件
- - '##'
  - 感知器
- - '###'
  - 练习 1-1. 编写感知器代码
- - '##'
  - 多层感知机
- - '###'
  - 反向传播
- - '###'
  - 随机梯度下降
- - '###'
  - PyTorch 与深度学习
- - '####'
  - 练习 1-3. 在 PyTorch 上用 MLP 解决 XOR 问题
- - '##'
  - 理解回归
- - '###'
  - 练习 1-4. 使用 PyTorch 预测房价
- - '####'
  - 过拟合与欠拟合
- - '##'
  - 对类别进行分类
- - '###'
  - 独热编码
- - '##'
  - 对 MNIST 手写数字进行分类
- - '###'
  - 练习 1-5. 使用 PyTorch 对 MNIST 进行分类
- - '##'
  - 结论
- - '#'
  - 2. 释放生成式建模的力量
- - '##'
  - 使用自编码器进行无监督学习
- - '##'
  - 使用卷积提取特征
- - '###'
  - 练习 2-2. 用于分类的卷积网络
- - '##'
  - 卷积自编码器
- - '###'
  - 练习 2-3. 在 CIFAR10 上实现卷积自编码器
- - '##'
  - 生成对抗网络
- - '###'
  - 练习 2-4. 构建基础版 GAN
- - '##'
  - 深度卷积生成对抗网络
- - '##'
  - 结论
- - '#'
  - 3. 探索潜在空间
- - '##'
  - 理解深度学习的学习内容
- - '###'
  - 深度学习函数逼近
- - '####'
  - 微积分的局限性
- - '####'
  - 深度学习爬山法
- - '##'
  - 学习率与过拟合/欠拟合
- - '###'
  - 练习 3-2：调整学习率以实现高效学习
- - '###'
  - 过拟合与欠拟合
- - '##'
  - 泛化与过拟合、欠拟合
- - '###'
  - 练习 3-3：理解过拟合与欠拟合
- - '##'
  - 构建变分自编码器
- - '###'
  - 练习 3-4：构建卷积变分自编码器
- - '##'
  - 使用 VAE 学习分布
- - '###'
  - 练习 3-5. 理解 VAE
- - '##'
  - 首先可视化原始图像
- - '##'
  - 使用 VAE 重建并可视化图像
- - '###'
  - 变异性与探索潜在空间
- - '##'
  - 结论
- - '#'
  - 4. 生成对抗网络，以及更多的生成对抗网络
- - '##'
  - 特征理解与深度卷积生成对抗网络
- - '###'
  - 初始化权重
- - '##'
  - 揭开 GAN 的数学原理
- - '###'
  - 使用 WGAN 解决距离问题
- - '##'
  - 离散化边界搜索生成对抗网络
- - '###'
  - 练习 4-3. 使用 BGAN 打破边界
- - '##'
  - 生成器损失
- - '##'
  - 衡量欺骗判别器的能力
- - '##'
  - 判别器损失
- - '##'
  - 相对论与相对论 GAN
- - '###'
  - 练习 4-4. 关联相对论 GAN
- - '##'
  - 生成器
- - '##'
  - 判别器
- - '##'
  - 使用 CGAN 进行条件控制
- - '##'
  - 结论
- - '#'
  - 5. 图像到图像的内容生成
- - '##'
  - 使用 UNet 进行图像分割
- - '###'
  - 揭示 UNet 的细节
- - '##'
  - 使用 Pix2Pix 进行图像翻译
- - '###'
  - GAN 损失
- - '###'
  - 逐像素损失
- - '###'
  - 总损失
- - '###'
  - 真实损失
- - '###'
  - 虚假损失
- - '###'
  - 总损失
- - '##'
  - 双 GAN：双重视角
- - '###'
  - 将图像翻译到相反域
- - '###'
  - 重建图像
- - '###'
  - 对抗损失
- - '###'
  - 循环损失
- - '###'
  - 总损失
- - '###'
  - 为改进的 Wasserstein 训练计算梯度惩罚
- - '###'
  - 对抗性损失
- - '###'
  - 为改进的 Wasserstein 训练计算梯度惩罚
- - '###'
  - 对抗性损失
- - '###'
  - 总损失
- - '##'
  - 驾驭 BicycleGAN 的潜在空间
- - '###'
  - VAE 翻译图像的像素级损失
- - '###'
  - 编码 B 的 Kullback-Leibler 散度
- - '###'
  - 对抗性损失
- - '##'
  - 使用 DiscoGAN 发现域
- - '###'
  - 练习 5-6. 使用 DiscoGAN 发现域
- - '###'
  - 像素级翻译损失
- - '###'
  - 总损失
- - '##'
  - 结论
- - '#'
  - 6. 残差网络生成对抗网络
- - '##'
  - 理解残差网络
- - '###'
  - 练习 6-1. 残差网络分类器
- - '##'
  - 残差网络与 CycleGAN
- - '###'
  - 再次循环：CycleGAN
- - '###'
  - 练习 6-2：使用 CycleGAN 进行循环与身份映射
- - '###'
  - 学习率更新调度器
- - '###'
  - 损失函数
- - '###'
  - 初始化生成器和判别器
- - '###'
  - 总损失
- - '##'
  - 使用 StarGAN 创建人脸
- - '###'
  - 练习 6-3. 使用 StarGAN 进行人脸条件控制
- - '###'
  - 初始化生成器和判别器
- - '###'
  - 真实图像
- - '###'
  - 伪造图像
- - '###'
  - 梯度惩罚
- - '###'
  - 对抗性损失
- - '###'
  - 分类损失
- - '###'
  - 总损失
- - '###'
  - 翻译并重建图像
- - '###'
  - 判别器评估翻译后的图像
- - '###'
  - 对抗性损失
- - '###'
  - 分类损失
- - '###'
  - 重建损失
- - '###'
  - 总损失
- - '##'
  - 最佳实践：迁移学习
- - '###'
  - 基于 VGG19 加载模型
- - '###'
  - 冻结各层
- - '###'
  - 修改最后一层
- - '##'
  - 使用 SRGAN 提高分辨率
- - '###'
  - 将特征提取器设置为推理模式
- - '###'
  - 从低分辨率输入生成高分辨率图像
- - '###'
  - 对抗损失
- - '###'
  - 内容损失
- - '###'
  - 总损失
- - '##'
  - 结论
- - '#'
  - 7. 注意力即一切！
- - '##'
  - 什么是注意力？
- - '###'
  - 理解注意力的类型
- - '####'
  - 应用注意力机制
- - '##'
  - 用注意力增强卷积
- - '###'
  - forward 函数内部
- - '##'
  - GAN 中的 Lipschitz 连续性
- - '###'
  - 什么是利普希茨连续性？
- - '###'
  - 用于在真实样本和虚假样本之间插值的随机权重项
- - '###'
  - 获取真实样本和虚假样本之间的随机插值
- - '###'
  - 获取关于插值的梯度
- - '####'
  - 练习 7-3. GAN 中的利普希茨连续性
- - '##'
  - 构建自注意力生成对抗网络
- - '###'
  - 练习 7-4. 构建并训练 SAGAN
- - '###'
  - Backward + Optimize
- - '##'
  - 改进 SAGAN
- - '###'
  - 练习 7-5. 改进 SAGAN
- - '##'
  - 结论
- - '#'
  - 8. 高级生成器
- - '##'
  - 渐进式增长的生成对抗网络
- - '###'
  - ProGAN 与 StyleGAN 版本 2
- - '####'
  - 练习 8-1：使用 ProGAN
- - '##'
  - 使用 StyleGAN 版本 2 进行样式化
- - '###'
  - 映射网络
- - '###'
  - 风格模块
- - '####'
  - 移除随机/传统输入
- - '####'
  - 随机变化（噪声输入）
- - '####'
  - 风格混合
- - '####'
  - W 的截断
- - '####'
  - 超参数调优
- - '###'
  - Frechet Inception Distance
- - '###'
  - StyleGAN2
- - '###'
  - 权重解调
- - '###'
  - 路径长度正则化
- - '###'
  - 惰性正则化
- - '###'
  - 无需渐进式增长
- - '###'
  - 大型网络
- - '##'
  - '`DeOldify`与新型`NoGAN`'
- - '###'
  - 练习 8-3：使用`DeOldify`为图像着色
- - '###'
  - 为视频着色与增强
- - '##'
  - 用 ArtLine 展现艺术风格
- - '###'
  - 练习 8-5. 用 ArtLine 展现艺术风格
- - '##'
  - 结论
- - '#'
  - 9. 深度伪造与换脸技术
- - '##'
  - 人脸交换工具介绍
- - '##'
  - 收集换脸数据
- - '###'
  - 练习 9-1. 下载名人脸部图像
- - '####'
  - 为深度伪造下载 YouTube 视频
- - '###'
  - 练习 9-2. 下载 YouTube 主题视频
- - '###'
  - Define the codec and create VideoWriter object
- - '##'
  - 理解深度伪造工作流程
- - '###'
  - 提取人脸
- - '####'
  - 排序与修剪人脸
- - '####'
  - 重新对齐对齐文件
- - '##'
  - 训练换脸模型
- - '###'
  - 练习 9-6. 训练换脸模型
- - '##'
  - 创建深度伪造视频
- - '###'
  - 练习 9-7. 转换视频以交换人脸
- - '####'
  - 编码视频
- - '###'
  - 练习 9-8. 创建深度伪造视频
- - '###'
  - Define the codec and create VideoWriter object
- - '##'
  - 结论
- - '#'
  - 10. 破解深度伪造
- - '##'
  - 理解面部操控方法
- - '###'
  - 破解伪造的技术
- - '####'
  - 手工特征
- - '####'
  - 基于学习的特征
- - '####'
  - 伪影
- - '##'
  - 识别深度伪造中的赝品
- - '##'
  - 结论
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
