name: Neural Networks in Unity
name_cn: Unity 神经网络实战
slug: neural-networks-in-unity
toc:
- - '#'
  - Unity 中的神经网络
- - '##'
  - 目录
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '##'
  - 引言
- - '##'
  - 第 1 章：神经网络基础
- - '###'
  - 神经网络简介
- - '###'
  - 深入探讨神经网络
- - '###'
  - 感知机
- - '###'
  - 激活函数及其不同类型
- - '####'
  - 恒等函数
- - '####'
  - 二进制阶跃函数
- - '####'
  - 逻辑函数或 Sigmoid 函数
- - '####'
  - Tanh 函数
- - '####'
  - Arctan 函数
- - '####'
  - 修正线性单元
- - '####'
  - 带泄露的 ReLU
- - '####'
  - Softmax 函数
- - '###'
  - 偏置和权重
- - '###'
  - 从头开始构建神经网络
- - '####'
  - Sigmoid 函数
- - '####'
  - 输入数据集
- - '####'
  - 输出数据集
- - '####'
  - 设定随机数种子，使计算结果具有确定性（这是一个良好的实践）
- - '####'
  - 以均值为 0 随机初始化权重
- - '####'
  - 前向传播
- - '####'
  - 使用链式法则进行误差反向传播
- - '####'
  - 我们错过了多少？
- - '####'
  - l1_error = l2_delta.dot(syn1.T)
- - '####'
  - 将我们的误差乘以 l1 处 sigmoid 函数的斜率
- - '####'
  - 更新权重
- - '###'
  - 反向传播
- - '###'
  - 本章小结
- - '##'
  - 第 2 章：Unity ML-Agents
- - '###'
  - Unity IDE
- - '###'
  - 机器学习智能体入门
- - '###'
  - 让我们从 TensorFlow 开始
- - '###'
  - 了解 Anaconda
- - '###'
  - 什么是 NVIDIA CUDA Toolkit？
- - '###'
  - GPU 加速的 TensorFlow
- - '###'
  - 在 Unity 中构建项目
- - '###'
  - 机器学习的内部操作
- - '###'
  - 在 Python 模式下训练 Anaconda
- - '###'
  - 使用 Jupyter Notebook
- - '####'
  - 检查环境参数
- - '####'
  - 设置默认工作大脑
- - '####'
  - 重置环境
- - '####'
  - 检查默认大脑的状态空间
- - '####'
  - 检查默认大脑的观测空间
- - '####'
  - 近端策略优化
- - '#####'
  - 通用参数
- - '#####'
  - 用于调优的算法特定参数
- - '####'
  - 创建 Tensorflow 模型图
- - '####'
  - 最终保存 TensorFlow 模型
- - '###'
  - 本章小结
- - '##'
  - 第 3 章：Unity 中的机器学习代理与神经网络
- - '###'
  - 通过更多示例扩展 Unity ML-Agents
- - '###'
  - 爬行器项目
- - '####'
  - 配置选项
- - '###'
  - 测试模拟
- - '###'
  - 使用 Unity C# 实现神经网络
- - '###'
  - 创建数据结构
- - '###'
  - 前馈网络
- - '###'
  - 在 Unity C# 中扩展 ML-Agents 与反向传播
- - '##'
  - 第 4 章：Unity C# 中的反向传播
- - '###'
  - 深入探讨反向传播
- - '###'
  - 构建数据结构
- - '###'
  - 前向传播与权重初始化
- - '###'
  - 测试反向传播神经网络
- - '##'
  - 第 5 章：Unity 中的数据可视化
- - '###'
  - Unity 中的机器学习数据可视化
- - '###'
  - 数据解析
- - '###'
  - 使用数据集
- - '###'
  - 另一个示例
- - '###'
  - 总结
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - G、H
- - '###'
  - I
- - '###'
  - M
- - '###'
  - J、K
- - '###'
  - N、O
- - '###'
  - P、Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T、U
- - '###'
  - V、W、X、Y、Z
