name: Trustworthy Artificial Intelligence Implementation
name_cn: 可信人工智能实施指南
slug: trustworthy-artificial-intelligence-implementation
toc:
- - '#'
  - 引言
- - '##'
  - 目标读者
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 关于技术审校者
- - '#'
  - 1. 引言
- - '##'
  - 从个性化医疗到精准健康
- - '##'
  - 排版与文本
- - '###'
  - 为什么是精准健康？为什么是现在？
- - '####'
  - 从数量到价值的范式转变
- - '####'
  - 健康的社会决定因素
- - '###'
  - 为何多样性对精准健康至关重要
- - '##'
  - 总结
- - '#'
  - 2. 什么是精准健康？
- - '##'
  - 精准健康的五个 P
- - '###'
  - 预测与预防
- - '###'
  - 治疗的个性化
- - '###'
  - 参与
- - '###'
  - 人群
- - '##'
  - 精准健康的考量
- - '###'
  - 成本
- - '###'
  - 基因只是起点
- - '###'
  - 健康公平
- - '###'
  - 数据未竟之力
- - '##'
  - 参与
- - '###'
  - 高接触意味着高科技
- - '###'
  - 表型组学
- - '###'
  - 数字化转型
- - '##'
  - 应用精准健康：P5H 精准医疗保健连续体
- - '###'
  - 健康阶段
- - '####'
  - A 阶段
- - '####'
  - B 阶段
- - '####'
  - C 阶段
- - '####'
  - D 阶段
- - '###'
  - 跨阶段优化
- - '###'
  - 干预层级
- - '####'
  - 第一层级
- - '####'
  - 第二层级
- - '####'
  - 第三层级
- - '####'
  - 第四层级
- - '##'
  - 总结
- - '#'
  - 3. 数据与数字表型
- - '##'
  - 数据的形式与类型
- - '###'
  - 形式
- - '###'
  - 类型
- - '##'
  - 数据来源
- - '###'
  - 传感器
- - '###'
  - 数字表型
- - '###'
  - 数字孪生
- - '##'
  - 数据挑战
- - '###'
  - 测量与完整性
- - '###'
  - 健康社会决定因素数据缺失
- - '###'
  - 隐私与安全
- - '###'
  - 成本
- - '###'
  - 与数据脱节
- - '###'
  - 通用数据模型采用有限
- - '###'
  - 超越定性数据
- - '##'
  - 数据驱动的行动范式
- - '###'
  - 将数据转化为信息、知识和智慧
- - '##'
  - 总结
- - '#'
  - 4. 精准健康中的人工智能与机器学习
- - '##'
  - 人工智能的三种类型
- - '###'
  - 弱人工智能
- - '###'
  - 通用人工智能
- - '###'
  - 超级人工智能
- - '##'
  - 机器学习简介
- - '###'
  - 机器学习框架
- - '###'
  - 软件与工具包
- - '##'
  - 可解释人工智能
- - '##'
  - 人工智能辅助精准健康在实践中的应用
- - '###'
  - 临床决策支持
- - '###'
  - 行为改变干预与生活方式医学
- - '###'
  - 新疗法、疾病定义与干预切入点
- - '###'
  - 数字孪生
- - '###'
  - 健康促进聊天机器人
- - '###'
  - 语音识别
- - '##'
  - 总结
- - '#'
  - 5. 精准健康的风险与伦理挑战
- - '##'
  - 负责任开发与伦理 AI 原则
- - '###'
  - 认知原则
- - '####'
  - 可解释性
- - '####'
  - 可靠性与安全性
- - '###'
  - 通用伦理 AI 原则
- - '####'
  - 偏见、包容性与公平性
- - '####'
  - 透明度与问责制
- - '####'
  - 合法性
- - '####'
  - 数据隐私与安全
- - '####'
  - 人类能动性
- - '####'
  - 行善原则
- - '####'
  - 重塑护理与医患关系
- - '####'
  - 健康不平等
- - '####'
  - 神学伦理
- - '##'
  - 职业准备
- - '##'
  - 总结
- - '#'
  - 6. 精准医疗的未来
- - '##'
  - 从出生到死亡的精准护理
- - '###'
  - 纳米技术
- - '###'
  - DNA 操作与基因治疗
- - '###'
  - 智能传感器
- - '###'
  - 生物打印
- - '##'
  - 脑机接口
- - '##'
  - 智能栖息地
- - '##'
  - 数字健康教育
- - '###'
  - 素养
- - '###'
  - 角色转变
- - '###'
  - 质量
- - '###'
  - 能力
- - '####'
  - 可及性与公平性
- - '####'
  - 新型培训形式
- - '###'
  - 学术界与产业界的合作
- - '##'
  - 总结
- - '#'
  - 7. 实践中的精准医疗
- - '##'
  - 通过数字工具为住院患者提供专科多学科体重管理
- - '###'
  - 目标
- - '###'
  - 方法
- - '###'
  - 个性化如何体现？
- - '###'
  - 结果
- - '###'
  - 讨论
- - '###'
  - 结论
- - '###'
  - 基于我们的证据进行拓展
- - '##'
  - 了解人们对数据的看法，以优化针对长期健康问题患者的专科足病服务
- - '###'
  - 目标
- - '###'
  - 方法
- - '###'
  - 结果
- - '###'
  - 讨论
- - '###'
  - 结论
- - '###'
  - 研究发现的影响
- - '##'
  - 针对 2 型糖尿病和糖尿病前期自我管理的数字干预措施评估
- - '###'
  - 目标
- - '###'
  - 方法
- - '###'
  - 结果
- - '###'
  - 讨论
- - '###'
  - 结论
- - '###'
  - 研究结果的影响
- - '##'
  - 基于语音的症状监测与基于人工智能的长期新冠患者康复
- - '###'
  - 背景
- - '###'
  - 目标
- - '###'
  - 实施计划
- - '###'
  - 风险
- - '###'
  - 评估
- - '###'
  - 潜在影响
- - '##'
  - 开发数字工具，支持儿童与青少年日常行为改变，迈向更健康的生活
- - '###'
  - 目标
- - '###'
  - 方法
- - '###'
  - 里程碑
- - '###'
  - 评估
- - '###'
  - 项目影响
- - '##'
  - 总结
