name: Real-Time IoT Imaging with Deep Neural Networks
name_cn: 深度神经网络实时物联网成像
slug: real-time-iot-imaging-with-deep-neural-networks
toc:
- - '#'
  - 引言
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 关于技术审校
- - '#'
  - 1. 入门指南
- - '##'
  - Visual Studio Code 入门指南
- - '##'
  - 运行你的第一个 Java 应用程序
- - '##'
  - 导入核心 Java 包
- - '##'
  - 调试课程
- - '###'
  - 添加断点
- - '###'
  - 逐步执行代码
- - '###'
  - 恢复执行
- - '###'
  - 监视表达式
- - '###'
  - 更改变量值
- - '###'
  - 总结
- - '#'
  - 2. 视频流中的对象检测
- - '##'
  - 棕褐色调入门：OpenCV Java 基础
- - '###'
  - 几个让事情更简单的文件…
- - '##'
  - OpenCV 入门 2：加载、调整大小和添加图片
- - '###'
  - 简单相加
- - '###'
  - 加权相加
- - '##'
  - 回到棕褐色效果
- - '##'
  - 寻找马塞尔：对象检测入门
- - '###'
  - 使用分类器在图片中查找猫脸
- - '####'
  - 什么是特征？
- - '####'
  - Marcel 在哪里？
- - '###'
  - 使用 Yolo 神经网络在图片中寻找猫脸
- - '#'
  - 3. 树莓派 4 上的视觉处理
- - '##'
  - 让树莓派“活”起来
- - '###'
  - 采购清单
- - '###'
  - 下载操作系统
- - '###'
  - 创建可启动 SD 卡
- - '####'
  - 连接线缆
- - '####'
  - 首次启动
- - '####'
  - 使用 `nmap` 查找你的树莓派
- - '####'
  - 轻松设置 SSH
- - '###'
  - 为远程使用设置 Visual Studio Code
- - '####'
  - 安装 Java OpenJDK
- - '####'
  - 安装 Java SDK 的替代方案
- - '####'
  - 检出 OpenCV/Java 模板
- - '#####'
  - 执行 Git 克隆
- - '#####'
  - 下载 Zip 文件
- - '#####'
  - 使用 Maven
- - '####'
  - 远程安装 Visual Code Java 扩展包
- - '####'
  - 运行第一个 OpenCV 示例
- - '##'
  - 改为在 Linux 或 AWS 虚拟机上运行
- - '##'
  - 捕获视频直播流
- - '###'
  - 播放视频
- - '##'
  - 在树莓派上分析视频流
- - '##'
  - 应用滤镜概述
- - '###'
  - 应用基础滤镜
- - '####'
  - 灰度滤镜
- - '####'
  - 边缘保留滤镜
- - '####'
  - Canny 边缘检测
- - '####'
  - 调试（再谈）
- - '####'
  - 组合过滤器
- - '###'
  - 应用类似 Instagram 的滤镜
- - '####'
  - 颜色映射
- - '####'
  - 阈值
- - '####'
  - 棕褐色
- - '####'
  - 卡通效果
- - '####'
  - 铅笔效果
- - '###'
  - 执行目标检测
- - '####'
  - 移除背景
- - '####'
  - 通过轮廓检测
- - '####'
  - 通过颜色检测
- - '####'
  - 通过 Haar 检测
- - '####'
  - 检测上的透明叠加层
- - '####'
  - 通过模板匹配进行检测
- - '####'
  - 通过 Yolo 进行检测
- - '#'
  - 5. 视觉与家庭自动化
- - '##'
  - Rhasspy 消息流
- - '##'
  - MQTT 消息队列
- - '##'
  - 安装 Mosquitto
- - '###'
  - 在 macOS 上
- - '###'
  - 在 Debian/Ubuntu 上
- - '###'
  - 使用 snap
- - '##'
  - 其他 MQTT 代理的比较
- - '##'
  - 命令行中的 MQTT 消息
- - '###'
  - 发送消息到树莓派
- - '##'
  - Java 中的 MQTT 消息传递
- - '###'
  - 依赖项设置
- - '###'
  - 发送基本 MQTT 消息
- - '###'
  - 模拟 Rhasspy 消息
- - '####'
  - JSON 趣谈
- - '#####'
  - 过度设计
- - '###'
  - 监听基本 MQTT 消息
- - '####'
  - 从 Java 向树莓派发送消息
- - '###'
  - 监听 MQTT JSON 消息
- - '##'
  - 语音与 Rhasspy 设置
- - '###'
  - 准备扬声器
- - '###'
  - 安装 Docker
- - '####'
  - 安装以下先决条件。
- - '####'
  - 下载并安装 Docker。
- - '####'
  - 授予 'pi' 用户运行 Docker 的权限。
- - '####'
  - 导入 Docker GPG 密钥。
- - '####'
  - 设置 Docker 仓库。
- - '####'
  - 修补并更新你的树莓派。
- - '####'
  - 启动 Docker 服务。
- - '####'
  - 验证 Docker 是否已安装并运行。
- - '####'
  - 你现在应该能看到一些关于版本、运行时等信息。
- - '###'
  - 使用 Docker 安装 Rhasspy
- - '###'
  - 启动 Rhasspy 控制台
- - '###'
  - Rhasspy 控制台
- - '###'
  - 第一条语音命令
- - '####'
  - 第一条命令，完整句子
- - '####'
  - 语音部分与测试您的意图
- - '####'
  - 微调意图
- - '#####'
  - 可选词
- - '###'
  - 添加备选方案
- - '###'
  - 让带槽位的意图更具可读性
- - '###'
  - 定义可复用的槽位
- - '##'
  - 设置：将意图放入队列
- - '##'
  - 设置：唤醒词
- - '###'
  - 创建高亮意图
- - '##'
  - 语音与实时目标检测
- - '###'
  - 简单设置：Origami + 语音
- - '###'
  - Origami 实时视频分析设置
- - '####'
  - 创建 Yolo 过滤器
- - '###'
  - 单独运行视频分析
- - '###'
  - 集成语音控制
- - '#'
  - 索引
- - '##'
  - A, B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T, U
- - '##'
  - V, W, X
- - '##'
  - Y, Z
