name: Artificial Intelligence in Medical Sciences and Psychology
name_cn: 医学科学与心理学中的人工智能
slug: artificial-intelligence-in-medical-sciences-and-psychology
toc:
- - '#'
  - 第1章 人工智能在医学与心理学中的应用导论
- - '##'
  - 本书背景
- - '##'
  - 本书的核心要点
- - '##'
  - 本书涵盖的人工智能子集
- - '##'
  - 本书结构
- - '##'
  - 本书使用的工具
- - '##'
  - Python 发行包
- - '##'
  - Anaconda 发行包
- - '###'
  - Jupyter Notebook
- - '##'
  - Python 库
- - '###'
  - 封装人工智能
- - '###'
  - 实现算法
- - '####'
  - 监督算法
- - '####'
  - 无监督算法
- - '###'
  - 人工神经网络
- - '##'
  - 结论
- - '#'
  - 第2章 利用神经网络识别疾病模式
- - '##'
  - 通过执行深度信念网络对心血管疾病诊断结果数据进行分类
- - '###'
  - 预处理心血管疾病诊断结果数据
- - '###'
  - 揭秘深度信念网络
- - '###'
  - 设计深度信念网络
- - '####'
  - ReLU 激活函数
- - '####'
  - Sigmoid 激活函数
- - '###'
  - 训练深度信念网络
- - '###'
  - 概述深度信念网络的预测结果
- - '####'
  - 考量深度神经网络的性能
- - '#####'
  - 训练和交叉验证中准确率随训练轮次的波动
- - '#####'
  - 训练和交叉验证中二元交叉熵损失随训练轮次的波动
- - '##'
  - 通过执行深度信念网络对糖尿病诊断结果数据进行分类
- - '###'
  - 执行深度信念网络对糖尿病诊断结果数据进行分类
- - '###'
  - 概述深度信念网络的预测结果
- - '###'
  - 评估深度神经网络的性能
- - '####'
  - 训练和交叉验证中跨 Epoch 的准确率波动
- - '####'
  - 训练与交叉验证中二元交叉熵损失随轮次的变化
- - '##'
  - 结论
- - '#'
  - 第3章 COVID-19 案例研究：考虑隐藏状态与模拟结果
- - '##'
  - 执行隐马尔可夫模型
- - '###'
  - 描述性分析
- - '##'
  - 执行高斯隐马尔可夫模型
- - '###'
  - 使用高斯隐马尔可夫模型分析美国新冠确诊病例的隐藏状态
- - '##'
  - 使用蒙特卡洛模拟方法模拟美国新冠确诊病例
- - '###'
  - 美国新冠确诊病例模拟结果
- - '##'
  - 结论
- - '#'
  - 第4章 使用神经网络进行癌症分割
- - '##'
  - 探索癌症
- - '##'
  - 探索皮肤癌
- - '###'
  - 通过执行 CNN 对患者皮肤癌结果进行分类
- - '####'
  - CNN 流水线
- - '####'
  - CNN 的架构结构
- - '#####'
  - 通过执行 CNN 对皮肤癌诊断图像数据进行分类
- - '#####'
  - 预处理训练用皮肤癌图像数据
- - '#####'
  - 预处理验证用皮肤癌图像数据
- - '#####'
  - 生成训练用皮肤癌诊断图像数据
- - '#####'
  - 调优训练用皮肤癌图像数据
- - '###'
  - 执行 CNN 对皮肤癌诊断图像数据进行分类
- - '####'
  - 评估 CNN 的性能
- - '#####'
  - 训练和交叉验证中准确率随轮次的波动
- - '#####'
  - 训练和交叉验证中稀疏分类交叉熵损失随轮次的波动
- - '##'
  - 乳腺癌的可见存在
- - '###'
  - 通过执行 CNN 对乳腺癌患者的超声扫描进行分类
- - '####'
  - 预处理验证集乳腺癌图像数据
- - '####'
  - 生成训练集乳腺癌诊断图像数据
- - '####'
  - 调优训练集乳腺癌图像数据
- - '###'
  - 执行 CNN 对乳腺癌诊断图像数据进行分类
- - '####'
  - 评估 CNN 的性能
- - '#####'
  - 训练与交叉验证中准确率随训练轮次的波动
- - '#####'
  - 训练与交叉验证中稀疏分类交叉熵损失随训练轮次的波动
- - '##'
  - 结论
- - '#'
  - 第5章 通过执行人工神经网络对磁共振成像和 X 光片进行建模
- - '##'
  - 脑肿瘤
- - '###'
  - MRI 检查流程
- - '###'
  - 预处理训练用 MRI 图像数据
- - '###'
  - 预处理验证用 MRI 图像数据
- - '###'
  - 生成训练用 MRI 图像数据
- - '###'
  - 调优训练用 MRI 图像数据
- - '###'
  - 执行 CNN 对 MRI 图像数据进行分类
- - '####'
  - 评估 CNN 的性能
- - '#####'
  - 训练与交叉验证中准确率随周期的波动
- - '#####'
  - 训练与交叉验证中稀疏分类交叉熵损失随周期的波动
- - '##'
  - 肺炎
- - '###'
  - X 射线成像流程
- - '####'
  - 通过执行 CNN 对 X 射线进行分类
- - '#####'
  - 处理 X 射线图像数据
- - '#####'
  - 生成训练用胸部 X 射线图像数据
- - '#####'
  - 预处理验证胸部 X 光图像数据
- - '#####'
  - 生成验证胸部 X 光图像数据
- - '#####'
  - 调优训练胸部 X 光图像数据
- - '###'
  - 执行 CNN 以分类胸部 X 光图像数据
- - '####'
  - 评估 CNN 的性能
- - '#####'
  - 训练和交叉验证中准确率随周期的波动
- - '#####'
  - 训练和交叉验证中稀疏分类交叉熵损失随周期的波动
- - '##'
  - 结论
- - '#'
  - 第6章 COVID-19 CT 扫描分割案例研究
- - '##'
  - 简单的计算机断层扫描流程
- - '###'
  - 预处理训练用的 COVID-19 数据
- - '###'
  - 预处理验证用的 COVID-19 CT 扫描数据
- - '###'
  - 生成训练用的 COVID-19 CT 扫描数据
- - '###'
  - 调优训练用的 COVID-19 CT 扫描数据
- - '##'
  - 执行 CNN 对 COVID-19 CT 扫描数据进行分类
- - '###'
  - 评估 CNN 的性能
- - '####'
  - 训练和交叉验证中准确率随周期的波动
- - '####'
  - 训练和交叉验证中稀疏分类交叉熵损失随周期的波动
- - '##'
  - 结论
- - '#'
  - 第7章 临床试验数据建模
- - '##'
  - 临床试验
- - '##'
  - 生存分析概述
- - '##'
  - 本章背景
- - '##'
  - 探索 Nelson-Aalen 加性模型
- - '###'
  - 描述性分析
- - '###'
  - 实现相关性关系
- - '###'
  - 概述生存表
- - '###'
  - 执行 Nelson-Aalen 加法模型
- - '####'
  - 概述 Nelson-Aalen 加法模型的置信区间
- - '####'
  - 识别生存风险
- - '####'
  - 识别累积生存风险
- - '####'
  - 基线生存风险
- - '##'
  - 结论
- - '#'
  - 第8章 医疗记录分类
- - '##'
  - 医疗记录
- - '##'
  - 本章背景
- - '##'
  - 使用线性判别分析进行分类
- - '##'
  - 描述性分析
- - '##'
  - 预处理医疗记录数据
- - '###'
  - 执行正则表达式
- - '###'
  - 执行词向量化
- - '##'
  - 执行线性判别分析模型以对患者病历进行分类
- - '###'
  - 评估线性判别分析模型的性能
- - '##'
  - 结论
- - '#'
  - 第9章 心理学案例：人格维度的因子分析与聚类
- - '##'
  - 人格维度
- - '##'
  - 问卷
- - '##'
  - 李克特量表
- - '##'
  - 量表信度
- - '###'
  - 斯皮尔曼-布朗信度检验策略
- - '###'
  - 执行克朗巴赫信度检验策略
- - '##'
  - 执行因子模型
- - '###'
  - 执行巴特利特球形度检验
- - '###'
  - 执行 Kaiser-Meyer-Olkin 检验
- - '###'
  - 使用碎石图判断 K 值
- - '###'
  - 执行特征值旋转
- - '####'
  - 最大方差旋转
- - '###'
  - 辨别比例方差与累积方差
- - '##'
  - 执行聚类分析
- - '###'
  - 执行主成分分析
- - '###'
  - 返回 K-Means 标签
- - '###'
  - 识别 K-Means 聚类中心
- - '##'
  - 结论
- - '#'
  - 参考文献
- - '#'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D, E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H, I, J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N, O
- - '###'
  - P, Q, R
- - '###'
  - S, T, U, V, W
- - '###'
  - X, Y, Z
