name: Keeping Your AI Under Control
name_cn: AI 控制指南
slug: keeping-your-ai-under-control
toc:
- - '#'
  - 第一部分：人工智能的未来状态
- - '##'
  - 评估即将到来的变革
- - '#'
  - 1. 2020 年后的人工智能
- - '##'
  - 我们最近已换挡提速
- - '##'
  - 人工智能已取得长足进展
- - '##'
  - 但它尚未无处不在
- - '###'
  - 最终用户如何看待 AI？
- - '###'
  - 商业用户在想什么？
- - '##'
  - 未来将如何？
- - '###'
  - 平衡之道
- - '##'
  - 从过去的失败中汲取教训
- - '###'
  - 当微软聊天机器人在社交网络上变成纳粹
- - '###'
  - 当亚马逊的当日达服务造成种族差异
- - '###'
  - 当优步的自动驾驶汽车撞死行人
- - '###'
  - 当灯泡发起拒绝服务攻击，瘫痪整个智能家居
- - '###'
  - 一家澳大利亚电信公司如何浪费了数百万美元
- - '###'
  - 这些失败案例有共同点
- - '###'
  - 关键经验教训
- - '##'
  - 理解人工智能风险及其影响
- - '###'
  - 马斯克、霍金、盖茨——他们都说过！
- - '##'
  - 我们正遭受认知缺失之苦
- - '###'
  - 许多人工智能系统如同垃圾
- - '###'
  - 人工智能缺乏平衡计分卡
- - '##'
  - AI 知道“怎么做”，却不懂“为什么”
- - '##'
  - AI 没有良知
- - '##'
  - 失业并非真正的问题
- - '##'
  - 正确的人工智能落入错误之手的风险
- - '###'
  - 灰色脑细胞——用进废退
- - '###'
  - 人类计划，科技发笑
- - '#'
  - 第二部分 预防
- - '##'
  - 主动规避人工智能风险
- - '#'
  - 4. 评估人工智能解决方案的风险
- - '##'
  - 从正确的假设开始
- - '###'
  - Acme Solutions 的奇特案例
- - '##'
  - 解决方案是否针对了有效的根本原因？
- - '##'
  - 解决方案是否得到了正确训练？
- - '##'
  - 解决方案是否考虑了所有场景？
- - '##'
  - 是否有优雅停止的选项？
- - '##'
  - 解决方案是否可解释且可审计？
- - '##'
  - 解决方案是否针对你的用例量身定制？
- - '##'
  - 解决方案是否具备处理漂移的能力？
- - '##'
  - AI 解决方案评估问卷
- - '###'
  - 全面评估，掌控全局
- - '##'
  - 降低 AI 解决方案部署风险
- - '###'
  - 确保长期战略已明确
- - '##'
  - 正确定义你的问题
- - '##'
  - 验证所有根本原因
- - '###'
  - 应用反向推理
- - '###'
  - 应用 MECE 原则
- - '##'
  - 规划业务连续性
- - '##'
  - 明确责任归属
- - '##'
  - 确保基础设施的可用性
- - '##'
  - 设定成功的目标指标
- - '##'
  - 定义验收标准
- - '##'
  - 构建执行能力
- - '##'
  - 处理安全与合规问题
- - '##'
  - 与你的其他系统集成
- - '##'
  - AI 解决方案部署问卷
- - '###'
  - 提出正确的问题是必须的
- - '#'
  - 6. 优秀 AI 落入不良用户之手
- - '##'
  - 糟糕的用户对我们意味着什么？
- - '###'
  - 创意型用户
- - '###'
  - 恶作剧型用户
- - '###'
  - 蓄意（恶意）用户
- - '###'
  - 卢德分子
- - '###'
  - 糟糕用户 vs. 无能用户
- - '###'
  - 通过变革管理来应对
- - '##'
  - 教育用户以实现更好的采用
- - '###'
  - 检查性能与差距
- - '##'
  - 切勿忽视现场走访
- - '##'
  - 处理用户测试与反馈
- - '##'
  - 建立 HAIR 部门
- - '##'
  - 用户就绪度问卷
- - '##'
  - 掌握技术要素对 AI 来说还不够
- - '#'
  - 7. 风险缓解的系统性方法
- - '##'
  - AI 风险管理的核心原则
- - '##'
  - AI 风险的常见促成因素
- - '##'
  - 事前验尸分析
- - '###'
  - 事前验尸分析的关键部分
- - '###'
  - 关于评级的更多信息
- - '###'
  - 利用分析结果
- - '###'
  - 特定行业考量
- - '###'
  - 结论
- - '#'
  - 8. 精心教导，严格测试
- - '##'
  - AI 如何学习
- - '###'
  - 机器学习类型
- - '##'
  - 训练中应避免的五个错误
- - '###'
  - 没有足够的数据进行训练
- - '###'
  - 未清理和验证数据集
- - '###'
  - 数据分布不够广泛
- - '###'
  - 忽略“险些失误”与“人工干预”
- - '###'
  - 混淆相关性与因果关系
- - '##'
  - 用测试来补充训练
- - '##'
  - AI 测试不是软件测试
- - '##'
  - AI 测试的核心顺序
- - '###'
  - 测试概念漂移
- - '###'
  - 测试交互问题
- - '###'
  - 它可以成为你信任的基础
- - '#'
  - 第三部分 缓解措施
- - '##'
  - 最小化风险的影响
- - '#'
  - 红队：AI 监督之道
- - '##'
  - 什么是红队？
- - '##'
  - 监督 AI 的必要性
- - '##'
  - 为什么不使用对抗性 AI 测试？
- - '##'
  - 唯有 AI 监督才能暴露这一点
- - '###'
  - 突出统计谬误
- - '###'
  - 检测概念漂移
- - '###'
  - 探索黑箱内部
- - '##'
  - 组建你的红队
- - '###'
  - 红队五大核心技能
- - '###'
  - 内部组建还是外包
- - '##'
  - 红队的目标
- - '##'
  - 红队不是为了测试防御
- - '##'
  - 红队已就绪，下一步是什么？
- - '#'
  - 10. 处理残余风险
- - '##'
  - 什么是残余风险？
- - '##'
  - 现有选项与局限性
- - '##'
  - 人工智能保险是否必要？
- - '###'
  - 人工智能让投资者损失惨重
- - '###'
  - 高风险的患者数字助手
- - '##'
  - 法规正在酝酿中
- - '##'
  - AI 保险面临的挑战
- - '###'
  - 共同池
- - '###'
  - 公平性
- - '###'
  - 基于云的 AI 的可保性
- - '###'
  - 归因
- - '##'
  - 什么可能让它奏效？
- - '##'
  - 为什么执着于 AI 保险？
- - '##'
  - 买保险与否，你都能过得更好
- - '#'
  - 11. 当与新兴技术打交道时
- - '##'
  - 我们又在犯同样的错误吗？
- - '##'
  - 劣质解决方案的泛滥
- - '##'
  - 一种好的方法
- - '###'
  - 我们必须保持怀疑
- - '###'
  - 我们绝不能超速
- - '###'
  - 我们必须坚持设置紧急停止开关
- - '###'
  - 我们必须要求质量
- - '###'
  - 我们必须寻求透明度
- - '###'
  - 我们必须寻求可解释性
- - '###'
  - 我们必须追求简洁
- - '###'
  - 我们必须追求问责制
- - '###'
  - 我们必须教育所有相关方
- - '###'
  - 我们必须认真对待用户反馈
- - '###'
  - 我们必须优先预防而非修复
- - '##'
  - 负责任地使用 AI
- - '##'
  - 理智是关键！
- - '###'
  - 索引
- - '####'
  - A
- - '####'
  - B
- - '####'
  - C
- - '####'
  - D
- - '####'
  - E
- - '####'
  - F
- - '####'
  - G
- - '####'
  - H
- - '####'
  - I, J
- - '####'
  - K
- - '####'
  - L
- - '####'
  - M
- - '####'
  - N
- - '####'
  - O
- - '####'
  - P, Q
- - '####'
  - R
- - '####'
  - S
- - '####'
  - T
- - '####'
  - U, V, W, X, Y, Z
