name: The AI-Powered Workplace
name_cn: AI赋能职场
slug: the-ai-powered-workplace
toc:
- - '#'
  - 书签
- - '#'
  - 引言
- - '##'
  - 理解人工智能
- - '#'
  - 人工智能在工作场所的应用
- - '#'
  - 构建你的人工智能驱动工作场所
- - '#'
  - 致谢
- - '##'
  - 关于作者
- - '#'
  - 第一部分：理解人工智能
- - '#'
  - 第1章 追寻会思考的机器
- - '##'
  - 新研究领域的诞生
- - '##'
  - 实际应用
- - '##'
  - 人工智能转入地下
- - '#'
  - 第2章 新的永恒之春
- - '##'
  - 数据洪流
- - '##'
  - 原始处理能力与更优算法
- - '###'
  - AI 的民主化
- - '##'
  - 展望未来
- - '#'
  - 第3章 什么是 AI？
- - '##'
  - AI 的隐身术
- - '##'
  - 通用 AI vs. 特定领域 AI
- - '#'
  - 第4章 基于智能体的 AI 视角
- - '##'
  - 智能体
- - '###'
  - 主动型智能体
- - '###'
  - 自我导向型智能体
- - '###'
  - 自主智能体
- - '###'
  - 会学习的智能体
- - '###'
  - 智能体社区
- - '##'
  - 超越智能
- - '#'
  - 第5章 构建 AI 驱动的应用
- - '##'
  - 人工智能需要什么
- - '##'
  - 模型驱动与数据驱动的 AI
- - '###'
  - 模型驱动 AI
- - '###'
  - 所以牛顿定律也是人工智能！？
- - '###'
  - 数据驱动的人工智能
- - '####'
  - 站在数据的肩膀上
- - '####'
  - 给我足够的数据和正确的算法，我就能撬动世界
- - '##'
  - 技术、能力与应用
- - '###'
  - 专家与机器协同工作
- - '#'
  - 第6章 核心人工智能技术
- - '##'
  - 模型驱动技术
- - '###'
  - 知识表示
- - '####'
  - 逻辑
- - '####'
  - 规划
- - '##'
  - 数据驱动技术
- - '###'
  - 监督学习
- - '####'
  - 收集和准备数据
- - '####'
  - 选择机器学习算法、训练与微调
- - '####'
  - 预测
- - '###'
  - 无监督学习
- - '###'
  - 强化学习
- - '###'
  - 深度学习与人工神经网络
- - '##'
  - 从技术到能力
- - '#'
  - 第7章 核心人工智能能力
- - '##'
  - 语言
- - '###'
  - 语音识别
- - '###'
  - 自然语言处理
- - '####'
  - 分析与实体提取
- - '####'
  - 分类
- - '####'
  - 意图提取
- - '####'
  - 翻译
- - '###'
  - 自然语言生成
- - '##'
  - 视觉
- - '##'
  - 定制能力
- - '##'
  - 从能力到应用
- - '#'
  - 第二部分 人工智能在工作场所的应用
- - '#'
  - 第8章 数字化工作场所
- - '##'
  - 什么是数字化工作场所？
- - '##'
  - 排版后的内容
- - '##'
  - 理解你的数字工作空间
- - '###'
  - 人员与团队
- - '####'
  - 探索人员数据
- - '###'
  - 流程
- - '####'
  - 绘制流程
- - '###'
  - 工具
- - '####'
  - 揭开工具的神秘面纱
- - '##'
  - 下一站
- - '#'
  - 第9章 人工智能即新用户界面
- - '##'
  - 超越“指向点击”
- - '##'
  - 对话式界面
- - '###'
  - 语音
- - '###'
  - 文本
- - '##'
  - 增强现实与虚拟现实
- - '#'
  - 第10章 对话式协作平台
- - '##'
  - 更佳的用户体验是竞争优势
- - '##'
  - 对话式协作平台
- - '###'
  - 核心功能
- - '####'
  - 人员
- - '####'
  - 在线状态
- - '####'
  - 对话
- - '###'
  - 公告群组
- - '###'
  - 兴趣与爱好群组
- - '###'
  - 共享群组
- - '###'
  - 文档交换
- - '###'
  - 搜索
- - '####'
  - 集成
- - '##'
  - 自定义对话平台
- - '###'
  - 用于审计的对话工具
- - '##'
  - 你的组织操作系统
- - '#'
  - 第11章 对话式应用
- - '##'
  - 从聊天机器人到对话式应用
- - '##'
  - 对话式应用的结构
- - '##'
  - 规划对话式应用
- - '###'
  - 能力范围
- - '###'
  - 交互风格
- - '###'
  - 处理复杂问题描述
- - '###'
  - 上下文
- - '####'
  - 平台
- - '####'
  - 分析与改进
- - '##'
  - 对话应用的使用场景
- - '###'
  - 智能通知
- - '####'
  - 基础通知
- - '###'
  - 主动通知
- - '###'
  - 团队通知
- - '##'
  - 监控关键数据
- - '###'
  - 连接数据
- - '###'
  - 上下文数据
- - '####'
  - 可解释的数据
- - '###'
  - 支持与协作
- - '####'
  - 自动化服务台
- - '####'
  - 捕获决策与完成任务
- - '####'
  - 捕获与分享流程知识
- - '##'
  - 组织协作运营
- - '#'
  - 第三部分：构建你的 AI 驱动型工作场所
- - '#'
  - 第12章 从数据到理解
- - '##'
  - 赋予数据以目的
- - '##'
  - 制定数据策略——从理论到实践
- - '###'
  - 挑战
- - '###'
  - 支持沟通与协作的数据策略
- - '####'
  - 一种实现连接与聚合的数据策略
- - '####'
  - 通过标准统一信息的策略
- - '####'
  - 迭代改进工具的数据策略
- - '##'
  - 从数据到理解
- - '#'
  - 第13章 定义人工智能战略
- - '##'
  - AI 战略的实用方法
- - '###'
  - 原则
- - '####'
  - 大处着眼，现实起步，适度扩展
- - '#####'
  - 大处着眼
- - '#####'
  - 现实起步（并逐步演进）
- - '#####'
  - 适度扩展
- - '####'
  - 切实成果至关重要
- - '####'
  - 人工智能战略无关人工智能
- - '####'
  - 不存在需要通过的“真正”人工智能测试
- - '####'
  - 确定你是否真的想要它
- - '###'
  - 方法
- - '####'
  - 找到你的位置
- - '#####'
  - 我们目前如何解决问题？
- - '######'
  - 揭示真实流程
- - '######'
  - 用人类模拟流程
- - '######'
  - 不要忽视经验
- - '#####'
  - 我们拥有哪些数据？
- - '######'
  - 一星——数据以任何格式可供使用
- - '######'
  - 二星——数据以结构化格式可用
- - '######'
  - 三星——数据以被充分理解的结构化格式可用
- - '######'
  - 四星——通过有文档记录的 API 获取数据
- - '######'
  - 五星——跨数据集链接数据以提供上下文
- - '####'
  - 连接各项活动
- - '####'
  - 构建你的路线图
- - '#####'
  - 雇佣内置 AI 的工具
- - '#####'
  - 用 AI 构建
- - '#####'
  - 构建 AI
- - '##'
  - AI 无处不在
- - '#'
  - 第14章 AI 驱动应用的伦理
- - '##'
  - 自动化决策的后果
- - '##'
  - 合乎道德的 AI 系统指南
- - '###'
  - 值得信赖的人工智能
- - '####'
  - 合法的人工智能
- - '####'
  - 合乎伦理的人工智能
- - '##'
  - 稳健人工智能
- - '##'
  - 合乎道德的人工智能应用
- - '#'
  - 第15章 尾声
- - '##'
  - 2035 年的一天工作
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
