name: Practical Natural Language Processing with Python
name_cn: Python 自然语言处理实战指南
slug: practical-natural-language-processing-with-python
toc:
- - '#'
  - 基于 Python 的实用自然语言处理
- - '#'
  - 目录
- - '#'
  - 第 1 章 数据类型
- - '##'
  - 搜索
- - '##'
  - 评论
- - '###'
  - 亚马逊评论示例
- - '###'
  - 亚马逊评论示例（长篇）
- - '##'
  - 社交媒体帖子/博客
- - '###'
  - Google Pixel 3 相关推文分析
- - '##'
  - 聊天数据
- - '###'
  - 个人聊天
- - '###'
  - 商业聊天与语音通话数据
- - '##'
  - 短信数据
- - '##'
  - 内容数据
- - '##'
  - IVR 语音数据
- - '##'
  - 数据中的有用信息
- - '#'
  - 第 2 章 客户服务中的自然语言处理
- - '##'
  - 语音通话
- - '##'
  - 聊天
- - '##'
  - 用户调查数据
- - '##'
  - 工单数据
- - '##'
  - 电子邮件数据
- - '##'
  - 客户之声
- - '###'
  - 意图挖掘
- - '##'
  - 通过高频词理解意图
- - '##'
  - 词云
- - '##'
  - 将列表连接成字符串，作为词云的输入
- - '###'
  - 返回的词云对象及其相对得分
- - '##'
  - 分类主题的规则
- - '##'
  - 文本排版
- - '###'
  - 代码清单 2-7. 文本挖掘规则
- - '###'
  - 代码清单 2-8.
- - '###'
  - 图 2-4. 文本挖掘规则输出
- - '###'
  - 代码清单 2-9.
- - '###'
  - 图 2-5. 分配主题
- - '###'
  - 代码清单 2-10. Scikit Learn 中的准确率方法
- - '##'
  - 排版后的文本
- - '##'
  - 使用机器学习的监督学习
- - '##'
  - 获取手动标记数据
- - '##'
  - 词语分词
- - '##'
  - 词项-文档矩阵
- - '###'
  - tokenize all rows
- - '##'
  - 图 2-7 中的数据是语料库中所有文档生成的词元输出结果。现在请参阅代码清单 2-15、代码清单 2-16 以及图 2-8。
- - '###'
  - 代码清单 2-15
- - '###'
  - 图 2-8 词项-文档矩阵
- - '###'
  - 代码清单 2-16
- - '###'
  - 表 2-5 计算 TF-IDF
- - '##'
  - 数据归一化
- - '##'
  - 替换特定模式
- - '##'
  - 识别问题行
- - '##'
  - 热门客户查询
- - '##'
  - 热门 CSAT 驱动因素
- - '##'
  - 使用次坐标轴绘制不同 Y 轴的图表
- - '##'
  - 主要 NPS 驱动因素
- - '###'
  - 客服人员属性
- - '##'
  - 用于客户服务代表的共情语句
- - '##'
  - 销售对话洞察
- - '##'
  - 销售对话中的热门产品
- - '##'
  - 未购买原因
- - '##'
  - 调查评论分析
- - '##'
  - 挖掘语音转录文本
- - '##'
  - 声学模型
- - '##'
  - 语言模型
- - '###'
  - 打印字符
- - '#'
  - 第 3 章 在线评论中的自然语言处理
- - '##'
  - 情感分析
- - '##'
  - 情绪挖掘
- - '##'
  - 方法一：基于词典的方法
- - '##'
  - 方法 2：基于规则的方法
- - '###'
  - 观察结果 1
- - '###'
  - 观察结果 2
- - '###'
  - 观察 3
- - '###'
  - 观察 4
- - '##'
  - 总体得分
- - '###'
  - 实现观察结果
- - '####'
  - 预处理
- - '####'
  - 增强词与否定词（观察结果 2 和观察结果 3）
- - '###'
  - 代码清单 3-13
- - '##'
  - 感叹号（观察点 4）
- - '###'
  - 代码清单 3-14. 检查感叹号
- - '##'
  - 对 `full_txt` 和 `Summary` 的评估（观察点 1）
- - '###'
  - 代码清单 3-15
- - '###'
  - 代码清单 3-16. 评估 `t3` 数据框
- - '####'
  - 计算总体得分
- - '####'
  - 最终判定
- - '####'
  - 记录中间值以便排查问题
- - '##'
  - 优化代码
- - '###'
  - 情感分析库
- - '##'
  - 方法 3：基于机器学习的方法（神经网络）
- - '##'
  - 语料库特征
- - '##'
  - 构建神经网络
- - '##'
  - 编译模型
- - '##'
  - 改进方向
- - '##'
  - 属性提取
- - '###'
  - 步骤 1：使用正则表达式进行标准化
- - '###'
  - 步骤 2：提取名词形式
- - '###'
  - 步骤 3：创建映射文件
- - '##'
  - 设备规格与自然语言处理
- - '##'
  - 设备规格
- - '###'
  - 获取顶部词汇
- - '###'
  - 步骤 4：将每条评论映射到属性
- - '###'
  - 步骤 5：分析品牌
- - '#'
  - 第 4 章 银行、金融服务和保险业中的自然语言处理
- - '##'
  - 自然语言处理在欺诈中的应用
- - '##'
  - 方法一：使用现有库
- - '###'
  - 命名实体识别示例
- - '##'
  - 方法二：提取名词短语
- - '##'
  - 方法 3：训练你自己的模型
- - '##'
  - NLP 中的词嵌入
- - '##'
  - Word2Vec
- - '###'
  - CBOW
- - '##'
  - 其他 word2vec 库
- - '##'
  - 将词嵌入应用于监督学习
- - '###'
  - 方法 3 – 方法 1
- - '###'
  - 方法 3 – 方法 2
- - '##'
  - 编译模型
- - '##'
  - 应用模型
- - '##'
  - 步骤 7：获取负面语料库
- - '##'
  - 步骤 8：验证 2.2 万数据集
- - '###'
  - 步骤 8.1：在另一个笔记本中读取你的 `only_ner_tagged.csv`
- - '###'
  - 步骤 8.2：读取步骤 7 生成的文件
- - '###'
  - 步骤 8.3：处理列并将文件合并到单个数据框中
- - '###'
  - 步骤 8.4：向量化列表
- - '###'
  - 步骤 8.5：余弦相似度
- - '###'
  - 步骤 8.6：如果余弦相似度大于 0.6，则视为匹配
- - '###'
  - 步骤 8.4（续）：与原始数据集匹配
- - '###'
  - 步骤 8.5：回到起点
- - '##'
  - 步骤 9：识别包含候选组织的原始文章
- - '##'
  - 步骤 10：获取句子的情感
- - '##'
  - 自然语言处理在银行业、金融服务和保险业的其他用例
- - '##'
  - 短信数据
- - '##'
  - 银行中的自然语言生成
- - '#'
  - 第 5 章 虚拟助手中的自然语言处理
- - '##'
  - 数据集
- - '##'
  - 实现架构
- - '##'
  - 编码器-解码器训练
- - '##'
  - 编码器输出
- - '##'
  - 解码器输入
- - '##'
  - 预处理
- - '##'
  - 双向 LSTM
- - '###'
  - 编码器
- - '###'
  - 解码器
- - '##'
  - BERT
- - '##'
  - 语言模型与微调
- - '##'
  - BERT 概述
- - '###'
  - Transformer 架构
- - '###'
  - Q 向量、K 向量、V 向量、Q·K
- - '###'
  - Softmax、Softmax * 求和
- - '###'
  - 值
- - '####'
  - 思考过程
- - '##'
  - 为分类器微调 BERT
- - '##'
  - 构建对话机器人的更多细节
- - '###'
  - 单轮对话 vs. 多轮对话
- - '##'
  - 多语言机器人
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G, H
- - '##'
  - I, J, K
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '#'
  - 关于技术审校者
- - '#'
  - 致谢
- - '#'
  - 引言
