name: How Algorithms Create and Prevent Fake News
name_cn: 算法如何制造与防范假新闻
slug: how-algorithms-create-and-prevent-fake-news
toc:
- - '#'
  - 引言
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 页面浏览量的危害
- - '##'
  - 故事的传播
- - '#'
  - 博客经济学
- - '#'
  - 从底层崛起
- - '#'
  - 排版后的内容
- - '##'
  - 历史背景
- - '#'
  - 虚假新闻贩子的典型案例
- - '##'
  - 可靠地方新闻的消亡
- - '#'
  - 摘要
- - '#'
  - 2. 由计算机精心打造
- - '##'
  - 合成照片
- - '##'
  - 自动化标题
- - '##'
  - 撰写整篇文章
- - '##'
  - 温斯顿对可疑用户的调查
- - '##'
  - 机器学习速成课
- - '###'
  - 监督学习
- - '###'
  - 深度学习
- - '###'
  - GPT-3
- - '###'
  - 深度伪造照片生成
- - '##'
  - 算法检测
- - '##'
  - 总结
- - '#'
  - 3. 深度伪造骗局
- - '##'
  - 敲响警钟
- - '##'
  - 浅层伪造简史
- - '##'
  - 浅伪造与深度伪造的起源
- - '###'
  - 深度伪造的起源
- - '###'
  - 一些技术细节
- - '####'
  - 不同类型的深度伪造
- - '##'
  - 政治领域中的深度伪造
- - '##'
  - 排版后的文本
- - '##'
  - 检测深度伪造
- - '##'
  - 对抗视觉虚假信息的不同方法
- - '###'
  - 法律监管
- - '##'
  - 驳回有效证据
- - '##'
  - 总结
- - '#'
  - 自动播放的独裁者
- - '##'
  - 日益增长的担忧之声
- - '##'
  - YouTube 背景介绍
- - '##'
  - 算法的发展
- - '###'
  - 2012 年：从观看次数到观看时长
- - '####'
  - 2015 年：基于深度学习的重新设计
- - '####'
  - 2018 年：深度强化学习
- - '####'
  - 此外……
- - '##'
  - 巴西的 YouTube
- - '###'
  - YouTube 对巴西人的政治影响
- - '####'
  - 极右翼如何受到青睐
- - '####'
  - 阴谋论盛行
- - '####'
  - 玩这场游戏
- - '##'
  - YouTube 在美国
- - '###'
  - 在 2020 年煽动选举风波
- - '###'
  - 美国媒体格局中的 YouTube
- - '###'
  - 研究算法
- - '##'
  - 皮尤的随机漫步
- - '##'
  - 查斯洛的政治推荐数据
- - '##'
  - 分析这八千个视频时
- - '###'
  - 追踪评论者
- - '###'
  - 矛盾的结果
- - '##'
  - 纵向研究
- - '##'
  - 观看历史的作用
- - '##'
  - 另一次算法失误
- - '##'
  - 审核 YouTube 上的内容
- - '##'
  - 总结与结论
- - '#'
  - 5. 推诿与测谎仪
- - '##'
  - 测谎仪的历史
- - '###'
  - 马斯顿及其发明
- - '###'
  - 步入法庭
- - '###'
  - 从血压到测谎仪
- - '###'
  - 决心寻找用途
- - '###'
  - 持久的质疑
- - '##'
  - 测谎仪遇上人工智能
- - '###'
  - 眼中的谎言
- - '###'
  - 深度学习微表情
- - '###'
  - 从视频到音频和文本
- - '##'
  - 假新闻
- - '#'
  - 摘要
- - '#'
  - 6. 倾向谷歌
- - '##'
  - 背景铺垫
- - '##'
  - 谷歌地图
- - '###'
  - 虚假商家信息
- - '##'
  - Google 地图上的虚假商家信息
- - '##'
  - Google 图片
- - '##'
  - 排版后的文本
- - '##'
  - Google Autocomplete
- - '###'
  - 暗示仇恨
- - '###'
  - 建议虚假新闻
- - '##'
  - Google 新闻
- - '##'
  - Google 搜索
- - '###'
  - 排名至关重要
- - '####'
  - 算法使用的信号
- - '####'
  - 精选摘要
- - '####'
  - 屏蔽搜索结果
- - '####'
  - BERT
- - '####'
  - 提升优质新闻质量
- - '##'
  - 总结
- - '#'
  - 7. 广告的贪婪
- - '##'
  - Google 广告与假新闻
- - '###'
  - 2017 年报告
- - '###'
  - 2019 年报告
- - '###'
  - 2021 年报告
- - '###'
  - 谷歌广告中的种族主义
- - '###'
  - Facebook 广告与种族主义
- - '###'
  - 攻击性广告类别
- - '###'
  - 种族歧视性排除广告
- - '###'
  - 算法可以助益而非伤害
- - '###'
  - 非法排除性广告的延续
- - '###'
  - 法律诉讼
- - '###'
  - 算法偏见
- - '###'
  - 企业进展
- - '###'
  - 假新闻何去何从？
- - '##'
  - 总结性思考
- - '##'
  - 总结
- - '#'
  - 8. 社交传播
- - '##'
  - 背景铺垫
- - '###'
  - 主要依赖社交媒体的人群
- - '###'
  - 社交媒体算法
- - '##'
  - 排版后的文本
- - '###'
  - Facebook 的问题与反应
- - '##'
  - 为什么 QAnon 如此棘手
- - '##'
  - QAnon 与社交媒体管控的演变
- - '##'
  - 量化假新闻的传播
- - '##'
  - Twitter 与 2016 年大选
- - '##'
  - 谎言比真相传播得更快、更深
- - '###'
  - 2020 年大选
- - '##'
  - 算法如何发挥作用
- - '###'
  - Facebook 的机器学习审核机制
- - '###'
  - Twitter 的机器人检测
- - '###'
  - 2020 年大选及其余波
- - '###'
  - 其他方面？
- - '##'
  - 算法如何提供帮助
- - '###'
  - 结构性方法
- - '###'
  - 虚假新闻检测
- - '###'
  - 算法调整
- - '#'
  - 第 230 条
- - '#'
  - 结语
- - '##'
  - 总结
- - '#'
  - 9. 真相的工具
- - '##'
  - 在线工具
- - '###'
  - Full Fact
- - '###'
  - Logically
- - '###'
  - Squash
- - '###'
  - FakerFact
- - '###'
  - 滑铁卢大学的立场检测
- - '###'
  - SciFact
- - '###'
  - Diffbot
- - '###'
  - Twitter 机器人检测
- - '###'
  - Google 反向图片搜索
- - '###'
  - 其他工具
- - '##'
  - 大型平台上的事实核查
- - '###'
  - 谷歌
- - '###'
  - YouTube
- - '###'
  - Facebook
- - '###'
  - Twitter
- - '##'
  - 总结
