name: Computer Vision Projects with PyTorch
name_cn: PyTorch 计算机视觉项目实战
slug: computer-vision-projects-with-pytorch
toc:
- - '#'
  - 目录
- - '##'
  - 引言
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '#'
  - 1. 计算机视觉的构建模块
- - '##'
  - 1.1 什么是计算机视觉
- - '###'
  - 1.1.1 应用
- - '###'
  - 1.1.2 分类
- - '###'
  - 1.1.3 目标检测与定位
- - '####'
  - 1.1.3.1 图像分割
- - '####'
  - 1.1.3.2 异常检测
- - '####'
  - 1.1.3.3 视频分析
- - '###'
  - 1.1.4 通道
- - '###'
  - 1.1.5 卷积神经网络
- - '###'
  - 1.1.6 感受野
- - '###'
  - 1.1.7 局部感受野
- - '###'
  - 1.1.8 全局感受野
- - '###'
  - 1.1.9 池化
- - '####'
  - 1.1.9.1 最大池化
- - '####'
  - 1.1.9.2 平均池化
- - '###'
  - 1.1.10 全局平均池化
- - '###'
  - 1.1.11 计算：特征图与感受野
- - '####'
  - 1.1.11.1 卷积核
- - '####'
  - 1.1.11.2 步长
- - '####'
  - 1.1.11.3 池化
- - '####'
  - 1.1.11.4 填充
- - '####'
  - 1.1.11.5 输入与输出
- - '####'
  - 1.1.11.6 感受野的计算
- - '###'
  - 1.1.12 理解 CNN 架构类型
- - '####'
  - 1.1.12.1 理解架构类型
- - '####'
  - 1.1.12.2 AlexNet
- - '###'
  - 1.1.13 VGG
- - '###'
  - 1.1.14 ResNet
- - '##'
  - 1.2 Inception 架构
- - '##'
  - 1.3 深度学习模型技术实践
- - '###'
  - 1.3.1 批量归一化
- - '####'
  - 1.3.1.1 丢弃法
- - '####'
  - 1.3.1.2 数据增强技术
- - '###'
  - 1.3.2 PyTorch 简介
- - '####'
  - 1.3.2.1 安装
- - '###'
  - 1.3.3 基础入门
- - '##'
  - 1.4 总结
- - '#'
  - 2. 图像分类
- - '##'
  - 2.1 涵盖主题
- - '###'
  - 2.1.1 定义问题
- - '##'
  - 2.2 方法概述
- - '##'
  - 2.3 创建图像分类流水线
- - '###'
  - 2.3.1 第一个基础模型
- - '####'
  - 2.3.1.1 数据
- - '####'
  - 2.3.1.2 数据探索
- - '####'
  - 2.3.1.3 数据加载器
- - '####'
  - 2.3.1.4 定义模型
- - '#####'
  - 2.3.1.4.1 Input Block
- - '#####'
  - 2.3.1.4.2 CONVOLUTION BLOCK
- - '#####'
  - 2.3.1.4.3 TRANSITION BLOCK
- - '#####'
  - 2.3.1.4.4 CONVOLUTION BLOCK
- - '#####'
  - 2.3.1.4.5 OUTPUT BLOCK
- - '####'
  - 2.3.1.5 训练过程
- - '###'
  - 2.3.2 模型的第二种变体
- - '###'
  - 2.3.3 模型的第三种变体
- - '####'
  - 2.3.3.1 输入块
- - '####'
  - 2.3.3.2 卷积块 1
- - '####'
  - 2.3.3.3 卷积块 2
- - '####'
  - 2.3.3.4 输出块
- - '###'
  - 2.3.4 模型的第四种变体
- - '##'
  - 2.4 总结
- - '#'
  - 3. 构建目标检测模型
- - '##'
  - 3.1 使用提升级联进行目标检测
- - '##'
  - 3.2 归一化并将颜色转换为灰度
- - '##'
  - 3.3 应用程序应能处理不同尺度的图像
- - '##'
  - 3.4 绘制椭圆
- - '##'
  - 3.5 类似的多尺度操作
- - '##'
  - 3.6 绘制圆形
- - '##'
  - 3.7 保存的 xml 路径
- - '##'
  - 3.8 初始化用于检测的级联
- - '##'
  - 3.9 加载级联，先加载人脸，后加载眼睛
- - '##'
  - 3.10 启用视频处理
- - '##'
  - 3.11 启用分类器对人脸进行操作
- - '##'
  - 3.12 按下 ESC 键关闭 CV 视频感知
- - '##'
  - 3.13 R-CNN
- - '###'
  - 3.13.1 区域提议网络
- - '####'
  - 3.13.1.1 快速区域卷积神经网络
- - '####'
  - 3.13.1.2 区域提议网络的工作原理
- - '####'
  - 3.13.1.3 锚点生成层
- - '####'
  - 3.13.1.4 区域提议层
- - '##'
  - 3.14 Mask R-CNN
- - '###'
  - 3.14.1 前提条件
- - '##'
  - 3.15 YOLO
- - '##'
  - 3.16 YOLO V2/V3
- - '##'
  - 3.17 项目代码片段
- - '###'
  - 3.17.1 步骤 1：获取标注数据
- - '###'
  - 3.17.2 步骤 2：修复配置文件与训练
- - '###'
  - 3.17.3 模型文件
- - '####'
  - 3.17.3.1 根据 module_defs 中的模块配置构建层块的模块列表
- - '####'
  - 3.17.3.2 modules.add_module('activation', nn.PReLU(num_parameters=1, init=0.10))
- - '####'
  - 3.17.3.3 imagenet 均值和方差 https://pytorch.org/docs/stable/torchvision/models.html#classification
- - '####'
  - 3.17.3.4 初始化前面的 Conv2d() 偏置 (https://arxiv.org/pdf/1708.02002.pdf 第 3.3 节)
- - '####'
  - 3.17.3.5 注册模块列表和输出过滤器数量
- - '##'
  - 3.18 总结
- - '#'
  - 4. 构建图像分割模型
- - '##'
  - 4.1 图像分割
- - '###'
  - 4.1.1 PyTorch 的预训练支持
- - '####'
  - 4.1.1.1 语义分割
- - '#####'
  - 4.1.1.1.1 torchvision related imports
- - '#####'
  - 4.1.1.1.2 models and transforms
- - '#####'
  - 4.1.1.1.3 utilities for multiple images
- - '#####'
  - 4.1.1.1.4 generalise cast images to list
- - '#####'
  - 4.1.1.1.5 get an image on which segmentation needs to be done
- - '#####'
  - 4.1.1.1.6 batch for images
- - '#####'
  - 4.1.1.1.7 switching on eval mode
- - '#####'
  - 4.1.1.1.8 standard normalizing based on train config
- - '####'
  - 4.1.1.2 实例分割
- - '##'
  - 4.2 微调模型
- - '###'
  - 4.2.1 提取交通数据
- - '###'
  - 4.2.2 基本导入
- - '###'
  - 4.2.3 torch 导入
- - '###'
  - 4.2.4 torchvision 导入
- - '###'
  - 4.2.5 图像工具
- - '###'
  - 4.2.6 代码工具
- - '###'
  - 4.2.7 克隆 PyTorch 仓库以建立与原始训练完全相同的目录结构
- - '###'
  - 4.2.8 从 PyTorch 仓库导入
- - '###'
  - 4.2.9 初始化对象属性
- - '###'
  - 4.2.10 从 dir_path
- - '###'
  - 4.2.11 添加来自 PedMasks 目录的掩码列表
- - '###'
  - 4.2.12 添加来自目录列表的实际图像列表
- - '###'
  - 4.2.13 获取图像和掩码
- - '###'
  - 4.2.14 背景具有第一个 ID，因此排除它
- - '###'
  - 4.2.15 将掩码分割为二进制
- - '###'
  - 4.2.16 边界框
- - '###'
  - 4.2.17 从 PyTorch 仓库加载已在 COCO 上训练好的模型
- - '###'
  - 4.2.18 识别输入特征数量
- - '###'
  - 4.2.19 修改头部
- - '###'
  - 4.2.20 获取交通数据进行转换
- - '###'
  - 4.2.21 训练集与测试集划分
- - '###'
  - 4.2.22 定义训练和验证数据加载器
- - '###'
  - 4.2.23 由于处理的是行人和背景，类别数量为 2
- - '###'
  - 4.2.24 将模型移至 GPU（若可用）或 CPU
- - '###'
  - 4.2.25 获取 SGD 优化器
- - '###'
  - 4.2.26 设置步进学习率
- - '###'
  - 4.2.27 设置训练周期数
- - '###'
  - 4.2.28 保存模型的完整版本
- - '###'
  - 4.2.29 也可以选择保存状态字典版本
- - '###'
  - 4.2.30 PyTorch 帮助将模型设置为评估模式
- - '###'
  - 4.2.31 helper function to generate mask
- - '###'
  - 4.2.32 helper function to generate predictions
- - '###'
  - 4.2.33 print(pred[0][’labels’].numpy().max())
- - '##'
  - 4.3 总结
- - '#'
  - 5. 基于图像的搜索与推荐系统
- - '##'
  - 5.1 问题陈述
- - '##'
  - 5.2 方法与途径
- - '##'
  - 5.3 实现
- - '###'
  - 5.3.1 数据集
- - '###'
  - 5.3.2 安装与导入库
- - '####'
  - 5.3.2.1 导入 matplotlib 用于绘图
- - '####'
  - 5.3.2.2 导入 numpy 用于数值运算
- - '####'
  - 5.3.2.3 导入 pandas 用于预处理
- - '####'
  - 5.3.2.4 导入 joblib 用于转储和加载嵌入数据框
- - '####'
  - 5.3.2.5 导入 cv2 用于读取图像
- - '####'
  - 5.3.2.6 导入 cosine_similarity 用于查找图像间的相似度
- - '####'
  - 5.3.2.7 从 pandas 导入 flatten 用于展平二维数组
- - '####'
  - 5.3.2.8 导入以下库用于模型构建
- - '####'
  - 5.3.2.9 导入 cv 模型
- - '####'
  - 5.3.2.10 导入图像处理库
- - '###'
  - 5.3.3 导入与理解数据
- - '####'
  - 5.3.3.1 导入元数据
- - '####'
  - 5.3.3.2 显示前 10 行
- - '####'
  - 5.3.3.3 设置样式
- - '####'
  - 5.3.3.4 理解数据：统计有多少种不同的 articleType 并了解其频率
- - '####'
  - 5.3.3.5 创建列以存储图像位置 ID
- - '####'
  - 5.3.3.6 重置索引
- - '####'
  - 5.3.3.7 图像路径
- - '####'
  - 5.3.3.8 加载图像的函数
- - '####'
  - 5.3.3.9 定义图形
- - '####'
  - 5.3.3.10 循环处理图像
- - '####'
  - 5.3.3.11 绘图
- - '####'
  - 5.3.3.12 生成 {索引, 图像} 字典
- - '####'
  - 5.3.3.13 在图形中绘制图像，设置 2 行 3 列
- - '###'
  - 5.3.4 特征工程
- - '###'
  - 5.3.5 ResNet18
- - '####'
  - 5.3.5.1 Defining the input shape
- - '####'
  - 5.3.5.2 Loading the pretrained model
- - '####'
  - 5.3.5.3 selecting the layer
- - '####'
  - 5.3.5.4 evaluation
- - '####'
  - 5.3.5.5 scaling the data
- - '####'
  - 5.3.5.6 normalizing
- - '####'
  - 5.3.5.7 converting to tensor
- - '####'
  - 5.3.5.8 creating the missing image object
- - '####'
  - 5.3.5.9 function to get embeddings
- - '####'
  - 5.3.5.10 Testing if our vector_extraction function works well on sample image
- - '####'
  - 5.3.5.11 Plotting the sample image and its embeddings
- - '####'
  - 5.3.5.12 Testing if our vector_extraction function works well on sample image
- - '####'
  - 5.3.5.13 Plotting the sample image and its embeddings
- - '####'
  - 5.3.5.14 Finding the similarity between those two images
- - '####'
  - 5.3.5.15 output
- - '####'
  - 5.3.5.16 Applying embeddings on subset of this huge dataset
- - '####'
  - 5.3.5.17 looping through images to get embeddings
- - '####'
  - 5.3.5.18 convert to series
- - '####'
  - 5.3.5.19 export the embeddings
- - '####'
  - 5.3.5.20 importing the embeddings
- - '####'
  - 5.3.5.21 exporting as pkl
- - '####'
  - 5.3.5.22 importing the pkl
- - '###'
  - 5.3.6 计算相似度与排序
- - '####'
  - 5.3.6.1 计算图像之间的相似度（使用嵌入值）
- - '####'
  - 5.3.6.2 预览前 4 行和前 4 列的相似度，以检查 cosine_sim 的结构
- - '####'
  - 5.3.6.3 将索引值存储在一个序列 index_vales 中，用于推荐
- - '####'
  - 5.3.6.4 定义一个基于余弦相似度分数给出推荐结果的函数
- - '####'
  - 5.3.6.5 将参考图像的索引赋值给 sim_ImId
- - '####'
  - 5.3.6.6 将所有其他图像与用户请求图像的余弦相似度存储为列表 sml_scr
- - '####'
  - 5.3.6.7 对 sml_scr 列表进行排序
- - '####'
  - 5.3.6.8 从 sml_scr 中提取前 n 个值
- - '####'
  - 5.3.6.9 ImId_rec 将返回相似图像的索引
- - '####'
  - 5.3.6.10 ImId_sim 将返回相似度分数的值
- - '####'
  - 5.3.6.11 示例如下
- - '###'
  - 5.3.7 可视化推荐结果
- - '####'
  - 5.3.7.1 获取推荐结果
- - '####'
  - 5.3.7.2 打印相似度分数
- - '####'
  - 5.3.7.3 绘制用户请求的图像
- - '####'
  - 5.3.7.4 生成一个 { 索引, 图像 } 的字典
- - '####'
  - 5.3.7.5 在图形中绘制相似图像，布局为 2 行 3 列
- - '###'
  - 5.3.8 从用户处获取图像输入并推荐相似产品
- - '####'
  - 5.3.8.1 加载图像并调整其大小
- - '####'
  - 5.3.8.2 计算余弦相似度
- - '####'
  - 5.3.8.3 打印余弦相似度
- - '####'
  - 5.3.8.4 提取前 10 个相似项目/图像的索引
- - '####'
  - 5.3.8.5 绘制用户请求项目的图像
- - '####'
  - 5.3.8.6 生成一个字典 { 索引, 图像 }
- - '####'
  - 5.3.8.7 在图形中绘制相似图像，2 行 5 列
- - '##'
  - 5.4 总结
- - '#'
  - 6. 姿态估计
- - '##'
  - 6.1 自上而下方法
- - '##'
  - 6.2 自下而上方法
- - '##'
  - 6.3 OpenPose
- - '###'
  - 6.3.1 分支-1
- - '###'
  - 6.3.2 分支-2
- - '##'
  - 6.4 HRNet（高分辨率网络）
- - '##'
  - 6.5 Higher HRNet
- - '##'
  - 6.6 PoseNet
- - '###'
  - 6.6.1 PoseNet 如何工作？
- - '####'
  - 6.6.1.1 单人姿态估计
- - '####'
  - 6.6.1.2 多人姿态估计
- - '####'
  - 6.6.1.3 PoseNet 的优缺点
- - '####'
  - 6.6.1.4 姿态估计的应用
- - '####'
  - 6.6.1.5 零售店视频测试案例
- - '##'
  - 6.7 实现
- - '###'
  - 6.7.1 步骤 1：确定要追踪的人体关键点列表
- - '####'
  - 6.7.1.1 人体关键点列表（共 17 个）
- - '###'
  - 6.7.2 步骤 2：确定关键点之间可能的连接关系
- - '####'
  - 6.7.2.1 人体关键点之间可能的连接关系，以形成结构
- - '###'
  - 6.7.3 步骤 3：从 PyTorch 库加载预训练模型
- - '####'
  - 6.7.3.1 从预训练的 keypointrcnn_resnet50_fpn 类创建模型
- - '####'
  - 6.7.3.2 调用 eval() 方法使模型进入推理模式
- - '###'
  - 6.7.4 步骤 4：输入图像预处理与建模
- - '####'
  - 6.7.4.1 导入 transforms 模块
- - '####'
  - 6.7.4.2 使用 opencv 读取图像
- - '####'
  - 6.7.4.3 预处理输入图像
- - '####'
  - 6.7.4.4 前向传播模型
- - '###'
  - 6.7.5 第 5 步：构建自定义函数以绘制输出
- - '###'
  - 6.7.6 第 6 步：在输入图像上绘制输出
- - '##'
  - 6.8 总结
- - '#'
  - 7. 图像异常检测
- - '##'
  - 7.1 异常检测
- - '###'
  - 7.1.1 方法 1：使用预训练分类模型
- - '####'
  - 7.1.1.1 步骤 1：导入所需库
- - '####'
  - 7.1.1.2 步骤 2：创建种子和确定性函数
- - '####'
  - 7.1.1.3 步骤 3：设置超参数
- - '####'
  - 7.1.1.4 步骤 4：导入数据集
- - '####'
  - 7.1.1.5 第 5 步：图像预处理阶段
- - '#####'
  - 7.1.1.5.1 Checking the dataset
- - '####'
  - 7.1.1.6 第 6 步：加载预训练模型
- - '####'
  - 7.1.1.7 第 7 步：冻结模型
- - '####'
  - 7.1.1.8 第 8 步：训练模型
- - '####'
  - 7.1.1.9 第 9 步：评估模型
- - '#####'
  - 7.1.1.9.1 张量：归一化图像。
- - '###'
  - 7.1.2 方法 2：使用自编码器
- - '####'
  - 7.1.2.1 步骤 1：准备数据集对象
- - '#####'
  - 7.1.2.1.1 步骤 1
- - '#####'
  - 7.1.2.1.2 准备数据集对象
- - '#####'
  - 7.1.2.1.3 加载包含 65 个值的 .csv 数据集
- - '#####'
  - 7.1.2.1.4 前 64 个值表示 64 个灰度格式的像素值
- - '#####'
  - 7.1.2.1.5 最后 1 个值表示实际数字（范围在 0 到 9 之间）
- - '#####'
  - 7.1.2.1.6 使用辅助函数 "tensor_converter" 将 CSV 格式转换为归一化张量
- - '####'
  - 7.1.2.2 步骤 2：构建自编码器网络
- - '####'
  - 7.1.2.3 步骤 3：训练自编码器网络
- - '#####'
  - 7.1.2.3.1 步骤 3. 训练自编码器模型
- - '####'
  - 7.1.2.4 第 4 步：基于原始数据计算重建损失
- - '#####'
  - 7.1.2.4.1 设置自编码器为评估模式
- - '#####'
  - 7.1.2.4.2 存储重建的 MSE 损失
- - '#####'
  - 7.1.2.4.3 根据 MSE 损失从高到低对列表进行排序
- - '####'
  - 7.1.2.5 第 5 步：基于误差度量分数选择最异常的数字
- - '#####'
  - 7.1.2.5.1 第 5 步：显示数据集中最异常的手写数字
- - '####'
  - 7.1.2.6 输出
- - '##'
  - 7.2 总结
- - '#'
  - 8. 图像超分辨率
- - '##'
  - 8.1 使用最近邻概念进行放大
- - '##'
  - 8.2 理解双线性上采样
- - '##'
  - 8.3 变分自编码器
- - '###'
  - 8.3.1 VAE 表示
- - '##'
  - 8.4 生成对抗网络
- - '###'
  - 8.4.1 模型代码
- - '##'
  - 8.5 模型开发
- - '###'
  - 8.5.1 导入
- - '##'
  - 8.6 定义生成器模型
- - '##'
  - 8.7 继承类
- - '##'
  - 8.8 初始化顺序网络 - 期望输入为 64x3
- - '##'
  - 8.9 添加 16 个残差卷积块
- - '##'
  - 8.10 定义前向传播 -> 3 个卷积块
- - '##'
  - 8.11 初始化权重
- - '##'
  - 8.12 为批归一化添加支持
- - '##'
  - 8.13 运行应用程序
- - '##'
  - 8.14 总结
- - '#'
  - 9. 视频分析
- - '##'
  - 9.1 问题陈述
- - '##'
  - 9.2 方法
- - '##'
  - 9.3 实现
- - '###'
  - 9.3.1 安装所需包
- - '###'
  - 9.3.2 导入包
- - '###'
  - 9.3.3 数据
- - '###'
  - 9.3.4 将所需视频上传到 Google Colab
- - '####'
  - 9.3.4.1 上传视频
- - '###'
  - 9.3.5 将视频转换为一系列图像
- - '####'
  - 9.3.5.1 导入视频
- - '####'
  - 9.3.5.2 错误处理
- - '####'
  - 9.3.5.3 导出图像
- - '###'
  - 9.3.6 图像提取
- - '####'
  - 9.3.6.1 为第一个视频提取并存储图像
- - '####'
  - 9.3.6.2 为停车场视频提取图像
- - '###'
  - 9.3.7 数据准备
- - '####'
  - 9.3.7.1 调整图像大小
- - '####'
  - 9.3.7.2 归一化
- - '####'
  - 9.3.7.3 创建空图像
- - '####'
  - 9.3.7.4 遍历每张图像
- - '####'
  - 9.3.7.5 输出
- - '###'
  - 9.3.8 识别零售店的热点区域
- - '####'
  - 9.3.8.1 生成热力图的函数
- - '####'
  - 9.3.8.2 定义图形
- - '####'
  - 9.3.8.3 定义尺寸
- - '####'
  - 9.3.8.4 求和
- - '####'
  - 9.3.8.5 添加原始图像和新生成的热力图图像
- - '####'
  - 9.3.8.6 生成原始图像
- - '####'
  - 9.3.8.7 设置坐标轴
- - '####'
  - 9.3.8.8 定位器
- - '####'
  - 9.3.8.9 调整子图
- - '####'
  - 9.3.8.10 显示图像
- - '####'
  - 9.3.8.11 生成密度图像
- - '####'
  - 9.3.8.12 设置坐标轴
- - '####'
  - 9.3.8.13 定位器
- - '####'
  - 9.3.8.14 调整子图
- - '####'
  - 9.3.8.15 添加计数
- - '####'
  - 9.3.8.16 显示图像
- - '####'
  - 9.3.8.17 带位置信息的图像名称
- - '####'
  - 9.3.8.18 保存图像
- - '####'
  - 9.3.8.19 统计人数
- - '####'
  - 9.3.8.20 简单预处理。
- - '####'
  - 9.3.8.21 获取图像的高度和宽度
- - '####'
  - 9.3.8.22 调整图像大小
- - '####'
  - 9.3.8.23 变换
- - '####'
  - 9.3.8.24 定义模型
- - '####'
  - 9.3.8.25 加载模型
- - '####'
  - 9.3.8.26 评估模型
- - '####'
  - 9.3.8.27 最终计数
- - '####'
  - 9.3.8.28 返回计数、密度和密度图
- - '###'
  - 9.3.9 导入图像
- - '####'
  - 9.3.9.1 从路径中获取所有图像
- - '####'
  - 9.3.9.2 加载所有图像
- - '###'
  - 9.3.10 获取人群计数
- - '####'
  - 9.3.10.1 获取每张图像中的人数
- - '####'
  - 9.3.10.2 定义空列表
- - '####'
  - 9.3.10.3 遍历每张图像
- - '####'
  - 9.3.10.4 创建包含图像 ID 和计数的数据框
- - '####'
  - 9.3.10.5 排序并显示
- - '###'
  - 9.3.11 安保与监控
- - '####'
  - 9.3.11.1 从路径中获取所有图像
- - '####'
  - 9.3.11.2 加载停车场视频的所有图像
- - '####'
  - 9.3.11.3 获取每张图像中的人数
- - '####'
  - 9.3.11.4 检查视频的每一帧是否有任何移动
- - '####'
  - 9.3.11.5 将数据保存到数据框
- - '####'
  - 9.3.11.6 打印移动为‘yes’的图像
- - '###'
  - 9.3.12 识别人口统计特征（年龄与性别）
- - '####'
  - 9.3.12.1 导入函数
- - '####'
  - 9.3.12.2 读取图像
- - '####'
  - 9.3.12.3 检查性别
- - '##'
  - 9.4 总结
- - '#'
  - 10. 计算机视觉的可解释人工智能
- - '##'
  - 10.1 Grad-CAM
- - '##'
  - 10.2 Grad-CAM++
- - '##'
  - 10.3 NBDT
- - '###'
  - 10.3.1 步骤 1
- - '###'
  - 10.3.2 步骤 2
- - '###'
  - 10.3.3 步骤 3 和 4
- - '##'
  - 10.4 Grad-CAM 和 Grad-CAM++ 实现
- - '###'
  - 10.4.1 在单张图像上实现 Grad-CAM 和 Grad-CAM++
- - '####'
  - 10.4.1.1 Load the config to the "Grad CAM" and "Grad CAM ++"
- - '####'
  - 10.4.1.2 Only "Grad CAM" and "Grad CAM ++" available in this library
- - '###'
  - 10.4.2 单张图像上的 NBDT 实现
- - '####'
  - 10.4.2.1 加载图像并执行图像变换（调整大小、中心裁剪、转换为张量、归一化）的函数
- - '####'
  - 10.4.2.2 加载带有预训练权重的 NBDT 模型的函数
- - '####'
  - 10.4.2.3 输出分类结果和层次结构的函数
- - '##'
  - 10.5 总结
