name: Introduction to Transformers for NLP
name_cn: NLP 的 Transformer 入门指南
slug: introduction-to-transformers-for-nlp
toc:
- - '##'
  - 目录
- - '#'
  - 引言
- - '##'
  - 源代码
- - '#'
  - 1. 语言模型导论
- - '##'
  - NLP 的历史
- - '###'
  - 词袋模型
- - '###'
  - n-gram 模型
- - '###'
  - 循环神经网络
- - '#'
  - 循环神经网络（RNN）究竟是什么？
- - '##'
  - RNN 的工作原理
- - '##'
  - 语言模型
- - '###'
  - 使用语言模型能带来哪些优势？
- - '###'
  - 基于神经网络的语言模型
- - '#'
  - 总结
- - '##'
  - 总结
- - '#'
  - 2. Transformer 简介
- - '##'
  - 什么是 Seq2Seq 神经网络？
- - '##'
  - Transformer
- - '###'
  - Transformer
- - '####'
  - 编码器
- - '###'
  - 输入嵌入
- - '####'
  - 分词
- - '####'
  - 向量化
- - '####'
  - 位置编码
- - '#####'
  - 位置编码示例
- - '###'
  - 多头注意力
- - '###'
  - 查询、键和值向量
- - '###'
  - 自注意力
- - '###'
  - 将 Softmax 输出与值向量相乘
- - '###'
  - 计算多头注意力
- - '###'
  - 残差连接、层归一化与前馈网络
- - '###'
  - 解码器
- - '####'
  - 输入嵌入与位置编码
- - '####'
  - 第一层多头注意力
- - '####'
  - 第二层多头注意力
- - '####'
  - 线性分类器与最终 Softmax 输出概率
- - '##'
  - 总结
- - '#'
  - 3. BERT
- - '##'
  - BERT 的工作原理
- - '###'
  - 掩码语言模型（MLM）
- - '###'
  - 下一句预测（NSP）
- - '###'
  - NSP 推理
- - '##'
  - BERT 预训练模型
- - '##'
  - BERT 输入表示
- - '#'
  - BERT 的应用场景
- - '##'
  - 推文情感分析
- - '##'
  - BERT 在多种常见语言任务上的表现
- - '##'
  - 总结
- - '#'
  - 4. Hugging Face
- - '##'
  - Hugging Face 平台的特点
- - '###'
  - Hugging Face 的组件
- - '####'
  - Pipelines
- - '###'
  - 分词器
- - '###'
  - 填充
- - '###'
  - 截断
- - '###'
  - AutoModel
- - '#'
  - 使用分词器和模型创建一个 pipeline 实例
- - '#'
  - 分析我们在前面示例中使用的 3 个句子的情感
- - '##'
  - 总结
- - '#'
  - 5. 使用 Hugging Face 库的任务
- - '#'
  - Gradio：简介
- - '##'
  - 在 Hugging Face 上创建 Space
- - '##'
  - Hugging Face 任务
- - '###'
  - 问答
- - '##'
  - 翻译
- - '###'
  - 摘要
- - '#'
  - 使用 Gradio 应用进行摘要的两个对话框
- - '##'
  - Pegasus
- - '###'
  - 零样本学习
- - '####'
  - 零样本文本分类
- - '###'
  - 为什么需要零样本学习
- - '###'
  - 文本生成任务/模型
- - '###'
  - 代码
- - '####'
  - '`app.py`'
- - '####'
  - '`requirements.txt`'
- - '###'
  - 文本到文本生成
- - '##'
  - 使用 T5 进行英译德
- - '###'
  - 情感分析任务
- - '###'
  - 句子释义任务
- - '##'
  - 聊天机器人/对话机器人
- - '###'
  - 代码
- - '#'
  - keep history in the tensor
- - '#'
  - get response
- - '#'
  - html for display
- - '##'
  - 代码与代码注释生成
- - '###'
  - CodeGen
- - '###'
  - 代码
- - '#'
  - give input as text which reflects intent of the program.
- - '#'
  - give input as text which reflects intent of the program.
- - '###'
  - 代码注释生成器
- - '##'
  - 总结
- - '#'
  - 6. 微调预训练模型
- - '##'
  - 数据集
- - '#'
  - 打印所有可用的数据集
- - '##'
  - 微调预训练模型
- - '###'
  - 微调训练
- - '###'
  - 推理
- - '#'
  - 分词
- - '#'
  - 获取输出
- - '#'
  - 使用 softmax 生成概率
- - '#'
  - 获取最佳匹配结果
- - '##'
  - 总结
