name: Oracle Digital Assistant
name_cn: Oracle Digital Assistant
slug: oracle-digital-assistant
toc:
- - '#'
  - 引言
- - '#'
  - 致谢
- - '##'
  - 关于作者与技术审校者
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校者
- - '#'
  - 第一部分：基础
- - '#'
  - 第 1 章 Oracle 数字助手简介
- - '##'
  - 聊天机器人简史
- - '##'
  - Oracle 数字助手
- - '##'
  - Oracle 数字助手核心组件
- - '###'
  - 对话式 AI 引擎
- - '####'
  - 对话流执行
- - '####'
  - 企业数据集成
- - '####'
  - 人工坐席移交
- - '####'
  - Webview 组件
- - '####'
  - 渠道配置器
- - '####'
  - 可执行的洞察
- - '##'
  - 总结
- - '#'
  - 第二部分：设计与用户体验
- - '#'
  - 第 2 章 设计对话式用户体验
- - '##'
  - 为什么需要对话式用户体验？
- - '##'
  - 设计对话式用户体验
- - '###'
  - 目标
- - '###'
  - 用户
- - '####'
  - 创建人物角色
- - '###'
  - 用户画像的益处
- - '##'
  - 用户旅程地图
- - '###'
  - 如何创建用户/客户旅程地图？
- - '###'
  - 为什么客户旅程地图如此有用？
- - '###'
  - 下一步是什么？
- - '##'
  - 渠道
- - '###'
  - Facebook Messenger
- - '###'
  - Twitter
- - '##'
  - 对话设计
- - '###'
  - 聊天机器人的个性与语气
- - '####'
  - 构建个性
- - '####'
  - 语气
- - '###'
  - 对话流程
- - '###'
  - 设计激励性对话
- - '####'
  - 信息
- - '####'
  - 目标设定与承诺
- - '####'
  - 激励措施
- - '###'
  - 自主性
- - '###'
  - 反馈
- - '##'
  - 后端系统
- - '##'
  - 示例实体
- - '##'
  - 可用性测试
- - '###'
  - 使用测试场景
- - '###'
  - 由大量用户进行探索性测试
- - '###'
  - A/B 测试
- - '#'
  - 第 3 章 用例
- - '##'
  - 引言
- - '##'
  - 目标
- - '###'
  - 利益相关者是谁？
- - '###'
  - 为何需要聊天机器人？
- - '##'
  - 客户：用户画像
- - '###'
  - 描述哈罗德
- - '###'
  - 他的工作“日”
- - '###'
  - 他的工具
- - '###'
  - 他的目标
- - '##'
  - 用户旅程图
- - '###'
  - 接触点
- - '###'
  - 哈罗德的意图
- - '###'
  - 他的动机/需求
- - '###'
  - 需触发的情感
- - '##'
  - 渠道
- - '##'
  - 对话
- - '###'
  - 机器人的个性
- - '###'
  - 对话流程
- - '##'
  - 后端
- - '##'
  - 实体与表述
- - '###'
  - 用户说什么/写什么
- - '###'
  - Travvy 说什么/回答什么
- - '##'
  - 测试对话界面
- - '###'
  - 认知走查
- - '###'
  - 可用性测试
- - '##'
  - 训练聊天机器人
- - '###'
  - 三步训练法
- - '#'
  - 第三部分：实现您的数字助手
- - '#'
  - 第 4 章 设计与实现的交汇点
- - '##'
  - 引言
- - '###'
  - 注意
- - '##'
  - 实现 Travvy 设计
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 审查生成的工件
- - '###'
  - 注意
- - '###'
  - 测试生成的技能机器人
- - '###'
  - 注意
- - '##'
  - 总结
- - '#'
  - 第 5 章 深入实现细节
- - '##'
  - Oracle 数字助理（ODA）环境简介
- - '###'
  - 提示
- - '##'
  - 使用技能
- - '###'
  - 创建技能
- - '###'
  - 注意
- - '###'
  - 克隆技能
- - '###'
  - 导出技能
- - '###'
  - 导入技能
- - '###'
  - 创建技能的新版本
- - '###'
  - 删除技能
- - '###'
  - 发布技能
- - '###'
  - 导出对话日志
- - '###'
  - 显示渠道路由
- - '##'
  - 处理意图与表述
- - '###'
  - 提示
- - '##'
  - 创建意图
- - '##'
  - 向意图添加表述
- - '##'
  - 导出意图
- - '###'
  - 注意
- - '##'
  - 导入意图
- - '###'
  - 训练与测试意图
- - '##'
  - 使用实体
- - '###'
  - 内置实体
- - '####'
  - 简单实体
- - '####'
  - 复杂实体
- - '###'
  - 自定义实体
- - '###'
  - 创建实体
- - '###'
  - 向意图添加实体
- - '##'
  - 使用对话流
- - '###'
  - 注意
- - '###'
  - 上下文部分
- - '###'
  - 状态部分
- - '###'
  - 注意
- - '###'
  - Apache FreeMarker 模板语言
- - '###'
  - 对话流中的组件
- - '####'
  - 内置组件
- - '###'
  - 自定义组件与 Webview
- - '##'
  - 将技能添加到数字助理
- - '###'
  - 注意
- - '##'
  - 总结
- - '#'
  - 第四部分：增强您的数字助理
- - '#'
  - 第 6 章 通过渠道发布你的数字助手
- - '##'
  - Oracle 数字助手中的渠道类型
- - '###'
  - 用户渠道
- - '###'
  - 坐席集成
- - '###'
  - 应用程序渠道
- - '###'
  - 系统
- - '##'
  - 使用渠道
- - '###'
  - 注意
- - '##'
  - 创建用户频道
- - '##'
  - 频道路由
- - '##'
  - 使用 ODA 客户端示例测试渠道
- - '##'
  - 使用 ODA 客户端 SDK 从 Web UI 访问用户的 Web 渠道
- - '###'
  - 配置客户端 SDK
- - '###'
  - 注意
- - '##'
  - 为 Travvy 创建一个简单的 Web 应用程序
- - '###'
  - 添加 JavaScript 代码
- - '###'
  - 部署 Web 应用程序并测试
- - '##'
  - 自定义聊天小部件
- - '##'
  - 总结
- - '#'
  - 第 7 章 在数字助手中支持多种语言
- - '##'
  - 引言
- - '###'
  - 注意
- - '##'
  - 翻译是如何工作的？
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 提示
- - '###'
  - 翻译服务的陷阱
- - '##'
  - 为 Travvy 添加多语言支持
- - '###'
  - 注意
- - '##'
  - 使用翻译服务
- - '###'
  - 选择退出
- - '###'
  - 选择加入
- - '##'
  - 提示
- - '##'
  - 使用资源包
- - '##'
  - 注意
- - '##'
  - 从资源包回复
- - '###'
  - 注意
- - '###'
  - 从用户话语中确定语言
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 使用用户配置文件中的语言
- - '##'
  - 总结
- - '#'
  - 第 8 章 使用 Webview 组件
- - '##'
  - 什么是 Webview 组件？
- - '##'
  - Webview 组件架构
- - '###'
  - 在数字助手内部托管的 Webview 应用程序
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 外部托管的 Webview 应用程序
- - '##'
  - 前提条件
- - '##'
  - 用例
- - '##'
  - 在 Digital Assistant 内部托管的 Webview 应用程序
- - '###'
  - 技能实施
- - '####'
  - 'platformVersion: the version of the bots platform that this flow was written
    to work with'
- - '###'
  - Web 应用程序实施
- - '##'
  - 打包 Web 应用程序
- - '##'
  - 创建 Webview 服务
- - '##'
  - 外部托管的 Webview 应用
- - '###'
  - 创建中介服务
- - '###'
  - Web 应用实现
- - '###'
  - 技能实现
- - '####'
  - 'platformVersion: the version of the bots platform that this flow was written
    to work with'
- - '###'
  - 使用 ngrok 公开 Web 应用程序和中介服务
- - '##'
  - 总结
- - '#'
  - 第 9 章 将常见问题解答集成到您的数字助理中
- - '##'
  - 引言
- - '##'
  - 问答是如何工作的？
- - '###'
  - 在技能级别配置问答路由
- - '###'
  - 问答在运行时如何工作
- - '###'
  - 提示
- - '##'
  - 为我们的数字助手添加问答功能
- - '###'
  - 问答数据文件
- - '###'
  - 提示
- - '###'
  - 提示
- - '###'
  - 注意
- - '###'
  - 测试问答
- - '###'
  - 在对话流中添加问答功能
- - '##'
  - 总结
- - '#'
  - 第五部分：高级主题
- - '#'
  - 第 10 章 使用自定义组件扩展您的数字助手
- - '##'
  - 引言
- - '##'
  - 使用自定义组件的好处
- - '##'
  - 自定义组件的用例
- - '##'
  - 自定义组件的环境搭建
- - '##'
  - 自定义组件开发入门
- - '##'
  - 在本地运行自定义组件
- - '##'
  - 通过互联网公开自定义组件
- - '###'
  - 注意
- - '##'
  - 从 ODA 实例访问自定义组件
- - '##'
  - 后续章节概览
- - '##'
  - 更新自定义组件实现与本地调试
- - '###'
  - 注意
- - '##'
  - 将自定义组件部署到 ODA 实例中的嵌入式容器
- - '##'
  - 总结
- - '#'
  - 第 11 章 为您的数字助手添加语音和情感
- - '##'
  - 引言
- - '##'
  - 情感分析
- - '##'
  - 实施前需要考虑什么？
- - '##'
  - 从文本分析情感
- - '##'
  - 情感分析 API 的调用
- - '###'
  - 'platformVersion: the version of the bots platform that this flow was written
    to work with'
- - '##'
  - 语音
- - '###'
  - 注意
- - '###'
  - 您需要什么？
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 注意
- - '##'
  - 语音合成标记语言 (SSML)
- - '##'
  - 注意
- - '##'
  - Webhook 代码
- - '##'
  - 了解 Travvy
- - '###'
  - 向 ODA 添加 Webhook 通道
- - '###'
  - 配置 Alexa
- - '####'
  - Alexa 调用语句
- - '####'
  - Alexa 意图和槽位类型
- - '####'
  - 端点
- - '###'
  - 设置 Webhook
- - '###'
  - 测试 Alexa 通道
- - '##'
  - 语音用户体验设计指南
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F, G
- - '##'
  - H
- - '##'
  - I, J, K, L
- - '##'
  - M, N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
