name: Introduction to Prescriptive AI
name_cn: Prescriptive AI 入门指南
slug: introduction-to-prescriptive-ai
toc:
- - '#'
  - 目录
- - '#'
  - 引言
- - '#'
  - 致谢
- - '#'
  - 关于作者 关于技术审稿人
- - '#'
  - 第1章 决策智能概述
- - '##'
  - 人工智能的类型
- - '##'
  - 决策智能
- - '##'
  - 决策智能发展史
- - '##'
  - 人工智能应用面临的挑战
- - '##'
  - 决策智能如何弥合人工智能与商业之间的鸿沟？
- - '##'
  - 决策智能的必要性
- - '##'
  - 决策方式的演变
- - '###'
  - 挑战
- - '###'
  - 应用
- - '##'
  - 理解决策智能在 AI 生命周期中的定位
- - '###'
  - 决策智能方法论
- - '###'
  - 排版后的内容
- - '##'
  - 决策智能的一些潜在优缺点
- - '##'
  - 公司利用决策智能的示例
- - '##'
  - 结论
- - '#'
  - 第2章 决策智能需求
- - '##'
  - 为什么 AI 项目会失败？
- - '##'
  - DI 需求框架
- - '###'
  - 规划
- - '###'
  - 方法
- - '###'
  - 审批机制/组织对齐
- - '###'
  - 关键绩效指标
- - '####'
  - 定义清晰的指标
- - '###'
  - 价值
- - '####'
  - 投资回报率
- - '####'
  - 每次决策的价值
- - '##'
  - AI 预测的消费
- - '##'
  - 总结
- - '#'
  - 第3章 决策智能方法论
- - '##'
  - 决策
- - '###'
  - 决策的类型
- - '####'
  - 个人决策与群体决策
- - '####'
  - 单准则决策与多准则决策
- - '####'
  - 战略决策、战术决策与运营决策
- - '####'
  - 决策过程
- - '####'
  - 决策过程示例
- - '##'
  - 决策方法论
- - '###'
  - 纯人类决策
- - '####'
  - 随机决策
- - '####'
  - 基于道德/伦理的决策
- - '####'
  - 基于经验
- - '####'
  - 基于权威
- - '####'
  - 基于共识
- - '####'
  - 基于投票
- - '####'
  - 基于阈值
- - '####'
  - 基于首个可接受匹配
- - '####'
  - 基于优化/最大化
- - '####'
  - 纯人工决策导致的认知偏差
- - '###'
  - 人机协同决策
- - '####'
  - 基于指令/规则的系统
- - '###'
  - 数学模型
- - '###'
  - 概率模型
- - '###'
  - 基于人工智能的模型
- - '####'
  - 纯机器决策
- - '#####'
  - 自主系统
- - '##'
  - 结论
- - '#'
  - 第4章 解读不同方法论的结果
- - '##'
  - 决策智能方法论：数学模型
- - '###'
  - 线性模型
- - '###'
  - 非线性模型
- - '####'
  - 生成 N 个潜在起始点的列表
- - '####'
  - 如果算法成功，打印结果
- - '##'
  - 决策智能方法论：概率模型
- - '###'
  - 马尔可夫链
- - '####'
  - 问题陈述
- - '####'
  - 解决方案
- - '#####'
  - 步骤 1：导入所需的库
- - '#####'
  - 步骤 2：读取历史活动数据（用户路径和渠道的每日营销支出）
- - '#####'
  - 步骤 3：数据预处理
- - '#####'
  - 步骤 4：构建归因模型（用于比较的启发式模型和用于计算的马尔可夫模型）并将结果保存到数据框中
- - '#####'
  - 步骤 5：计算营销渠道的最佳预算
- - '##'
  - 决策智能方法论：AI/ML 模型
- - '###'
  - 问题陈述
- - '###'
  - 解决方案
- - '####'
  - 第 1 步：导入库并读取训练和测试数据
- - '####'
  - 第 2 步：数据预处理
- - '####'
  - 步骤 3：模型训练（逻辑回归）与评估
- - '##'
  - 结论
- - '#'
  - 第5章 将决策智能结果增强到业务工作流中
- - '##'
  - 挑战
- - '###'
  - 工作流程
- - '##'
  - 决策智能应用
- - '###'
  - 如何做及为何做？
- - '####'
  - 用户友好型界面
- - '###'
  - 将 AI 预测增强到业务工作流
- - '####'
  - 连接到业务工具
- - '####'
  - 映射数据
- - '##'
  - 结论
- - '#'
  - 第6章 行动、偏见与人在回路中
- - '##'
  - AI 中的关键伦理考量
- - '##'
  - 行动、偏见与人在回路中
- - '##'
  - 认知偏见
- - '###'
  - 为什么检测偏见很重要？
- - '###'
  - 类型
- - '###'
  - 忽视偏见会带来什么后果？
- - '###'
  - 偏见检测
- - '###'
  - 偏见工具的作用是什么？
- - '##'
  - 通过人工干预融入反馈
- - '###'
  - 人在回路（HITL）系统
- - '###'
  - 如何构建 HITL 系统？
- - '####'
  - 示例：客户流失
- - '##'
  - 结论
- - '#'
  - 第7章 案例研究
- - '##'
  - 案例研究 1：电信客户流失管理
- - '###'
  - 数据集详情
- - '####'
  - 人口统计信息
- - '####'
  - 服务信息
- - '####'
  - 流失状态
- - '###'
  - 阶段 1：AI 模型创建
- - '####'
  - 步骤 1：导入所需库
- - '####'
  - 步骤 2：加载电信客户流失数据集
- - '####'
  - 步骤 3：检查数据特征，查看数据中是否存在任何差异（例如，缺失值、错误的数据类型等）
- - '#####'
  - Column            Non-Null Count  Dtype
- - '####'
  - 步骤 4：数据预处理
- - '####'
  - 第 5 步：建模
- - '#####'
  - 超参数调优
- - '###'
  - 阶段 2：生成反事实
- - '####'
  - 反事实分析
- - '####'
  - DiCEML
- - '####'
  - 步骤 6：构建反事实解释器对象
- - '#####'
  - dice 数据初始化
- - '#####'
  - dice 模型初始化
- - '#####'
  - 将模型和数据整合在一起
- - '###'
  - 阶段 3：假设分析
- - '####'
  - 步骤 7：使用解释器对象生成保留客户的可行策略
- - '####'
  - 步骤 8：使用假设分析获取正确的客户保留策略集（基于约束条件）
- - '##'
  - 案例研究 2：手机定价/配置策略
- - '###'
  - 阶段 1：AI 模型创建
- - '####'
  - 步骤 1：导入所需库
- - '####'
  - 步骤 2：加载数据集
- - '####'
  - 步骤 3：检查数据特征，查看数据中是否存在任何差异（例如，缺失值、错误的数据类型等）
- - '#####'
  - Column        Non-Null Count  Dtype
- - '####'
  - 步骤 4：建模
- - '#####'
  - Column        Non-Null Count  Dtype
- - '###'
  - 阶段 2：生成反事实
- - '###'
  - 阶段 3：假设分析
- - '####'
  - 步骤 5：使用解释器对象生成可能的定价策略
- - '####'
  - 步骤 6：使用假设分析为给定手机找到正确的定价策略
- - '##'
  - 结论
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
